import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const CORS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-verstak-access,apikey","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8"};
const json=(x:any,status=200)=>new Response(JSON.stringify(x),{status,headers:CORS});
const clean=(v:any,n=500)=>String(v??"").trim().slice(0,n);
const hex=(b:Uint8Array)=>[...b].map(x=>x.toString(16).padStart(2,"0")).join("");
const unhex=(h:string)=>new Uint8Array((h.match(/.{1,2}/g)||[]).map(x=>parseInt(x,16)));
const sha=async(s:string)=>hex(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s))));
const derive=async(pin:string,salt:string,it:number)=>{const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(pin),"PBKDF2",false,["deriveBits"]);return hex(new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:unhex(salt),iterations:it},k,256)))};
const same=(a:string,b:string)=>{if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0};
const randHex=(n:number)=>{const b=new Uint8Array(n);crypto.getRandomValues(b);return hex(b)};
const randToken=()=>{const b=new Uint8Array(32);crypto.getRandomValues(b);return btoa(String.fromCharCode(...b)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")};
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:CORS});if(req.method!=="POST")return json({ok:false,error:"method_not_allowed"},405);const base=Deno.env.get("SUPABASE_URL"),svc=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!base||!svc)return json({ok:false,error:"server_not_configured"},500);const db=createClient(base,svc,{auth:{persistSession:false}});const body=await req.json().catch(()=>({})),action=clean(body.action,80);const dispatch=(qid:string,ship:string)=>{if(ship!=="SHIP-VERSTAK-SASHA-85C4A3")return;const p=fetch(`${base}/functions/v1/verstak-solai-runtime`,{method:"POST",headers:{"content-type":"application/json","authorization":`Bearer ${svc}`},body:JSON.stringify({queueId:qid})}).catch(()=>null);const er=(globalThis as any).EdgeRuntime;if(er?.waitUntil)er.waitUntil(p);else void p};
if(action==="login"){const id=clean(body.setkaId,64).toUpperCase(),pin=clean(body.pin,16);if(!/^SETKA-H-[A-Z0-9]{4}-[A-Z0-9]{4}$/.test(id)||!/^[0-9]{6}$/.test(pin))return json({ok:false,error:"invalid_credentials"},401);let q=db.from("api_verstak_user_credentials_v1").select("*").eq("login_setka_id",id).eq("state","ACTIVE");const hint=clean(body.shipCode,100);if(hint)q=q.eq("ship_code",hint);const {data:c,error}=await q.limit(2);if(error||!c?.length)return json({ok:false,error:"invalid_credentials"},401);if(c.length>1&&!hint)return json({ok:false,error:"ship_required"},409);const cr:any=c[0];if(cr.locked_until&&Date.parse(cr.locked_until)>Date.now())return json({ok:false,error:"temporarily_locked"},429);const got=await derive(pin,cr.pin_salt_hex,Number(cr.pbkdf2_iterations)||120000);if(!same(got,cr.pin_hash_hex)){const n=(Number(cr.failed_attempts)||0)+1,l=n>=5?new Date(Date.now()+600000).toISOString():null;await db.from("api_verstak_user_credentials_v1").update({failed_attempts:n,locked_until:l,last_failed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("identity_id",cr.identity_id).eq("ship_code",cr.ship_code);return json({ok:false,error:l?"temporarily_locked":"invalid_credentials"},l?429:401)}const {data:i}=await db.from("api_identities_v1").select("setka_id,status").eq("id",cr.identity_id).maybeSingle();if(!i||i.status!=="active")return json({ok:false,error:"identity_inactive"},403);const tok=randToken(),th=await sha(tok),exp=new Date(Date.now()+30*86400000).toISOString();const {error:se}=await db.from("api_verstak_user_sessions_v1").insert({identity_id:cr.identity_id,ship_code:cr.ship_code,session_token_sha256:th,expires_at:exp,user_agent:clean(req.headers.get("user-agent"),500),created_via:"SETKA_ID_PIN"});if(se)return json({ok:false,error:"session_create_failed",detail:se.message},500);await db.from("api_verstak_user_credentials_v1").update({failed_attempts:0,locked_until:null,last_login_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("identity_id",cr.identity_id).eq("ship_code",cr.ship_code);const {data:inv}=await db.from("api_verstak_access_invites_v1").select("display_name_ru").eq("identity_id",cr.identity_id).eq("ship_code",cr.ship_code).order("created_at",{ascending:false}).limit(1).maybeSingle();return json({ok:true,accessToken:tok,expiresAt:exp,identity:{setkaId:i.setka_id,displayNameRu:inv?.display_name_ru||"Пользователь"},shipCode:cr.ship_code})}
const access=req.headers.get("x-verstak-access")||"";if(access.length<20)return json({ok:false,error:"access_required"},401);const th=await sha(access);let actor="",ship="",name="Пользователь",mode="",sid:string|null=null;const {data:s}=await db.from("api_verstak_user_sessions_v1").select("session_id,identity_id,ship_code,state,expires_at").eq("session_token_sha256",th).maybeSingle();if(s&&s.state==="ACTIVE"&&Date.parse(s.expires_at)>Date.now()){actor=s.identity_id;ship=s.ship_code;mode="SETKA_ID_PIN";sid=s.session_id;await db.from("api_verstak_user_sessions_v1").update({last_used_at:new Date().toISOString()}).eq("session_id",s.session_id);const {data:v}=await db.from("api_verstak_access_invites_v1").select("display_name_ru").eq("identity_id",actor).eq("ship_code",ship).order("created_at",{ascending:false}).limit(1).maybeSingle();name=v?.display_name_ru||name}else{const {data:v,error}=await db.from("api_verstak_access_invites_v1").select("invite_code,identity_id,ship_code,display_name_ru,state,expires_at").eq("token_sha256",th).maybeSingle();if(error||!v||v.state!=="ACTIVE"||(v.expires_at&&Date.parse(v.expires_at)<Date.now()))return json({ok:false,error:"access_denied",detail:error?.message||null},401);actor=v.identity_id;ship=v.ship_code;name=v.display_name_ru;mode="INVITE";await db.from("api_verstak_access_invites_v1").update({last_used_at:new Date().toISOString()}).eq("invite_code",v.invite_code)}const {data:ident}=await db.from("api_identities_v1").select("setka_id,status").eq("id",actor).maybeSingle();if(!ident||ident.status!=="active")return json({ok:false,error:"identity_inactive"},403);
if(action==="set_pin"){const pin=clean(body.pin,16);if(!/^[0-9]{6}$/.test(pin))return json({ok:false,error:"pin_must_be_6_digits"},400);const salt=randHex(16),it=120000,ph=await derive(pin,salt,it);const {error}=await db.from("api_verstak_user_credentials_v1").upsert({identity_id:actor,ship_code:ship,login_setka_id:ident.setka_id,pin_salt_hex:salt,pin_hash_hex:ph,pbkdf2_iterations:it,state:"ACTIVE",failed_attempts:0,locked_until:null,updated_at:new Date().toISOString()},{onConflict:"identity_id,ship_code"});return error?json({ok:false,error:"pin_setup_failed",detail:error.message},500):json({ok:true,setkaId:ident.setka_id,shipCode:ship,pinConfigured:true})}
if(action==="logout"){if(sid)await db.from("api_verstak_user_sessions_v1").update({state:"REVOKED"}).eq("session_id",sid);return json({ok:true})}
const {data:r,error:re}=await db.rpc("api_verstak_action_v1",{p_actor_id:actor,p_ship_code:ship,p_action:action,p_payload:body});if(re)return json({ok:false,error:"action_rpc_failed",detail:re.message},500);let out:any=r||{ok:false,error:"empty_response"};if(action==="bootstrap"){const {data:c}=await db.from("api_verstak_user_credentials_v1").select("state").eq("identity_id",actor).eq("ship_code",ship).maybeSingle();out={...out,identity:{setkaId:ident.setka_id,displayNameRu:name},pinConfigured:!!c,authMode:mode,features:{pin:true,pencil:true,customCompartments:true,boardComputer:true,transcript:true,projectCreation:true,setkaIdPinLogin:true,eventDrivenSolai:true},alpha:true};for(const q of (out.solaiQueue||[]).filter((x:any)=>x.status==="PENDING").slice(0,4))dispatch(String(q.id),ship)}if(out?.queueId)dispatch(String(out.queueId),ship);return json(out,out?.ok===false?400:200)});