// @ts-nocheck
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8"};
const J=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H});
const T=(v,m=400)=>String(v??"").trim().slice(0,m),N=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,O=v=>v&&typeof v==="object"&&!Array.isArray(v)?v:{};
async function sha(v){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function auth(k){if(!k)return false;const q=await db.from("admin_keys").select("id").eq("key_hash",await sha(T(k,300))).eq("active",true).maybeSingle();return!!q.data}
async function aliases(){const q=await db.from("prototype_v34_participant_aliases").select("device_id,label");if(q.error)throw q.error;return new Map((q.data||[]).map(x=>[x.device_id,T(x.label,120)]))}
function avg(xs,fn){return xs.length?xs.reduce((a,x)=>a+N(fn(x)),0)/xs.length:0}
function summary(xs){return{visits:xs.length,avgDurationMs:avg(xs,x=>x.duration_ms),avgTimeToFirstPatternMs:avg(xs,x=>O(x.metrics).timeToFirstPatternMs),avgTaps:avg(xs,x=>O(x.metrics).taps),avgBacktracks:avg(xs,x=>O(x.metrics).backtracks),avgRevisits:avg(xs,x=>O(x.metrics).screenRevisits),avgRapidRepeatTaps:avg(xs,x=>O(x.metrics).rapidRepeatTaps)}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return J({error:"method_not_allowed"},405);try{const b=await req.json();if(!(await auth(b.adminKey)))return J({error:"invalid_admin_key"},403);const action=T(b.action,50);if(action==="admin-ux"){const [q,a]=await Promise.all([db.from("prototype_v34_replay_digests").select("device_id,replay_key,kind,started_at,ended_at,duration_ms,event_count,metrics,pinned,raw_until,compacted_at").order("started_at",{ascending:false}).limit(3000),aliases()]);if(q.error)throw q.error;const rows=q.data||[],by=new Map();for(const r of rows){if(!by.has(r.device_id))by.set(r.device_id,[]);by.get(r.device_id).push(r)}for(const v of by.values())v.sort((x,y)=>Date.parse(x.started_at)-Date.parse(y.started_at));const first=[],repeat=[];for(const v of by.values())v.forEach((r,i)=>(i===0?first:repeat).push(r));return J({ok:true,summary:{all:summary(rows),first:summary(first),repeat:summary(repeat)},replays:rows.map(r=>({...r,name:a.get(r.device_id)||"Участник",rawAvailable:!r.compacted_at&&(!r.raw_until||Date.parse(r.raw_until)>Date.now())}))})}
if(action==="admin-replay"){const deviceId=T(b.deviceId,160),key=T(b.replayKey,300);const [d,r]=await Promise.all([db.from("prototype_v34_replay_digests").select("*").eq("device_id",deviceId).eq("replay_key",key).maybeSingle(),db.from("prototype_v34_raw_events").select("event_id,type,wall_at,session_id,phase,t_ms,payload").eq("device_id",deviceId).eq("replay_key",key).order("wall_at",{ascending:true}).limit(50000)]);if(d.error)throw d.error;if(r.error)throw r.error;return J({ok:true,digest:d.data,rawAvailable:(r.data||[]).length>0,events:r.data||[]})}
return J({error:"unknown_action"},400)}catch(e){console.error(e);return J({error:"server_error",detail:String(e?.message||e)},500)}});
