(() => {
  "use strict";
  const API="https://gfchgaphzhxufwdhrcis.supabase.co/functions/v1/setka-sensors-v13";
  const API_KEY="sb_publishable_1jL-x9_kp6rpfGghpSp_OA_OiXDnvsv";
  const ACCESS_KEY="setka-research:access-code:v1";
  const GUEST_ARCHIVE_KEY="setka-research:guest-archive:v11";
  const GUEST_ACTIVE_KEY="setka-research:guest-active-session:v11";
  const PENDING_GUEST_KEY="setka-research:sensor-guest-archive:v13";
  const app=document.getElementById("app"),library=document.getElementById("libraryScreen"),game=document.getElementById("gameScreen");
  if(!app||!library||!game)return;

  let device=null,characteristic=null,stream=null,sourceType=null,demoTimer=0,flushTimer=0,samples=[],lastBpm=null,lastAt=0,lastContext="",linking=false;
  const esc=v=>String(v??"").replace(/[&<>\"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
  const headers={"Content-Type":"application/json","apikey":API_KEY};
  async function post(action,p={}){const r=await fetch(API,{method:"POST",headers,body:JSON.stringify({action,...p})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"sensor_request_failed");return d}
  function auth(){const a=window.SetkaJourneyAuth||window.SetkaJourney?.getAuth?.();return a?.sessionId&&a?.sessionToken?a:null}
  function guestArchive(){try{return window.SetkaGuestTrial?.getArchive?.()||JSON.parse(localStorage.getItem(GUEST_ARCHIVE_KEY)||"null")}catch(_){return null}}
  function guestActive(){try{return JSON.parse(localStorage.getItem(GUEST_ACTIVE_KEY)||"null")}catch(_){return null}}
  function currentContext(){const a=auth();if(a)return{kind:"auth",key:`auth:${a.sessionId}`,sessionId:a.sessionId,sessionToken:a.sessionToken,guestArchiveId:null,guestSessionId:null,phase:readAuthPhase()};const g=guestArchive(),s=guestActive();if(g?.archiveId)return{kind:"guest",key:`guest:${g.archiveId}:${s?.id||"free"}`,guestArchiveId:g.archiveId,guestSessionId:s?.id||null,phase:s?.phase||"free"};return null}
  function readAuthPhase(){try{return JSON.parse(localStorage.getItem("setka-research:active-session:v5")||"null")?.phase||"free"}catch(_){return"free"}}
  function rememberGuest(){const g=guestArchive();if(g?.archiveId&&!localStorage.getItem(ACCESS_KEY))try{localStorage.setItem(PENDING_GUEST_KEY,g.archiveId)}catch(_){}}
  rememberGuest();

  const style=document.createElement("style");style.textContent=`
    #sensorMenuButton{position:absolute;z-index:46;right:68px;top:calc(env(safe-area-inset-top,0px) + 48px);width:40px;height:40px;border:1px solid rgba(255,255,255,.24);border-radius:50%;background:transparent;color:rgba(255,255,255,.72);display:grid;place-items:center;font-size:16px;cursor:pointer}#sensorMenuButton.connected{border-color:#fff;color:#fff;background:rgba(255,255,255,.08)}
    #sensorLivePill{position:absolute;z-index:130;right:20px;top:calc(env(safe-area-inset-top,0px) + 99px);height:27px;padding:0 10px;border:1px solid rgba(255,255,255,.22);border-radius:14px;background:rgba(0,0,0,.42);color:#fff;font-size:9px;letter-spacing:.04em;display:none;align-items:center;gap:6px;backdrop-filter:blur(4px);-webkit-backdrop-filter:blur(4px);font-variant-numeric:tabular-nums}#sensorLivePill.show{display:flex}#sensorLivePill i{width:6px;height:6px;border-radius:50%;background:#fff;display:block}
    #sensorLayer{position:fixed;inset:0;z-index:100120;background:#000;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","Helvetica Neue",Arial,sans-serif;overflow:auto;padding:calc(env(safe-area-inset-top,0px) + 28px) 18px calc(env(safe-area-inset-bottom,0px) + 28px)}#sensorLayer.hidden{display:none}.sensor-wrap{max-width:440px;margin:0 auto}.sensor-top{display:flex;gap:10px;align-items:center;margin-bottom:22px}.sensor-back{width:42px;height:42px;border:1px solid rgba(255,255,255,.25);border-radius:50%;background:transparent;color:#fff;font-size:20px}.sensor-kicker{font-size:9px;letter-spacing:.13em;color:rgba(255,255,255,.38)}.sensor-title{font-size:24px;font-weight:650;margin-top:3px}.sensor-card{border:1px solid rgba(255,255,255,.15);border-radius:22px;padding:17px;margin:10px 0;background:#080808}.sensor-status{display:flex;align-items:center;gap:10px}.sensor-heart{font-size:28px}.sensor-bpm{font-size:34px;font-weight:700;letter-spacing:-.02em}.sensor-unit{font-size:10px;color:rgba(255,255,255,.4)}.sensor-muted{font-size:11px;line-height:1.5;color:rgba(255,255,255,.43)}.sensor-btn{width:100%;min-height:50px;border-radius:25px;border:1px solid rgba(255,255,255,.3);background:transparent;color:#fff;font-size:14px;margin-top:9px}.sensor-btn.primary{background:#fff;color:#000;border-color:#fff;font-weight:650}.sensor-btn.danger{border-color:rgba(255,255,255,.18);color:rgba(255,255,255,.65)}.sensor-mini{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px}.sensor-kpi{border:1px solid rgba(255,255,255,.1);border-radius:15px;padding:10px;background:#050505}.sensor-kpi b{font-size:16px}.sensor-kpi span{display:block;font-size:8px;color:rgba(255,255,255,.4);margin-top:4px}.sensor-support{margin-top:14px;padding-top:13px;border-top:1px solid rgba(255,255,255,.09)}
  `;document.head.appendChild(style);

  const menu=document.createElement("button");menu.id="sensorMenuButton";menu.type="button";menu.textContent="♥";menu.setAttribute("aria-label","Подключить датчик пульса");library.appendChild(menu);
  const pill=document.createElement("div");pill.id="sensorLivePill";pill.innerHTML='<i></i><span>ДАТЧИК</span>';game.querySelector(".game-ui")?.appendChild(pill);
  const layer=document.createElement("div");layer.id="sensorLayer";layer.className="hidden";layer.innerHTML='<div class="sensor-wrap"></div>';document.body.appendChild(layer);const wrap=layer.querySelector(".sensor-wrap");

  function browserLabel(){if("bluetooth" in navigator)return"Прямое BLE-подключение доступно в этом браузере.";return"Этот браузер не даёт веб-странице прямой доступ к BLE-пульсометру. В прототипе можно включить тестовый поток; в мобильной SETKA этот же слой будет работать через нативный Bluetooth / Health APIs."}
  function render(){const connected=!!sourceType;wrap.innerHTML=`<div class="sensor-top"><button class="sensor-back">‹</button><div><div class="sensor-kicker">ФИЗИОЛОГИЧЕСКИЙ ПОТОК</div><div class="sensor-title">Датчик пульса</div></div></div><div class="sensor-card"><div class="sensor-status"><div class="sensor-heart">♥</div><div><div class="sensor-bpm">${lastBpm??"—"}</div><div class="sensor-unit">BPM ${connected?`· ${esc(device?.name||sourceType||"датчик")}`:"· датчик не подключён"}</div></div></div><div class="sensor-mini"><div class="sensor-kpi"><b>${stream?.sampleCount||samples.length||0}</b><span>ИЗМЕРЕНИЙ</span></div><div class="sensor-kpi"><b>${connected?"LIVE":"—"}</b><span>СТАТУС</span></div><div class="sensor-kpi"><b>${currentContext()?.phase||"—"}</b><span>КОНТЕКСТ</span></div></div></div><div class="sensor-card"><div style="font-size:14px;font-weight:600">Совместимые источники</div><div class="sensor-muted" style="margin-top:7px">Любой пульсометр, часы, браслет или спортивный датчик, который передаёт стандартный Bluetooth Heart Rate Service. Для устройств с закрытым протоколом позже подключаются отдельные адаптеры.</div>${!connected?`<button id="sensorBleConnect" class="sensor-btn primary" ${"bluetooth" in navigator?"":"disabled"}>Найти Bluetooth-пульсометр</button><button id="sensorDemoConnect" class="sensor-btn">Запустить тестовый поток</button>`:`<button id="sensorDisconnect" class="sensor-btn danger">Отключить датчик</button>`}<div class="sensor-support sensor-muted">${browserLabel()}</div></div><div class="sensor-card"><div style="font-size:14px;font-weight:600">Что пишется вместе с сессией</div><div class="sensor-muted" style="margin-top:7px">Точное время каждого измерения, BPM, источник, качество сигнала и доступные RR-интервалы. В админке поток накладывается на временную линию сессии и сохраняет границу до ID / после ID.</div></div>`;
    wrap.querySelector(".sensor-back").onclick=close;wrap.querySelector("#sensorBleConnect")?.addEventListener("click",connectBle);wrap.querySelector("#sensorDemoConnect")?.addEventListener("click",connectDemo);wrap.querySelector("#sensorDisconnect")?.addEventListener("click",()=>disconnect("user"));
  }
  function open(){render();layer.classList.remove("hidden");window.SetkaJourney?.track?.("sensor_screen",{})}
  function close(){layer.classList.add("hidden")}
  menu.onclick=open;

  async function ensureStream(force=false){const ctx=currentContext();if(!ctx)return null;if(stream&&!force&&lastContext===ctx.key)return stream;if(stream)await stopStream("context_changed");lastContext=ctx.key;const d=await post("start",{sessionId:ctx.sessionId,sessionToken:ctx.sessionToken,guestArchiveId:ctx.guestArchiveId,guestSessionId:ctx.guestSessionId,sourceType,deviceName:device?.name||sourceType,metadata:{phase:ctx.phase,webBluetooth:Boolean(device),prototype:true}});stream={id:d.streamId,token:d.streamToken,startedAt:d.startedAt,sampleCount:0};return stream}
  async function stopStream(reason="stopped"){clearTimeout(flushTimer);flushTimer=0;await flush();if(stream){try{await post("stop",{streamId:stream.id,streamToken:stream.token,reason})}catch(_){}stream=null}}
  function scheduleFlush(){if(flushTimer)return;flushTimer=setTimeout(()=>{flushTimer=0;flush()},1800)}
  async function flush(){if(!samples.length||!sourceType)return;try{await ensureStream();const batch=samples.splice(0,80);if(!stream){samples.unshift(...batch);return}await post("samples",{streamId:stream.id,streamToken:stream.token,items:batch});stream.sampleCount=(stream.sampleCount||0)+batch.length;renderPill();if(!layer.classList.contains("hidden"))render()}catch(_){}}
  function addSample(bpm,quality="ok",payload={}){const v=Math.round(Number(bpm));if(!Number.isFinite(v)||v<20||v>260)return;lastBpm=v;lastAt=Date.now();samples.push({observedAt:new Date().toISOString(),value:v,quality,payload:{...payload,phase:currentContext()?.phase||"free"}});if(samples.length>160)samples.splice(0,samples.length-160);scheduleFlush();renderPill();if(!layer.classList.contains("hidden"))render()}
  function renderPill(){menu.classList.toggle("connected",!!sourceType);pill.classList.toggle("show",!!sourceType&&game.classList.contains("active"));pill.querySelector("span").textContent=sourceType?`♥ ${lastBpm??"—"} BPM`:"ДАТЧИК"}

  function parseHeartRate(ev){const d=ev.target.value,flags=d.getUint8(0),is16=flags&1;let off=1;const bpm=is16?d.getUint16(off,true):d.getUint8(off);off+=is16?2:1;const contact=((flags>>1)&3),energy=Boolean(flags&8);if(energy)off+=2;const rr=[];if(flags&16)while(off+1<d.byteLength){rr.push(Math.round(d.getUint16(off,true)/1024*1000));off+=2}addSample(bpm,contact===3?"contact":"ok",{rrMs:rr,contactDetected:contact===3})}
  async function connectBle(){if(!("bluetooth" in navigator))return;try{device=await navigator.bluetooth.requestDevice({filters:[{services:["heart_rate"]}],optionalServices:["battery_service"]});device.addEventListener("gattserverdisconnected",()=>disconnect("device_disconnected"));const server=await device.gatt.connect(),service=await server.getPrimaryService("heart_rate");characteristic=await service.getCharacteristic("heart_rate_measurement");await characteristic.startNotifications();characteristic.addEventListener("characteristicvaluechanged",parseHeartRate);sourceType="ble_heart_rate";lastContext="";await ensureStream(true);renderPill();render();window.SetkaJourney?.track?.("sensor_connected",{source:"ble",deviceName:device.name||null})}catch(e){wrap.querySelector(".sensor-support")?.insertAdjacentHTML("beforebegin",'<div class="sensor-muted" style="margin-top:10px">Подключение не завершено.</div>')}}
  async function connectDemo(){sourceType="demo_heart_rate";device={name:"Тестовый поток"};let bpm=78;clearInterval(demoTimer);await ensureStream(true);demoTimer=setInterval(()=>{bpm=C(bpm+(Math.random()-.52)*3-(bpm-72)*.025,58,104);addSample(Math.round(bpm),"simulated",{simulated:true})},1000);renderPill();render();window.SetkaJourney?.track?.("sensor_connected",{source:"demo"})}
  function C(v,a,b){return Math.max(a,Math.min(b,v))}
  async function disconnect(reason="stopped"){clearInterval(demoTimer);demoTimer=0;if(characteristic){try{characteristic.removeEventListener("characteristicvaluechanged",parseHeartRate);await characteristic.stopNotifications()}catch(_){}}if(device?.gatt?.connected){try{device.gatt.disconnect()}catch(_){}}await stopStream(reason);device=null;characteristic=null;sourceType=null;lastContext="";renderPill();render();window.SetkaJourney?.track?.("sensor_disconnected",{reason})}

  async function linkGuestIfNeeded(){if(linking)return;const a=auth(),archiveId=localStorage.getItem(PENDING_GUEST_KEY);if(!a||!archiveId)return;linking=true;try{await post("link-guest",{sessionId:a.sessionId,sessionToken:a.sessionToken,guestArchiveId:archiveId});localStorage.removeItem(PENDING_GUEST_KEY);window.SetkaJourney?.track?.("sensor_guest_linked",{archiveId})}catch(_){}finally{linking=false}}
  function injectIntoPersonalScreens(){const guest=document.getElementById("guestLayer");if(guest&&!guest.classList.contains("hidden")){const title=guest.querySelector(".g-title")?.textContent?.trim();const body=guest.querySelector("#gBody");if(title==="Твой пробный час"&&body&&!body.querySelector(".sensor-personal-action")){const b=document.createElement("button");b.className="g-action sensor-personal-action";b.innerHTML='<b>Датчик пульса</b><span>Подключить live BPM к сессиям и паттернам</span>';b.onclick=open;body.appendChild(b)}}const research=document.getElementById("setkaResearchLayer");if(research&&!research.classList.contains("hidden")){const title=research.querySelector(".research-title")?.textContent?.trim();const grid=research.querySelector(".hub-grid");if(title==="Я"&&grid&&!grid.querySelector(".sensor-personal-action")){const b=document.createElement("button");b.className="hub-action sensor-personal-action";b.innerHTML='<span class="hub-icon">♥</span><span><span class="hub-title">Датчик пульса</span><span class="hub-sub">Live BPM во время SETKA-сессий</span></span>';b.onclick=open;grid.appendChild(b)}}}
  const observer=new MutationObserver(()=>{injectIntoPersonalScreens();renderPill()});observer.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:["class"]});
  window.addEventListener("setka:view",renderPill);window.addEventListener("pagehide",()=>{try{flush()}catch(_){}});
  setInterval(()=>{rememberGuest();linkGuestIfNeeded();const ctx=currentContext();if(sourceType&&ctx&&ctx.key!==lastContext)ensureStream(true).catch(()=>{})},900);
  injectIntoPersonalScreens();renderPill();linkGuestIfNeeded();
  window.SetkaSensorV13={open,disconnect,getState:()=>({connected:!!sourceType,bpm:lastBpm,sourceType,streamId:stream?.id||null})};
})();