(()=>{
'use strict';
const API='https://gfchgaphzhxufwdhrcis.supabase.co/functions/v1/verstak-alpha';
const API_KEY='sb_publishable_1jL-x9_kp6rpfGghpSp_OA_OiXDnvsv';
const ACCESS_KEY='verstak-alpha:access:v1';
let access=localStorage.getItem(ACCESS_KEY)||'';
let state={boot:null,projectId:null,compartmentId:null,section:'bridge',pinMode:false,pencil:null,pencilEvents:[],pencilSeq:0,pencilStartedAt:0};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const time=v=>{try{return new Date(v).toLocaleString('ru-RU',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'})}catch{return ''}};
const toast=t=>{const el=$('#toast');el.textContent=t;el.classList.remove('hidden');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.add('hidden'),2600)};
async function api(action,payload={}){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json','apikey':API_KEY,'x-verstak-access':access},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false){const e=new Error(d.error||'request_failed');e.data=d;throw e}return d}
function takeHash(){const h=new URLSearchParams(location.hash.replace(/^#/,''));const t=h.get('access');if(t&&t.length>20){access=t;localStorage.setItem(ACCESS_KEY,t);history.replaceState(null,'',location.pathname+location.search)}}
function activeProject(){return state.boot?.projects?.find(p=>p.id===state.projectId)||state.boot?.projects?.[0]||null}
function activeComp(){return state.boot?.compartments?.find(c=>c.id===state.compartmentId)||state.boot?.compartments?.find(c=>c.project_id===state.projectId)||null}
async function refresh(){state.boot=await api('bootstrap');if(!state.projectId&&state.boot.projects?.length)state.projectId=state.boot.projects[0].id;if(state.projectId&&!state.boot.projects.some(p=>p.id===state.projectId))state.projectId=state.boot.projects[0]?.id||null;if(state.projectId&&!state.compartmentId)state.compartmentId=state.boot.compartments.find(c=>c.project_id===state.projectId)?.id||null;render()}
function render(){const b=state.boot;if(!b)return;$('#shipName').textContent=b.ship?.display_name_ru||'VERSTAK';$('#setkaId').textContent=b.identity?.setkaId||'';$('#projectCount').textContent=b.projects?.length||0;$('#pinCount').textContent=b.pins?.length||0;$('#queueCount').textContent=(b.solaiQueue||[]).filter(x=>x.status==='PENDING').length;renderProjects();renderCompartments();renderTranscript();renderPins();renderQueue();renderBridge();$$('.panel').forEach(x=>x.classList.toggle('active',x.id===`panel-${state.section}`));$$('.sector-btn').forEach(x=>x.classList.toggle('active',x.dataset.section===state.section));$('#pinTool').classList.toggle('on',state.pinMode);$('#pencilTool').classList.toggle('on',!!state.pencil);$('#pencilTool').textContent=state.pencil?'■ Завершить':'✏️ Карандаш'}
function renderBridge(){const p=activeProject();const last=state.boot.events?.[0];$('#bridgeCurrent').innerHTML=p?`<div class="kicker">Текущий проект</div><h2>${esc(p.title_ru)}</h2><div class="muted">${esc(p.description_ru||'Описание пока не добавлено.')}</div>`:`<div class="kicker">Старт</div><h2>Создай первый проект</h2><div class="muted">Этот корабль пустой специально. Первый проект создаёшь ты сам.</div>`;$('#bridgeLast').innerHTML=last?`<strong>${esc(last.summary_ru)}</strong><div class="meta">${time(last.occurred_at)}</div>`:'<span class="muted">Пока только рождение корабля.</span>'}
function renderProjects(){const host=$('#projects');const arr=state.boot.projects||[];if(!arr.length){host.innerHTML='<div class="empty">У тебя пока нет проектов.</div>';return}host.innerHTML=arr.map(p=>`<button class="project-card pin-target ${p.id===state.projectId?'active':''}" data-project="${p.id}" data-pin-key="project:${esc(p.project_code)}"><div class="project-title">${esc(p.title_ru)}</div><div class="meta">${esc(p.project_code)}</div></button>`).join('');host.querySelectorAll('[data-project]').forEach(el=>el.onclick=()=>{if(state.pinMode)return;state.projectId=el.dataset.project;state.compartmentId=state.boot.compartments.find(c=>c.project_id===state.projectId)?.id||null;render()})}
function renderCompartments(){const host=$('#compartments');if(!state.projectId){host.innerHTML='<div class="muted small">Сначала создай проект.</div>';return}const arr=(state.boot.compartments||[]).filter(c=>c.project_id===state.projectId);host.innerHTML=arr.map(c=>`<button class="compartment pin-target ${c.id===state.compartmentId?'active':''}" data-comp="${c.id}" data-pin-key="compartment:${esc(c.compartment_code)}">${esc(c.title_ru)}</button>`).join('');host.querySelectorAll('[data-comp]').forEach(el=>el.onclick=()=>{if(state.pinMode)return;state.compartmentId=el.dataset.comp;render()});const c=activeComp();$('#workspaceTitle').textContent=c?.title_ru||'Проект';$('#workspacePurpose').textContent=c?.purpose_ru||'Рабочее пространство проекта'}
function renderTranscript(){const host=$('#events');const arr=state.boot.events||[];host.innerHTML=arr.length?arr.map(e=>`<div class="event pin-target" data-pin-key="event:${e.event_no}"><div class="event-time">${time(e.occurred_at)}</div><div><strong>${esc(e.summary_ru)}</strong><div class="meta">${esc(e.event_type)} · ${esc(e.object_ref||'')}</div></div></div>`).join(''):'<div class="empty">Стенограмма пока пустая.</div>'}
function repliesFor(pin){const own=pin.verstak_pin_messages||[];const q=(state.boot.solaiQueue||[]).filter(x=>x.pin_code===pin.pin_code&&x.response_ru);return [...own.map(m=>({who:m.author_kind==='HUMAN'?'Саша':'Система',text:m.message_ru,at:m.created_at})),...q.map(x=>({who:'Солай',text:x.response_ru,at:x.responded_at||x.created_at}))]}
function renderPins(){const host=$('#pins');const arr=(state.boot.pins||[]).filter(p=>!state.projectId||p.project_id===state.projectId);host.innerHTML=arr.length?arr.map(p=>{const reps=repliesFor(p);return `<div class="pin"><div class="row"><span class="badge">📌 ${esc(p.pin_code)}</span><span class="coord">${p.x_norm!=null?`${Math.round(Number(p.x_norm)*100)}% × ${Math.round(Number(p.y_norm)*100)}%`:''}</span></div><div class="comment">${esc(p.comment_ru||p.target_label||p.target_key||'PIN')}</div><div class="meta">${esc(p.screen_key)} · ${time(p.created_at)}</div>${reps.map(r=>`<div class="reply"><b>${esc(r.who)}:</b> ${esc(r.text)}</div>`).join('')}<div class="row" style="margin-top:9px"><button class="btn ghost" data-reply-pin="${p.pin_code}">Ответить</button></div></div>`}).join(''):'<div class="empty">PIN пока нет. Нажми 📌 PIN и укажи на элемент экрана.</div>';host.querySelectorAll('[data-reply-pin]').forEach(b=>b.onclick=()=>openTextModal('Ответ к PIN','Напиши уточнение или ответ Солаю…',async text=>{await api('pin_message',{pinCode:b.dataset.replyPin,messageRu:text});toast('Ответ отправлен');await refresh()}))}
function renderQueue(){const host=$('#queue');const arr=state.boot.solaiQueue||[];host.innerHTML=arr.length?arr.map(q=>`<div class="queue-item"><div class="row"><span class="badge">${esc(q.request_kind)}</span><span class="badge">${esc(q.status)}</span></div><div style="margin-top:7px">${esc(q.question_ru||q.source_ref)}</div>${q.response_ru?`<div class="reply"><b>Солай:</b> ${esc(q.response_ru)}</div>`:'<div class="meta">Передано Солаю. Ответ появится здесь после обработки.</div>'}</div>`).join(''):'<div class="empty">Сообщений пока нет.</div>'}
function setSection(s){state.section=s;render()}
function openTextModal(title,placeholder,onOk,initial=''){const m=$('#modal');$('#modalTitle').textContent=title;const ta=$('#modalText');ta.placeholder=placeholder;ta.value=initial;m.classList.remove('hidden');$('#modalCancel').onclick=()=>m.classList.add('hidden');$('#modalOk').onclick=async()=>{const v=ta.value.trim();if(!v)return;$('#modalOk').disabled=true;try{await onOk(v);m.classList.add('hidden')}catch(e){toast('Ошибка: '+e.message)}finally{$('#modalOk').disabled=false}}}
function togglePin(){if(!state.projectId){toast('Сначала создай проект');return}state.pinMode=!state.pinMode;document.body.classList.toggle('pin-cursor',state.pinMode);toast(state.pinMode?'PIN: нажми на объект или точку':'PIN выключен');render()}
async function pinAt(ev,target){if(!state.pinMode)return;ev.preventDefault();ev.stopPropagation();const x=ev.clientX/window.innerWidth,y=ev.clientY/window.innerHeight;target?.classList.add('pin-highlight');setTimeout(()=>target?.classList.remove('pin-highlight'),800);state.pinMode=false;document.body.classList.remove('pin-cursor');const key=target?.dataset?.pinKey||target?.id||target?.getAttribute?.('aria-label')||target?.tagName||'screen';const label=(target?.innerText||target?.textContent||key).trim().slice(0,160);openTextModal('📌 Новый PIN','Что именно ты хочешь зафиксировать здесь?',async comment=>{await api('create_pin',{projectId:state.projectId,compartmentId:state.compartmentId,route:location.pathname,screenKey:state.section,targetKey:key,targetLabel:label,xNorm:x,yNorm:y,viewport:{w:innerWidth,h:innerHeight,dpr:devicePixelRatio},commentRu:comment});toast('PIN создан и передан Солаю');await refresh()});render()}
function capturePencil(ev){if(!state.pencil)return;const t=ev.target.closest?.('[data-no-pencil]')||ev.target;if(t?.dataset?.noPencil)return;const x=('clientX'in ev)?ev.clientX/window.innerWidth:null,y=('clientY'in ev)?ev.clientY/window.innerHeight:null;state.pencilSeq++;state.pencilEvents.push({seq:state.pencilSeq,eventType:ev.type.toUpperCase(),tMs:Date.now()-state.pencilStartedAt,xNorm:x,yNorm:y,targetKey:t?.dataset?.pinKey||t?.id||t?.tagName||'',targetLabel:(t?.innerText||t?.getAttribute?.('aria-label')||'').trim().slice(0,120),data:{tag:t?.tagName||'',href:t?.getAttribute?.('href')||'',checked:typeof t?.checked==='boolean'?t.checked:undefined}});if(state.pencilEvents.length>=18)flushPencil()}
async function flushPencil(){if(!state.pencil||!state.pencilEvents.length)return;const batch=state.pencilEvents.splice(0);try{await api('pencil_events',{sessionId:state.pencil.id,events:batch})}catch{state.pencilEvents.unshift(...batch)}}
async function togglePencil(){if(!state.projectId){toast('Сначала создай проект');return}if(!state.pencil){const d=await api('pencil_start',{projectId:state.projectId,compartmentId:state.compartmentId,route:location.pathname,screenKey:state.section});state.pencil=d.session;state.pencilStartedAt=Date.now();state.pencilSeq=0;state.pencilEvents=[];toast('Карандаш пишет действия. Текст полей не записывается.');render();return}await flushPencil();const id=state.pencil.id;openTextModal('✏️ Завершить запись','Что ты хотел сделать или что должно было произойти?',async intention=>{await api('pencil_finish',{sessionId:id,intentionRu:intention});state.pencil=null;toast('Запись сохранена и передана Солаю');await refresh()})}
async function createProject(){openTextModal('Новый проект','Название проекта',async title=>{const desc=$('#newProjectDesc').value.trim();const d=await api('create_project',{titleRu:title,descriptionRu:desc});state.projectId=d.project.id;state.compartmentId=d.defaultCompartment?.id||null;$('#newProjectDesc').value='';toast('Проект создан');await refresh()})}
async function createCompartment(){if(!state.projectId){toast('Сначала создай проект');return}openTextModal('Новый отсек','Например: Маркетинг, Логистика, Исследования…',async title=>{await api('create_compartment',{projectId:state.projectId,titleRu:title,kind:'CUSTOM',purposeRu:''});toast('Отсек создан');await refresh()})}
async function askBoard(){const q=$('#boardInput').value.trim();if(!q)return;$('#boardInput').value='';const d=await api('board_query',{projectId:state.projectId,questionRu:q});toast(d.messageRu||'Передано Солаю');await refresh()}
async function health(){try{const h=await api('health');$('#healthText').textContent=`${h.state} · ожидает Солая: ${h.pendingSolai}`;$('#healthDot').style.background='#49d17d'}catch{$('#healthText').textContent='Нет связи';$('#healthDot').style.background='#ff667a'}}
function bind(){$$('.sector-btn').forEach(b=>b.onclick=()=>setSection(b.dataset.section));$('#pinTool').onclick=togglePin;$('#pencilTool').onclick=togglePencil;$('#createProject').onclick=createProject;$('#createCompartment').onclick=createCompartment;$('#boardSend').onclick=askBoard;document.addEventListener('click',ev=>{if(state.pinMode){const target=ev.target.closest?.('.pin-target')||ev.target;pinAt(ev,target)}},true);document.addEventListener('pointerdown',capturePencil,true);document.addEventListener('click',capturePencil,true);window.addEventListener('pagehide',()=>{if(state.pencil)flushPencil()});}
async function init(){takeHash();if(!access){$('#gate').classList.remove('hidden');$('#main').classList.add('hidden');return}bind();try{await refresh();$('#main').classList.remove('hidden');$('#gate').classList.add('hidden');health();setInterval(()=>{refresh().catch(()=>{});health()},20000)}catch(e){$('#gate').classList.remove('hidden');$('#main').classList.add('hidden');$('#gateMsg').textContent='Доступ не принят или истёк.'}}
init();
})();