// @ts-nocheck
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8"};
const J=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H});
const T=(v:any,m=500)=>String(v??"").trim().slice(0,m),B=(v:any)=>!!v,N=(v:any,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const CHANNEL="yulia_lab_v34";
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function requireAdmin(key:string){if(!key)return false;const q=await db.from("admin_keys").select("id").eq("key_hash",await sha(key.trim())).eq("active",true).maybeSingle();if(q.error)throw q.error;return!!q.data}
async function policy(){const q=await db.from("prototype_v34_replay_settings").select("retention_days,sample_hz,last_compacted_at").eq("channel",CHANNEL).maybeSingle();if(q.error)throw q.error;return q.data||{retention_days:90,sample_hz:8,last_compacted_at:null}}
async function countTable(table:string){const q=await db.from(table).select("*",{count:"exact",head:true});if(q.error)throw q.error;return q.count||0}
async function rawEventsForDevice(deviceId:string){const q=await db.from("prototype_v34_raw_events").select("event_id,type,wall_at,visit_id,session_id,phase,t_ms,payload,replay_key").eq("device_id",deviceId).order("wall_at",{ascending:true}).limit(50000);if(q.error)throw q.error;return(q.data||[]).map((x:any)=>({id:x.event_id,type:x.type,wallAt:x.wall_at,visitId:x.visit_id,sessionId:x.session_id,phase:x.phase,tMs:x.t_ms,payload:x.payload,replayKey:x.replay_key}))}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return J({error:"method_not_allowed"},405);try{const b=await req.json().catch(()=>({})),a=T(b.action,80);
 if(a==="sync"){
   if(T(b.channel,80)!==CHANNEL)return J({error:"invalid_channel"},403);const deviceId=T(b.deviceId,180);if(!deviceId)return J({error:"missing_device_id"},400);const now=new Date().toISOString(),ex=await db.from("prototype_v34_devices").select("subject_key,label,first_seen_at").eq("device_id",deviceId).maybeSingle();if(ex.error)throw ex.error;const subjectKey=ex.data?.subject_key||"guest",label=String(subjectKey).startsWith("T-")?"Тестировщик":(ex.data?.label||"Гость"),firstSeen=ex.data?.first_seen_at||(b.firstSeenAt?new Date(b.firstSeenAt).toISOString():now);const row={device_id:deviceId,label,subject_key:subjectKey,channel:CHANNEL,first_seen_at:firstSeen,last_seen_at:now,app_version:"standalone-v40-private-local",active:true,updated_at:now};const q=ex.data?await db.from("prototype_v34_devices").update({label,channel:CHANNEL,last_seen_at:now,app_version:"standalone-v40-private-local",active:true,updated_at:now}).eq("device_id",deviceId):await db.from("prototype_v34_devices").insert(row);if(q.error){if(q.error.code!=="23505")throw q.error;}return J({ok:true,label,subjectKey,channel:CHANNEL,updatedAt:now,acceptedEvents:0,acceptedExposures:0,sessionCount:0,retentionDays:0,sampleHz:0,privacyMode:"local-personal-corpus",personalArchiveAccepted:false,rawTelemetryAccepted:false})
 }
 if(a.startsWith("admin-")){
   if(!(await requireAdmin(T(b.adminKey,300))))return J({error:"invalid_admin_key"},403);
   if(a==="admin-overview"){
     const d=await db.from("prototype_v34_devices").select("device_id,label,subject_key,channel,first_seen_at,last_seen_at,user_agent,viewport,app_version,active").eq("channel",CHANNEL).order("last_seen_at",{ascending:false});if(d.error)throw d.error;const ids=(d.data||[]).map((x:any)=>x.device_id);let sessions:any[]=[];if(ids.length){const s=await db.from("prototype_v34_sessions").select("*").in("device_id",ids).order("started_at",{ascending:false});if(s.error)throw s.error;sessions=s.data||[]}return J({ok:true,devices:d.data||[],sessions,channel:CHANNEL,privacyMode:"local-personal-corpus",legacySessionData:true})
   }
   if(a==="admin-device"){
     const deviceId=T(b.deviceId,180),d=await db.from("prototype_v34_devices").select("*").eq("device_id",deviceId).eq("channel",CHANNEL).maybeSingle();if(d.error)throw d.error;if(!d.data)return J({error:"device_not_found"},404);const s=await db.from("prototype_v34_snapshots").select("schema_version,captured_at,payload,updated_at").eq("device_id",deviceId).maybeSingle();if(s.error)throw s.error;const idx=await db.from("prototype_v34_sessions").select("*").eq("device_id",deviceId).order("started_at",{ascending:false});if(idx.error)throw idx.error;const events=await rawEventsForDevice(deviceId),dig=await db.from("prototype_v34_replay_digests").select("*").eq("device_id",deviceId).order("started_at",{ascending:false});if(dig.error)throw dig.error;return J({ok:true,device:d.data,snapshot:s.data?{...s.data,payload:{...(s.data.payload||{}),events}}:{schema_version:400,captured_at:null,updated_at:null,payload:{events:[],privacyMode:"local-personal-corpus",personalDataStored:false}},sessionIndex:idx.data||[],replayDigests:dig.data||[],privacyMode:"local-personal-corpus",legacyData:!!s.data})
   }
   if(a==="admin-replay-policy"){const p=await policy(),raw=await countTable("prototype_v34_raw_events"),dig=await db.from("prototype_v34_replay_digests").select("pinned,compacted_at");if(dig.error)throw dig.error;const ds=dig.data||[];return J({ok:true,policy:p,stats:{rawEvents:raw,replays:ds.length,pinned:ds.filter((x:any)=>x.pinned).length,compacted:ds.filter((x:any)=>x.compacted_at).length},legacyReadOnly:true})}
   if(a==="admin-set-replay-policy"){const days=Math.round(N(b.retentionDays));if(![30,60,90].includes(days))return J({error:"invalid_retention_days"},400);const q=await db.rpc("prototype_v34_set_replay_retention",{p_days:days});if(q.error)throw q.error;return J({ok:true,retentionDays:days})}
   if(a==="admin-replay-digests"){let q=db.from("prototype_v34_replay_digests").select("*").order("started_at",{ascending:false}).limit(1000);if(b.deviceId)q=q.eq("device_id",T(b.deviceId,180));const r=await q;if(r.error)throw r.error;return J({ok:true,items:r.data||[],legacyReadOnly:true})}
   if(a==="admin-pin-replay"){const deviceId=T(b.deviceId,180),key=T(b.replayKey,260),pinned=B(b.pinned),q=await db.from("prototype_v34_replay_digests").update({pinned,updated_at:new Date().toISOString()}).eq("device_id",deviceId).eq("replay_key",key).select("replay_key,pinned").maybeSingle();if(q.error)throw q.error;if(!q.data)return J({error:"replay_not_found"},404);return J({ok:true,...q.data})}
   if(a==="admin-compact-now"){const q=await db.rpc("prototype_v34_compact_replays");if(q.error)throw q.error;return J({ok:true,removed:q.data||0})}
 }
 return J({error:"unknown_action"},400)
}catch(e){console.error(e);return J({error:"server_error",detail:String(e?.message||e)},500)}});