// @ts-nocheck
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8"};
const J=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H});
const T=(v,m=400)=>String(v??"").trim().slice(0,m);const N=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
async function sha(v){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("")}
function token(){const a=new Uint8Array(32);crypto.getRandomValues(a);return Array.from(a,b=>b.toString(16).padStart(2,"0")).join("")}
async function session(id,t){if(!id||!t)return null;const h=await sha(t);const q=await db.from("sessions").select("id,participant_id,request_key,research_started").eq("id",id).eq("session_token_hash",h).maybeSingle();return q.data||null}
async function admin(key){if(!key)return false;const h=await sha(key.trim());const q=await db.from("admin_keys").select("id").eq("key_hash",h).eq("active",true).maybeSingle();return !!q.data}
async function streamAuth(id,t){if(!id||!t)return null;const h=await sha(t);const q=await db.from("physiological_streams").select("*").eq("id",id).eq("stream_token_hash",h).maybeSingle();return q.data||null}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return J({error:"method_not_allowed"},405);try{const b=await req.json();const a=T(b?.action,80);
 if(a==="start"){
   let participantId=null,sessionId=null;const s=await session(T(b.sessionId,80),T(b.sessionToken,220));if(s){participantId=s.participant_id;sessionId=s.id}
   const guestArchiveId=T(b.guestArchiveId,140)||null;if(!participantId&&!guestArchiveId)return J({error:"missing_identity"},400);
   const raw=token(),hash=await sha(raw);const row={participant_id:participantId,session_id:sessionId,guest_archive_id:guestArchiveId,guest_session_id:T(b.guestSessionId,140)||null,source_type:T(b.sourceType,60)||"ble_heart_rate",device_name:T(b.deviceName,180)||null,metric:"heart_rate",unit:"bpm",stream_token_hash:hash,status:"active",metadata:b.metadata&&typeof b.metadata==="object"?b.metadata:{}};
   const q=await db.from("physiological_streams").insert(row).select("id,started_at").single();if(q.error)throw q.error;return J({ok:true,streamId:q.data.id,streamToken:raw,startedAt:q.data.started_at})
 }
 if(a==="samples"){
   const st=await streamAuth(T(b.streamId,80),T(b.streamToken,220));if(!st)return J({error:"invalid_stream"},403);const items=Array.isArray(b.items)?b.items.slice(0,120):[];if(!items.length)return J({ok:true,count:0});const rows=[];let sum=0,min=Infinity,max=-Infinity;
   for(const x of items){const v=N(x?.value,NaN);if(!Number.isFinite(v)||v<20||v>260)continue;const at=x?.observedAt?new Date(x.observedAt):new Date();const val=Math.round(v*10)/10;sum+=val;min=Math.min(min,val);max=Math.max(max,val);rows.push({stream_id:st.id,participant_id:st.participant_id,session_id:st.session_id,guest_archive_id:st.guest_archive_id,guest_session_id:st.guest_session_id,observed_at:Number.isNaN(at.getTime())?new Date().toISOString():at.toISOString(),metric:"heart_rate",value:val,unit:"bpm",quality:T(x?.quality,30)||null,payload:x?.payload&&typeof x.payload==="object"?x.payload:{}})}
   if(rows.length){const iq=await db.from("physiological_samples").insert(rows);if(iq.error)throw iq.error;const oldCount=N(st.sample_count),newCount=oldCount+rows.length,oldAvg=N(st.avg_value,0),avg=(oldAvg*oldCount+sum)/newCount;const uq=await db.from("physiological_streams").update({sample_count:newCount,min_value:st.min_value==null?min:Math.min(N(st.min_value),min),max_value:st.max_value==null?max:Math.max(N(st.max_value),max),avg_value:avg,last_sample_at:rows[rows.length-1].observed_at}).eq("id",st.id);if(uq.error)throw uq.error}
   return J({ok:true,count:rows.length})
 }
 if(a==="stop"){
   const st=await streamAuth(T(b.streamId,80),T(b.streamToken,220));if(!st)return J({error:"invalid_stream"},403);const q=await db.from("physiological_streams").update({ended_at:new Date().toISOString(),status:T(b.reason,40)||"stopped"}).eq("id",st.id);if(q.error)throw q.error;return J({ok:true})
 }
 if(a==="link-guest"){
   const s=await session(T(b.sessionId,80),T(b.sessionToken,220));if(!s)return J({error:"invalid_session"},403);const archive=T(b.guestArchiveId,140);if(!archive)return J({error:"missing_archive"},400);
   const imported=await db.from("sessions").select("id,meta").eq("participant_id",s.participant_id);if(imported.error)throw imported.error;const map=new Map();for(const x of imported.data||[]){if(x.meta?.guestArchiveId===archive&&x.meta?.guestSessionId)map.set(String(x.meta.guestSessionId),x.id)}
   const qs=await db.from("physiological_streams").select("id,guest_session_id").eq("guest_archive_id",archive);if(qs.error)throw qs.error;let guestSessionStreams=0,linkedSessionStreams=0;for(const x of qs.data||[]){const guestId=String(x.guest_session_id||"");if(guestId)guestSessionStreams++;const linked=map.get(guestId)||null;if(linked)linkedSessionStreams++;await db.from("physiological_streams").update({participant_id:s.participant_id,session_id:linked,converted_at:new Date().toISOString()}).eq("id",x.id);await db.from("physiological_samples").update({participant_id:s.participant_id,session_id:linked}).eq("stream_id",x.id)}return J({ok:true,streams:(qs.data||[]).length,guestSessionStreams,linkedSessionStreams})
 }
 if(a==="admin-overview"){
   if(!(await admin(T(b.adminKey,300))))return J({error:"invalid_admin_key"},403);const q=await db.from("physiological_streams").select("id,participant_id,session_id,guest_archive_id,guest_session_id,source_type,device_name,started_at,ended_at,last_sample_at,status,sample_count,min_value,max_value,avg_value,converted_at,metadata").order("started_at",{ascending:false}).limit(1000);if(q.error)throw q.error;const rows=q.data||[];const pids=[...new Set(rows.map(x=>x.participant_id).filter(Boolean))];const sids=[...new Set(rows.map(x=>x.session_id).filter(Boolean))];let ps=[],ss=[];if(pids.length){const r=await db.from("participants").select("id,access_code,label").in("id",pids);ps=r.data||[]}if(sids.length){const r=await db.from("sessions").select("id,request_key,research_started,started_at").in("id",sids);ss=r.data||[]}const pm=new Map(ps.map(x=>[x.id,x])),sm=new Map(ss.map(x=>[x.id,x]));return J({ok:true,items:rows.map(x=>({...x,participant:pm.get(x.participant_id)||null,session:sm.get(x.session_id)||null})),overview:{streams:rows.length,live:rows.filter(x=>x.status==="active").length,converted:rows.filter(x=>x.participant_id).length,samples:rows.reduce((a,x)=>a+N(x.sample_count),0),devices:new Set(rows.map(x=>x.device_name).filter(Boolean)).size}})
 }
 if(a==="admin-stream"){
   if(!(await admin(T(b.adminKey,300))))return J({error:"invalid_admin_key"},403);const id=T(b.streamId,80);const q=await db.from("physiological_streams").select("*").eq("id",id).single();if(q.error)throw q.error;const sr=await db.from("physiological_samples").select("id,observed_at,value,quality,payload").eq("stream_id",id).order("observed_at").limit(6000);if(sr.error)throw sr.error;let participant=null,sessionRow=null,markers=[];
   if(q.data.participant_id)participant=(await db.from("participants").select("id,access_code,label").eq("id",q.data.participant_id).maybeSingle()).data||null;
   if(q.data.session_id){sessionRow=(await db.from("sessions").select("id,started_at,request_key,pre_state,post_state,helped,research_started").eq("id",q.data.session_id).maybeSingle()).data||null;if(sessionRow){const ev=await db.from("session_events").select("t_ms,event_type,payload").eq("session_id",q.data.session_id).in("event_type",["journey_pattern_open","journey_color","journey_favorite_save","journey_note_create","pattern_open","color_change","favorite_save"]).order("t_ms").limit(2500);if(!ev.error){const base=Date.parse(sessionRow.started_at);markers=(ev.data||[]).map(x=>({observedAt:new Date(base+N(x.t_ms)).toISOString(),type:x.event_type,payload:x.payload||{}}))}}
   if(q.data.guest_archive_id){let ge=db.from("guest_trial_events").select("wall_at,event_type,payload").eq("archive_id",q.data.guest_archive_id).gte("wall_at",q.data.started_at).order("wall_at").limit(2500);if(q.data.ended_at||q.data.last_sample_at)ge=ge.lte("wall_at",q.data.ended_at||q.data.last_sample_at);const gr=await ge;if(!gr.error)markers.push(...(gr.data||[]).map(x=>({observedAt:x.wall_at,type:x.event_type,payload:x.payload||{}}))}
   markers.sort((x,y)=>Date.parse(x.observedAt)-Date.parse(y.observedAt));return J({ok:true,stream:q.data,samples:sr.data||[],participant,session:sessionRow,markers})
 }
 return J({error:"unknown_action"},400)
}catch(e){console.error(e);return J({error:"server_error",detail:String(e?.message||e)},500)}});