// @ts-nocheck
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const URL=Deno.env.get('SUPABASE_URL')!;
const db=createClient(URL,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
const UP=`${URL}/functions/v1/setka-mother-president-v4`;
const H={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store,max-age=0','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-setka-session','Access-Control-Allow-Methods':'POST,OPTIONS','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'};
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H});
const text=(v:any,m=400)=>String(v??'').trim().slice(0,m);
async function sha256(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function president(req:Request,body:any){const tok=text(req.headers.get('x-setka-session')||body.sessionToken,256);if(!tok)return null;const hash=await sha256(tok);const r=await db.rpc('foundation_session_actor_v018',{p_session_hash:hash});if(r.error)return null;const a=r.data;return a?.identityId&&a?.president?{...a,hash}:null}
async function proxy(req:Request,body:any){const h:any={'content-type':'application/json'};const tok=req.headers.get('x-setka-session');if(tok)h['x-setka-session']=tok;const r=await fetch(UP,{method:'POST',headers:h,body:JSON.stringify(body)});const t=await r.text();let d:any;try{d=JSON.parse(t)}catch{return new Response(t,{status:r.status,headers:H})}return json(d,r.status)}
const S=(name:string,title:string)=>({name,title});
const M:any={
FLEET:[S('ship_registry_current_v1','Реестр кораблей'),S('ship_nodes','Узлы кораблей'),S('ship_birth_candidates','Кандидаты на рождение'),S('ship_birth_manifests','Манифесты рождения'),S('ghost_ship_instances','Ghost Fleet'),S('ship_exchange_packets','Обмен между кораблями'),S('ship_autocrane_state','Автокран · состояние'),S('ship_autocrane_decisions','Автокран · решения'),S('fractal_branch_mission_profiles','Профили фрактальных веток'),S('fractal_branch_exchange_events','События обмена веток')],
EXPERIMENTS:[S('ship_pocket_core_experiments','Pocket Core experiments'),S('crown_mission_experiments','Crown experiments'),S('ghost_ship_instances','Ghost Fleet runs'),S('ghost_g2_events','Ghost G2 events'),S('ghost_g2_events_history_v2','Ghost G2 history'),S('ghost_ship_seen_decisions','Ghost decisions'),S('polygon_local_transcript_events','Стенограмма полигонов'),S('entity_candidate_tests','Тесты кандидатов'),S('synthetic_optimization_scenarios','Optimization scenarios'),S('synthetic_field_missions','Полевые миссии')],
WORK:[S('mission_cards','Миссии'),S('atomic_tasks','Атомарные задачи'),S('ai_shift_plan_tasks','План задач ИИ'),S('synthetic_missions','Миссии синтетиков'),S('synthetic_mission_events','События миссий'),S('task_completion_coverage_v020','Покрытие завершения задач'),S('task_completion_evidence_gate_v020','Evidence gate задач'),S('trace_work_events','Рабочие TRACE-события'),S('trace_priority_events','Приоритеты TRACE')],
VERSTAK:[S('verstak_user_projects','Проекты'),S('verstak_project_compartments','Отсеки проектов'),S('verstak_project_identity_bindings','Участники проектов'),S('verstak_project_positions','Должности проектов'),S('verstak_ship_events','События VERSTAK'),S('verstak_ui_pins','UI PIN'),S('verstak_pencil_events','Pencil events'),S('verstak_pin_messages','PIN messages')],
CREW:[S('ship_scoped_crew_current_v1','Экипаж Материнского'),S('ship_position_index','Должности'),S('ship_position_occupancies','Занятость должностей'),S('ship_sector_positions_v1','Позиции по секторам'),S('identity_assignments','Назначения identity'),S('synthetic_duty_current','Текущие обязанности'),S('synthetic_professional_cards','Профессиональные карты'),S('synthetic_current_hierarchy_v1','Иерархия синтетиков'),S('synthetic_career_stats','Карьерная статистика')],
SYNTHETICS:[S('synthetic_neural_runs','Neural runs'),S('synthetic_runtime_sessions','Runtime sessions'),S('synthetic_runtime_admissions','Runtime admissions'),S('synthetic_wake_signals','Wake signals'),S('synthetic_interwake_handoffs','Interwake handoffs'),S('synthetic_interwake_memory_packets','Interwake memory'),S('synthetic_action_tapes','Action tapes'),S('synthetic_runtime_automation_opportunities_v1','Automation opportunities'),S('synthetic_resource_pools','Resource pools'),S('synthetic_resource_snapshot','Resource snapshot'),S('synthetic_ship_movement_current_v1','Текущее перемещение')],
KNOWLEDGE:[S('setka_entity_card_v6','Карточки сущностей'),S('setka_canonical_spine','Канонический позвоночник'),S('setka_entity_graph_edges_v2','Граф сущностей'),S('entity_relation_registry_v2','Реестр отношений'),S('entity_source_links','Источники сущностей'),S('entity_semantic_source_gaps_v1','Semantic source gaps'),S('entity_candidate_incubator_active_v1','Активный инкубатор'),S('entity_taxonomy_current_v1','Таксономия'),S('entity_who_what_where_when_v1','4W представление'),S('knowledge_capability_transition_current_v1','Knowledge → capability')],
CAPABILITIES:[S('capability_command_catalog','Каталог capabilities'),S('capability_command_current_v1','Текущие команды'),S('capability_command_requests','Запросы команд'),S('capability_command_events','События Command Bus'),S('capability_composition_candidates','Composition candidates'),S('capability_gap_report_v1','Capability gaps'),S('capability_portfolio_report_v1','Capability portfolio'),S('capability_promotion_queue_v2','Promotion queue'),S('system_capability_library_v1','System capability library')],
OBSERVATORY:[S('entity_pulse_current_v2','Пульс сущностей'),S('system_time_spine_health_v1','Здоровье временного позвоночника'),S('achievement_signal_events','Достижения'),S('entity_family_velocity_v1','Скорость семейств'),S('entity_family_progress_delta_v1','Дельта прогресса'),S('entity_metabolism_current_v1','Метаболизм сущностей'),S('crown_mission_projection_v1','Crown projection'),S('system_report_federation_health_v1','Федерация отчётов')],
TRANSCRIPT:[S('system_transcript_events','Системная стенограмма'),S('system_reports','Системные отчёты'),S('synthetic_session_reports','Рапорты синтетиков'),S('event_provenance_links','Provenance событий'),S('system_transcript_effective_provenance_v018','Effective provenance'),S('system_transcript_visual_provenance_v018','Visual provenance'),S('project_chat_turns','Project chat turns'),S('control_events','Control events')],
MEMORY:[S('memory_layer_registry','Слои памяти'),S('memory_layer_summary_v1','Сводка слоёв'),S('memory_physiology_current_v2','Физиология памяти'),S('memory_retention_registry_v1','Retention registry'),S('memory_compaction_capsules_v1','Compaction capsules'),S('ephemeral_memory_archive_manifests_v1','Archive manifests'),S('ephemeral_memory_archive_rows_v1','Archive rows'),S('short_term_memory_entries','Short-term memory'),S('synthetic_memory_capsules','Память синтетиков'),S('synthetic_self_capsules','Self capsules')],
SECURITY:[S('canon_guard_events','Canon guards'),S('architecture_admissions','Architecture admissions'),S('identity_authority_current_v1','Authority'),S('session_hash_admission_health_v1','Session admission health'),S('runtime_admission_class_audit_v1','Runtime admission audit'),S('entity_integrity_health_v1','Entity integrity'),S('synthetic_trusted_gateway_coverage_v1','Trusted gateway coverage'),S('entity_source_coverage_v1','Source coverage'),S('setka_entity_integration_health_v1','Entity integration health')],
STORAGE:[S('ship_storage_containers','Контейнеры кораблей'),S('entity_candidate_incubator_cold_archive_v1','Cold archive'),S('ship_local_transcript_archive_manifests_v2','Local transcript manifests'),S('ship_local_transcript_archive_events_v2','Local transcript archive events'),S('ship_local_transcript_distillates_v2','Transcript distillates'),S('memory_archive_proof_events_v2','Memory archive proofs'),S('prototype_v34_lossless_archive_state_events_v2','Prototype archive states')],
COMMUNICATION:[S('ship_computer_dialogue_turns','Диалоги бортового компьютера'),S('ship_computer_event_interactions','Event interactions'),S('ship_computer_event_receipts','Event receipts'),S('ship_contact_routes','Маршруты связи'),S('ship_exchange_packets','Ship exchange packets'),S('pin_messages','PIN messages'),S('ship_local_pin_messages','Ship local PIN messages'),S('synthetic_contact_tree_history','Contact tree history')],
GOVERNANCE:[S('president_session_mode_events','Режимы Президента'),S('president_report_policy','Политика рапортов'),S('identity_authority_current_v1','Authority'),S('authority_command_edges','Цепочки полномочий'),S('entity_review_stamps','Review stamps'),S('architecture_admissions','Architecture admissions'),S('senior_inspection_seal_events','Senior inspection seals'),S('control_events','Control events')],
ATLAS:[S('front_backend_catalog_v1','Полный backend-каталог')]
};
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return json({error:'method_not_allowed'},405);try{const body=await req.json().catch(()=>({}));const action=text(body.action,80);if(action!=='module')return proxy(req,body);const a=await president(req,body);if(!a)return json({error:'invalid_president_session'},401);const key=text(body.key,40).toUpperCase();const defs=M[key];if(!defs)return json({error:'unknown_module'},404);const limit=Math.max(1,Math.min(50,Number(body.limit)||18));const r=await db.rpc('setka_president_front_module_preview_v1',{p_relations:defs.map((x:any)=>x.name),p_limit:limit});if(r.error)throw r.error;const raw=r.data||{};const sources:any={};const unavailable:any[]=[];for(const def of defs){const p=raw[def.name];if(p?.ok&&Array.isArray(p.rows)){sources[def.name]={title:def.title,count:null,rows:p.rows}}else unavailable.push({name:def.name,title:def.title,error:p?.error||'source_unavailable'})}return json({ok:true,module:{key},sources,unavailable,sourceCount:Object.keys(sources).length});}catch(e){console.error('setka-mother-president-v5',e);return json({error:'server_error',detail:String(e?.message||e)},500)}});