// @ts-nocheck
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8"};
const J=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H});
const T=(v,m=500)=>String(v??"").trim().slice(0,m);const N=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;const C=(v,a,b)=>Math.min(b,Math.max(a,v));
async function sha(v){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("")}
async function session(id,token){if(!id||!token)return null;const h=await sha(token);const q=await db.from("sessions").select("id,participant_id,request_key,pre_state,post_state,completed,planned_duration_seconds,timer_started_at,timer_deadline_at,feedback_prompted_at,feedback_submitted_at,continued_after_feedback").eq("id",id).eq("session_token_hash",h).maybeSingle();return q.data||null}
async function admin(key){if(!key)return false;const h=await sha(key.trim());const q=await db.from("admin_keys").select("id").eq("key_hash",h).eq("active",true).maybeSingle();return !!q.data}
function canon(v){if(Array.isArray(v))return v.map(canon);if(v&&typeof v==="object")return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])]));if(typeof v==="number")return Math.round(v*100000)/100000;return v}
async function cfgHash(patternId,version,config){return sha(`${patternId}|${version}|${JSON.stringify(canon(config||{}))}`)}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return J({error:"method_not_allowed"},405);try{const b=await req.json();const a=T(b?.action,80);
if(a==="timing-start"){const s=await session(T(b.sessionId,80),T(b.sessionToken,200));if(!s)return J({error:"invalid_session"},403);const started=b.startedAt?new Date(b.startedAt):new Date();const sec=C(Math.round(N(b.plannedDurationSeconds,600)),60,7200);const deadline=b.deadlineAt?new Date(b.deadlineAt):new Date(started.getTime()+sec*1000);const q=await db.from("sessions").update({research_started:true,planned_duration_seconds:sec,timer_started_at:started.toISOString(),timer_deadline_at:deadline.toISOString(),local_started_at:started.toISOString(),completion_reason:null,measured_active_ms:0,after_feedback_active_ms:0,continued_after_feedback:false}).eq("id",s.id);if(q.error)throw q.error;return J({ok:true,deadlineAt:deadline.toISOString()})}
if(a==="feedback-prompt"){const s=await session(T(b.sessionId,80),T(b.sessionToken,200));if(!s)return J({error:"invalid_session"},403);const at=b.at?new Date(b.at):new Date();const q=await db.from("sessions").update({feedback_prompted_at:at.toISOString(),completion_reason:T(b.reason,40)||"timer"}).eq("id",s.id);if(q.error)throw q.error;return J({ok:true})}
if(a==="feedback-submit"){const s=await session(T(b.sessionId,80),T(b.sessionToken,200));if(!s)return J({error:"invalid_session"},403);const at=b.at?new Date(b.at):new Date();let prompt=s.feedback_prompted_at?new Date(s.feedback_prompted_at):at;const delay=Math.max(0,at.getTime()-prompt.getTime());const q=await db.from("sessions").update({feedback_submitted_at:at.toISOString(),feedback_delay_ms:delay,measured_active_ms:Math.max(0,Math.round(N(b.measuredActiveMs,0)))}).eq("id",s.id);if(q.error)throw q.error;return J({ok:true,feedbackDelayMs:delay})}
if(a==="continuation-start"){const s=await session(T(b.sessionId,80),T(b.sessionToken,200));if(!s)return J({error:"invalid_session"},403);const at=b.at?new Date(b.at):new Date();const q=await db.from("sessions").update({continued_after_feedback:true,continuation_started_at:at.toISOString()}).eq("id",s.id);if(q.error)throw q.error;return J({ok:true})}
if(a==="continuation-end"){const s=await session(T(b.sessionId,80),T(b.sessionToken,200));if(!s)return J({error:"invalid_session"},403);const at=b.at?new Date(b.at):new Date();const q=await db.from("sessions").update({continuation_ended_at:at.toISOString(),after_feedback_active_ms:Math.max(0,Math.round(N(b.afterFeedbackActiveMs,0)))}).eq("id",s.id);if(q.error)throw q.error;return J({ok:true})}
if(a==="post-usage"){const s=await session(T(b.sessionId,80),T(b.sessionToken,200));if(!s)return J({error:"invalid_session"},403);const list=Array.isArray(b.items)?b.items.slice(0,100):[];if(list.length){const rows=list.map(u=>({session_id:s.id,participant_id:s.participant_id,pattern_id:T(u.patternId,100)||"tentacle-orbit",community_config_id:u.communityConfigId||null,config_hash:T(u.configHash,128)||null,started_ms:Math.max(0,Math.round(N(u.startedMs))),ended_ms:Math.max(0,Math.round(N(u.endedMs))),duration_ms:Math.max(0,Math.round(N(u.durationMs))),saved:!!u.saved}));const q=await db.from("session_post_usage").insert(rows);if(q.error)throw q.error}return J({ok:true})}
if(a==="note-create"){const s=await session(T(b.sessionId,80),T(b.sessionToken,200));if(!s)return J({error:"invalid_session"},403);const text=T(b.text,5000);if(!text)return J({error:"empty_note"},400);const state=b.state&&typeof b.state==="object"?b.state:{};const patternId=T(state.patternId||b.patternId,100)||null;const version=Math.max(1,Math.round(N(state.patternVersion||b.patternVersion,1)));const config=canon(state.config||b.config||{});const hash=patternId?await cfgHash(patternId,version,config):null;const phase=["measured","after_feedback","standalone"].includes(String(b.phase))?String(b.phase):"measured";const at=b.observedAt?new Date(b.observedAt):new Date();const row={participant_id:s.participant_id,session_id:s.id,note_text:text,phase,observed_at:at.toISOString(),local_offset_minutes:Number.isFinite(Number(b.localOffsetMinutes))?Math.round(Number(b.localOffsetMinutes)):null,session_elapsed_ms:Math.max(0,Math.round(N(b.sessionElapsedMs))),request_key:T(b.requestKey||s.request_key,60)||null,pattern_id:patternId,pattern_version:version,source_type:T(state.sourceType||b.sourceType,60)||null,source_id:T(state.sourceId||b.sourceId,120)||null,community_config_id:state.communityId||b.communityConfigId||null,config_hash:hash,config,preview_frame:Number.isFinite(Number(state.frame??b.previewFrame))?Number(state.frame??b.previewFrame):null};const q=await db.from("participant_notes").insert(row).select("*").single();if(q.error)throw q.error;return J({ok:true,item:q.data})}
if(a==="note-list"){const s=await session(T(b.sessionId,80),T(b.sessionToken,200));if(!s)return J({error:"invalid_session"},403);const q=await db.from("participant_notes").select("id,session_id,note_text,phase,observed_at,local_offset_minutes,session_elapsed_ms,request_key,pattern_id,pattern_version,source_type,source_id,community_config_id,config_hash,config,preview_frame").eq("participant_id",s.participant_id).order("observed_at",{ascending:false}).limit(C(Math.round(N(b.limit,300)),1,1000));if(q.error)throw q.error;return J({ok:true,items:q.data||[]})}
if(a==="self-summary"){const s=await session(T(b.sessionId,80),T(b.sessionToken,200));if(!s)return J({error:"invalid_session"},403);const [sq,nq,iq,syq]=await Promise.all([db.from("sessions").select("id,started_at,request_key,pre_state,post_state,planned_duration_seconds,measured_active_ms,after_feedback_active_ms,continued_after_feedback,completed").eq("participant_id",s.participant_id).eq("research_started",true).order("started_at",{ascending:false}).limit(50),db.from("participant_notes").select("id",{count:"exact",head:true}).eq("participant_id",s.participant_id),db.from("participants").select("id",{count:"exact",head:true}).eq("invited_by",s.participant_id),db.from("participant_symptoms").select("id",{count:"exact",head:true}).eq("participant_id",s.participant_id).eq("active",true)]);return J({ok:true,summary:{sessions:sq.data||[],noteCount:nq.count||0,inviteCount:iq.count||0,symptomCount:syq.count||0}})}
if(a.startsWith("admin-")){if(!(await admin(T(b.adminKey,300))))return J({error:"invalid_admin_key"},403);
 if(a==="admin-notes"){const q=await db.from("participant_notes").select("id,participant_id,session_id,note_text,phase,observed_at,session_elapsed_ms,request_key,pattern_id,pattern_version,source_type,source_id,community_config_id,config,preview_frame,participants(access_code,label)").order("observed_at",{ascending:false}).limit(2000);if(q.error)throw q.error;return J({ok:true,items:q.data||[]})}
 if(a==="admin-session-timing"){const q=await db.from("sessions").select("id,participant_id,started_at,ended_at,request_key,pre_state,post_state,helped,completed,planned_duration_seconds,timer_started_at,timer_deadline_at,feedback_prompted_at,feedback_submitted_at,feedback_delay_ms,measured_active_ms,continued_after_feedback,continuation_started_at,continuation_ended_at,after_feedback_active_ms,completion_reason,participants(access_code,label)").eq("research_started",true).order("started_at",{ascending:false}).limit(2000);if(q.error)throw q.error;return J({ok:true,items:q.data||[]})}
 if(a==="admin-session-notes"){const q=await db.from("participant_notes").select("*").eq("session_id",T(b.sessionId,80)).order("observed_at");if(q.error)throw q.error;return J({ok:true,items:q.data||[]})}
}
return J({error:"unknown_action"},400)}catch(e){console.error(e);return J({error:"server_error",detail:String(e?.message||e)},500)}});