// @ts-nocheck
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
const CHANNEL="yulia_lab_v34";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8"};
const J=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H});
const T=(v,m=500)=>String(v??"").trim().slice(0,m),N=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,O=v=>v&&typeof v==="object"&&!Array.isArray(v)?v:{},A=v=>Array.isArray(v)?v:[];
const TD={patternId:"tentacle-orbit",numTentacles:24,tentacleLength:100,baseRadius:10,movementSpeed:1,colorSpeed:1,circleSize:1,lineWeight:1,segmentStep:2,colorModeIndex:0};
const DD={patternId:"dandelion",v1:.473,numShapes:380,angleSpeed:.01,tSpeed:.005,backgroundAlpha:255,lineWeight:1.2,pointSize:4,zoom:1,colorModeIndex:0};
const r5=v=>Math.round(N(v)*1e5)/1e5;
function canonical(patternId,key,raw={}){key=T(key,300);raw=O(raw);let pid=T(patternId,80)||T(raw.patternId,80)||null,parts=key?key.split("|"):[];if(parts[0]==="dandelion")pid="dandelion";else if(parts[0]==="tentacle-orbit")pid="tentacle-orbit";else if(!pid&&parts.length===9)pid="tentacle-orbit";if(!pid&&("v1" in raw||"numShapes" in raw))pid="dandelion";if(pid==="dandelion"){const p=parts[0]==="dandelion"?parts.slice(1):[],c={...DD,...raw,patternId:"dandelion"};if(p.length>=9){c.v1=N(p[0],c.v1);c.numShapes=Math.round(N(p[1],c.numShapes));c.angleSpeed=N(p[2],c.angleSpeed);c.tSpeed=N(p[3],c.tSpeed);c.backgroundAlpha=Math.round(N(p[4],c.backgroundAlpha));c.lineWeight=N(p[5],c.lineWeight);c.pointSize=N(p[6],c.pointSize);c.zoom=N(p[7],c.zoom);c.colorModeIndex=Math.round(N(p[8],c.colorModeIndex))}return{patternId:"dandelion",configKey:["dandelion",r5(c.v1),c.numShapes,r5(c.angleSpeed),r5(c.tSpeed),c.backgroundAlpha,r5(c.lineWeight),r5(c.pointSize),r5(c.zoom),c.colorModeIndex].join("|"),config:c}}
 const p=parts[0]==="tentacle-orbit"?parts.slice(1):(parts.length===9?parts:[]),c={...TD,...raw,patternId:"tentacle-orbit"};if(p.length>=9){c.numTentacles=Math.round(N(p[0],c.numTentacles));c.tentacleLength=N(p[1],c.tentacleLength);c.baseRadius=N(p[2],c.baseRadius);c.movementSpeed=N(p[3],c.movementSpeed);c.colorSpeed=N(p[4],c.colorSpeed);c.circleSize=N(p[5],c.circleSize);c.lineWeight=N(p[6],c.lineWeight);c.segmentStep=Math.round(N(p[7],c.segmentStep));c.colorModeIndex=Math.round(N(p[8],c.colorModeIndex))}return{patternId:"tentacle-orbit",configKey:["tentacle-orbit",c.numTentacles,r5(c.tentacleLength),r5(c.baseRadius),r5(c.movementSpeed),r5(c.colorSpeed),r5(c.circleSize),r5(c.lineWeight),c.segmentStep,c.colorModeIndex].join("|"),config:c}}
async function replaceFavorites(deviceId,list){const rows=[];for(const f of A(list).slice(0,300)){const c=canonical(f.patternId||f.baseId,f.configKey,f.config),saved=f.savedAt||f.createdAt||Date.now();rows.push({device_id:deviceId,config_key:c.configKey,pattern_id:c.patternId,config:c.config,favorite_id:T(f.id,180)||null,saved_at:new Date(Number.isFinite(Number(saved))?Number(saved):saved).toISOString(),source_type:T(f.sourceType||"favorite",60)||"favorite",updated_at:new Date().toISOString()})}const del=await db.from("prototype_v35_favorites").delete().eq("device_id",deviceId);if(del.error)throw del.error;if(rows.length){const q=await db.from("prototype_v35_favorites").upsert(rows,{onConflict:"device_id,config_key"});if(q.error)throw q.error}return rows.length}
async function upsertExposures(deviceId,list){const rows=[];for(const x0 of A(list).slice(0,1500)){const x=O(x0),c=canonical(x.patternId,x.configKey,x.config),st=new Date(x.startedAt||Date.now()),en=new Date(x.endedAt||x.startedAt||Date.now());if(!T(x.exposureId,180)||!c.configKey||Number.isNaN(st.getTime())||Number.isNaN(en.getTime()))continue;rows.push({exposure_id:T(x.exposureId,180),device_id:deviceId,visit_id:T(x.visitId,180)||null,session_id:T(x.sessionId,180)||null,session_type:T(x.sessionType,40)||null,context:["free","measured","after_feedback","exploration"].includes(T(x.context,40))?T(x.context,40):"free",request_key:T(x.requestKey,80)||null,pattern_id:c.patternId,config_key:c.configKey,config:c.config,source_type:T(x.sourceType,80)||null,source_id:T(x.sourceId,180)||null,community_id:T(x.communityId,180)||null,started_at:st.toISOString(),ended_at:en.toISOString(),duration_ms:Math.max(0,Math.round(N(x.durationMs,en.getTime()-st.getTime()))),entry_reason:T(x.entryReason,80)||null,legacy_source:null,updated_at:new Date().toISOString()})}for(let i=0;i<rows.length;i+=400){const q=await db.from("prototype_v35_pattern_exposures").upsert(rows.slice(i,i+400),{onConflict:"exposure_id"});if(q.error)throw q.error}return rows.length}
async function upsertVisit(deviceId,v){v=O(v);const id=T(v.id,180);if(!id)return;const now=new Date(),start=new Date(v.startedAt||now),last=new Date(v.lastSeenAt||now);const row={visit_id:id,device_id:deviceId,started_at:Number.isNaN(start.getTime())?now.toISOString():start.toISOString(),last_seen_at:Number.isNaN(last.getTime())?now.toISOString():last.toISOString(),ended_at:v.endedAt?new Date(v.endedAt).toISOString():null,updated_at:now.toISOString()};const q=await db.from("prototype_v35_visits").upsert(row,{onConflict:"visit_id"});if(q.error)throw q.error}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return J({error:"method_not_allowed"},405);try{const b=await req.json();if(T(b.action,40)!=="sync"||T(b.channel,80)!==CHANNEL)return J({error:"forbidden"},403);const deviceId=T(b.deviceId,180);if(!deviceId)return J({error:"missing_device"},400);const favorites=await replaceFavorites(deviceId,b.favorites),acceptedExposures=await upsertExposures(deviceId,b.exposuresDelta);await upsertVisit(deviceId,b.visit);const idx=await db.from("prototype_v34_sessions").update({session_type:"exploration"}).eq("device_id",deviceId).eq("request_key","explore").is("session_type",null);if(idx.error)throw idx.error;const idx2=await db.from("prototype_v34_sessions").update({session_type:"outcome"}).eq("device_id",deviceId).neq("request_key","explore").is("session_type",null);if(idx2.error)throw idx2.error;const r=await db.rpc("prototype_v35_rebuild_device_facts",{p_device_id:deviceId});if(r.error)throw r.error;return J({ok:true,favorites,acceptedExposures,facts:true})}catch(e){console.error(e);return J({error:"server_error",detail:String(e?.message||e)},500)}});
