// @ts-nocheck
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8"};
const J=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H});const T=(v,m=400)=>String(v??"").trim().slice(0,m),N=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,O=v=>v&&typeof v==="object"&&!Array.isArray(v)?v:{};
async function sha(v){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function auth(k){if(!k)return false;const q=await db.from("admin_keys").select("id").eq("key_hash",await sha(T(k,300))).eq("active",true).maybeSingle();return!!q.data}
function add(m,k,init){if(!m.has(k))m.set(k,init());return m.get(k)}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return J({error:"method_not_allowed"},405);try{const b=await req.json();if(!(await auth(b.adminKey)))return J({error:"invalid_admin_key"},403);const action=T(b.action,60);
 if(action==="admin-all-configs"){const q=await db.from("prototype_v35_config_facts").select("pattern_id,config_key,config,total_ms,measured_ms,after_feedback_ms,exploration_ms,max_continuous_ms,segments,session_count,outcome_session_count,outcome_delta_sum,favorite_current,note_count");if(q.error)throw q.error;const m=new Map();for(const r of q.data||[]){const x=add(m,r.config_key,()=>({patternId:r.pattern_id,configKey:r.config_key,config:r.config,participants:0,totalMs:0,measuredMs:0,afterFeedbackMs:0,explorationMs:0,maxContinuousMs:0,segments:0,sessions:0,outcomeSessions:0,deltaSum:0,favoriteParticipants:0,notes:0}));x.participants++;x.totalMs+=N(r.total_ms);x.measuredMs+=N(r.measured_ms);x.afterFeedbackMs+=N(r.after_feedback_ms);x.explorationMs+=N(r.exploration_ms);x.maxContinuousMs=Math.max(x.maxContinuousMs,N(r.max_continuous_ms));x.segments+=N(r.segments);x.sessions+=N(r.session_count);x.outcomeSessions+=N(r.outcome_session_count);x.deltaSum+=N(r.outcome_delta_sum);if(r.favorite_current)x.favoriteParticipants++;x.notes+=N(r.note_count)}return J({ok:true,items:[...m.values()].sort((a,b)=>b.totalMs-a.totalMs).slice(0,500)})}
 if(action==="admin-community"){const q=await db.from("prototype_v35_favorites").select("device_id,pattern_id,config_key,config,saved_at");if(q.error)throw q.error;const m=new Map();for(const r of q.data||[]){const x=add(m,r.config_key,()=>({patternId:r.pattern_id,configKey:r.config_key,config:r.config,saveCount:0,participants:new Set(),firstSavedAt:r.saved_at,lastSavedAt:r.saved_at}));x.saveCount++;x.participants.add(r.device_id);if(Date.parse(r.saved_at||0)<Date.parse(x.firstSavedAt||0))x.firstSavedAt=r.saved_at;if(Date.parse(r.saved_at||0)>Date.parse(x.lastSavedAt||0))x.lastSavedAt=r.saved_at}return J({ok:true,items:[...m.values()].map(x=>({...x,participants:x.participants.size})).sort((a,b)=>b.saveCount-a.saveCount||Date.parse(b.lastSavedAt)-Date.parse(a.lastSavedAt))})}
 return J({error:"unknown_action"},400)}catch(e){console.error(e);return J({error:"server_error",detail:String(e?.message||e)},500)}});
