(()=>{
'use strict';
const API='https://gfchgaphzhxufwdhrcis.supabase.co/functions/v1/setka-mother-president-v3';
const AUTH='https://gfchgaphzhxufwdhrcis.supabase.co/functions/v1/setka-foundation-v018';
const CONTROL='https://gfchgaphzhxufwdhrcis.supabase.co/functions/v1/setka-foundation-control';
const SESSION_KEY='setka:foundation:president:session';
const FRONT_VERSION='MOTHER-PRESIDENT-V2';
const $=id=>document.getElementById(id);
const state={boot:null,module:null,moduleData:null,current:'HOME',pins:[],pinFilter:'active',mailTab:'events',pinMode:false,pinHover:null};
const trace={recording:false,code:'',segment:'',seq:0,events:[],started:0,lastMove:0,lastScroll:0};
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const token=()=>{try{return localStorage.getItem(SESSION_KEY)||''}catch{return''}};
const setToken=v=>{try{if(v)localStorage.setItem(SESSION_KEY,v);else localStorage.removeItem(SESSION_KEY)}catch{}};
function toast(msg){const t=$('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2600)}
async function post(url,action,payload={},auth=true){const h={'content-type':'application/json'};if(auth&&token())h['x-setka-session']=token();const r=await fetch(url,{method:'POST',headers:h,body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({}));if(r.status===401&&auth){showLogin();throw new Error('Нужна Президентская сессия')}if(!r.ok)throw new Error(d.detail||d.error||'Ошибка запроса');return d}
const api=(a,p={})=>post(API,a,p,true);
const control=(a,p={})=>post(CONTROL,a,p,true);
function workingVersion(){return state.boot?.manifest?.pointers?.working||state.boot?.manifest?.working||'3.0.0'}
function bestText(x){if(x==null)return'—';if(typeof x==='string'||typeof x==='number'||typeof x==='boolean')return String(x);if(Array.isArray(x))return x.length?bestText(x[0]):'—';for(const k of ['display_name_ru','title_ru','title','summary_ru','summary','name','ship_code','mission_ref','mission_code','experiment_code','experiment_ref','candidate_code','report_ref','pin_code','setka_id','identity_ref','local_identity_ref','position_ref','event_type','eventType','command_code','commandCode','entity_ref','source_ref'])if(x?.[k]!=null&&x[k]!=='')return String(x[k]);const p=Object.entries(x||{}).find(([,v])=>['string','number','boolean'].includes(typeof v));return p?`${p[0]}: ${p[1]}`:'Запись'}
function metaText(x){if(!x||typeof x!=='object')return'';const bits=[];for(const k of ['state','status','stage','kind','event_type','scope_ref','source_ref','created_at','updated_at','occurred_at','generated_at','prepared_at','admitted_at'])if(x[k]!=null&&x[k]!==''&&bits.length<3)bits.push(`${k}: ${typeof x[k]==='object'?JSON.stringify(x[k]):x[k]}`);return bits.join(' · ')}
function moduleBy(k){return (state.boot?.modules||[]).find(m=>m.key===k)}
function setView(v){state.current=v;$('homeView').classList.toggle('active',v==='HOME');$('moduleView').classList.toggle('active',v!=='HOME');document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===v))}
function renderHeader(){const b=state.boot,ship=b?.ship;const w=workingVersion();$('workingVersion').textContent=`${w} · WORKING`;$('frontVersion').textContent=FRONT_VERSION;$('shipStatus').textContent=ship?.state==='active'?'Корабль активен':(ship?.state||'—');$('pinBadge').textContent=String(state.pins.filter(p=>!['resolved','rejected','deleted'].includes(String(p.status||'').toLowerCase())).length);$('pinBadge').style.display=state.pins.length?'inline-flex':'none'}
function renderRail(){const rail=$('rail');const primary=['HOME','FLEET','EXPERIMENTS','WORK','VERSTAK','CREW','KNOWLEDGE','OBSERVATORY'];const icons={HOME:'⌂'};rail.innerHTML='';for(const key of primary){const m=key==='HOME'?{key:'HOME',icon:'⌂',title:'Корабль'}:moduleBy(key);if(!m)continue;const b=document.createElement('button');b.dataset.nav=key;b.innerHTML=`<span>${m.icon||icons[key]||'◈'}</span><em>${esc(m.title)}</em>`;b.onclick=()=>key==='HOME'?goHome():openModule(key);rail.appendChild(b)}setView(state.current)}
function stat(label,val){return `<div class="stat"><strong>${esc(val??0)}</strong><span>${esc(label)}</span></div>`}
function renderDashboard(){const b=state.boot;if(!b)return;const ship=b.ship||{};$('shipTitle').textContent=ship.display_name_ru||'Материнский корабль SETKA';$('shipMeta').textContent=`${ship.ship_code||'SHIP-SETKA-MOTHER'} · владелец ${ship.owner_identity_ref||'SETKA-0001-0001'}`;$('heroState').innerHTML=`<i></i>${esc(ship.state||'active')} · live backend`;
 $('stats').innerHTML=stat('модулей',b.stats?.modules)+stat('кораблей во флоте',b.stats?.fleet)+stat('экипаж',b.stats?.crew)+stat('pocket-core экспериментов',b.stats?.experiments)+stat('PIN',state.pins.length);
 const majors=['FLEET','EXPERIMENTS','WORK','VERSTAK'];$('majorGrid').innerHTML=majors.map(k=>{const m=moduleBy(k);return m?`<button class="majorCard" data-open="${m.key}" data-pin="module:${m.key}"><div class="icon">${m.icon}</div><h3>${esc(m.title)}</h3><p>${esc(m.subtitle)}</p><div class="countLine"><span><b>${m.recordCount??0}</b> записей</span><span>${m.totalSources||0} источников</span></div></button>`:''}).join('');
 $('moduleGrid').innerHTML=(b.modules||[]).filter(m=>!majors.includes(m.key)).map(m=>`<button class="moduleCard" data-open="${m.key}" data-pin="module:${m.key}"><div class="icon">${m.icon}</div><h3>${esc(m.title)}</h3><p>${esc(m.subtitle)}</p><div class="countLine"><span><b>${m.recordCount??0}</b> записей</span><span>${m.totalSources||0} источников</span></div></button>`).join('');
 const sectors=(b.sectors||[]).filter(s=>s.sector_ref!=='SHIP/SETKA');$('sectorGrid').innerHTML=sectors.map(s=>`<button class="sectorCard" data-pin="sector:${esc(s.sector_ref)}"><div class="icon">${sectorIcon(s)}</div><h3>${esc(s.display_name_ru||s.sector_ref)}</h3><p>${esc(s.canonical_state?.purpose||s.sector_kind||'')}</p><div class="countLine"><span>${esc(s.state||'')}</span></div></button>`).join('')||'<div class="empty">Отсеки не загрузились.</div>';
 renderEvents();renderQuick();bindDashboardButtons();
}
function sectorIcon(s){const k=String(s.sector_ref||s.sector_kind||'').toUpperCase();if(k.includes('BRIDGE'))return'🧭';if(k.includes('VERSTAK'))return'🛠';if(k.includes('CREW'))return'👥';if(k.includes('KNOWLEDGE'))return'🧬';if(k.includes('ENGINE'))return'⚙️';if(k.includes('SECURITY'))return'🛡';if(k.includes('OBSERV'))return'📡';if(k.includes('POLYGON'))return'🧪';if(k.includes('HOLD'))return'📦';return'◈'}
function bindDashboardButtons(){document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openModule(b.dataset.open))}
function renderEvents(){const box=$('eventPreview'),arr=state.boot?.eventInbox||[];box.innerHTML=arr.slice(0,8).map(x=>`<div class="feedItem" data-pin="event:${esc(x.event_key||x.event_no||'')}"><strong>${esc(x.summary||bestText(x))}</strong><span>${esc([x.event_category,x.state,x.occurred_at].filter(Boolean).join(' · '))}</span></div>`).join('')||'<div class="empty">Событий для показа нет.</div>'}
function renderQuick(){const box=$('quickHome'),arr=state.boot?.quickActions||[];box.innerHTML=arr.slice(0,8).map((x,i)=>`<button data-quick="${i}">${esc(x.label||x.title||x.prompt||x.commandCode||'Действие')}</button>`).join('')||'<div class="empty">Нет быстрых действий.</div>';box.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>runQuick(arr[Number(b.dataset.quick)]))}
async function runQuick(x){const prompt=x?.prompt||x?.label||x?.title||x?.commandCode||x?.command_code;if(!prompt)return;openComputer();await sendComputer(prompt)}
function goHome(){state.module=null;state.moduleData=null;setView('HOME');renderDashboard()}
async function openModule(key){const m=moduleBy(key);if(!m)return;state.module=m;setView(key);$('moduleIcon').textContent=m.icon;$('moduleTitle').textContent=m.title;$('moduleSubtitle').textContent=m.subtitle;$('moduleMeta').textContent=`${m.totalSources||m.sources?.length||0} backend-источников · live`;$('moduleSearch').value='';$('sourceGrid').innerHTML='<div class="empty">Загружаю живые данные модуля…</div>';try{const d=await api('module',{key,limit:80});state.moduleData=d;renderModuleSources()}catch(e){$('sourceGrid').innerHTML=`<div class="sourceError">${esc(e.message)}</div>`}}
function renderModuleSources(){const d=state.moduleData;if(!d)return;const q=$('moduleSearch').value.trim().toLowerCase();const entries=Object.entries(d.sources||{});let shown=0;const html=[];for(const [name,src] of entries){const rows=Array.isArray(src.rows)?src.rows:[];const sourceMatch=`${src.title} ${name}`.toLowerCase().includes(q);const filtered=q&&!sourceMatch?rows.filter(r=>`${bestText(r)} ${metaText(r)} ${JSON.stringify(r)}`.toLowerCase().includes(q)):rows;if(q&&!sourceMatch&&!filtered.length)continue;shown++;if(src.rows?.__error||src.rows?.__source){html.push(`<div class="sourceGroup"><div class="sourceError">${esc(src.title)} · ${esc(src.rows.__error||'Ошибка источника')}</div></div>`);continue}html.push(`<details class="sourceGroup" ${entries.length<5?'open':''} data-pin="source:${esc(name)}"><summary><strong>${esc(src.title||name)}</strong><span>${src.count==null?'?':src.count} записей · ${esc(name)}</span></summary><div class="rows">${filtered.length?filtered.slice(0,80).map(r=>rowHtml(r,name)).join(''):'<div class="row"><div class="empty">Нет записей.</div></div>'}</div></details>`)}$('sourceGrid').innerHTML=shown?html.join(''):'<div class="empty">Ничего не найдено.</div>'}
function rowHtml(r,source){return `<details class="row" data-pin="row:${esc(source)}:${esc(bestText(r).slice(0,80))}"><summary><span class="rowTitle">${esc(bestText(r))}</span><span class="rowMeta">${esc(metaText(r))}</span></summary><pre>${esc(JSON.stringify(r,null,2))}</pre></details>`}
function openComputer(){$('computerPanel').classList.add('open');$('computerPanel').setAttribute('aria-hidden','false')}
function closeComputer(){$('computerPanel').classList.remove('open');$('computerPanel').setAttribute('aria-hidden','true')}
function appendChat(kind,text){const d=document.createElement('div');d.className=`bubble ${kind}`;d.textContent=text;$('chatLog').appendChild(d);$('chatLog').scrollTop=$('chatLog').scrollHeight}
function computerText(r){const x=r?.result??r;if(typeof x==='string')return x;if(x?.response)return x.response;if(x?.answer)return x.answer;if(x?.message)return x.message;return bestText(x)}
async function sendComputer(msg){msg=String(msg||'').trim();if(!msg)return;appendChat('user',msg);$('computerInput').value='';try{const d=await api('computer_chat',{message:msg});appendChat('computer',computerText(d));}catch(e){appendChat('computer','Ошибка: '+e.message)}}
function statusClass(s){s=String(s||'').toLowerCase();if(['open','new','proposed'].includes(s))return'red';if(['in_progress','working','ready_for_review'].includes(s))return'yellow';if(['done','resolved','accepted','closed'].includes(s))return'green';return'grey'}
function filterPins(){if(state.pinFilter==='all')return state.pins;if(state.pinFilter==='active')return state.pins.filter(p=>!['resolved','rejected','deleted','accepted','closed'].includes(String(p.status||'').toLowerCase()));return state.pins.filter(p=>String(p.status||'').toLowerCase()===state.pinFilter)}
function openDrawer(kind){$('drawer').classList.add('open');$('drawer').setAttribute('aria-hidden','false');if(kind==='pins'){state.mailTab='pins';$('drawerTitle').textContent='Пины';$('drawerKicker').textContent='PRESIDENT PIN SYSTEM'}else{state.mailTab='events';$('drawerTitle').textContent='Почта / Связь';$('drawerKicker').textContent='EVENT HUB + PIN MAIL'}renderDrawer()}
function closeDrawer(){$('drawer').classList.remove('open');$('drawer').setAttribute('aria-hidden','true')}
function renderDrawer(){const body=$('drawerBody');body.innerHTML=`<div class="drawerTabs"><button data-tab="events">События</button><button data-tab="pins">Пины</button></div><div id="drawerContent"></div>`;body.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===state.mailTab);b.onclick=()=>{state.mailTab=b.dataset.tab;renderDrawer()}});if(state.mailTab==='events')renderEventDrawer();else renderPinDrawer()}
function renderEventDrawer(){const c=$('drawerContent'),arr=state.boot?.eventInbox||[];c.innerHTML=arr.map((x,i)=>`<div class="pinItem" data-event-index="${i}"><div><span class="dot ${x.state==='UNREAD'?'red':'grey'}"></span><strong>${esc(x.summary||bestText(x))}</strong></div><p>${esc([x.event_category,x.state,x.occurred_at].filter(Boolean).join(' · '))}</p></div>`).join('')||'<div class="empty">Нет событий.</div>';c.querySelectorAll('[data-event-index]').forEach(el=>el.onclick=()=>openEvent(arr[Number(el.dataset.eventIndex)]))}
function renderPinDrawer(){const c=$('drawerContent');c.innerHTML=`<div class="drawerTabs"><button data-pf="all">Все</button><button data-pf="active">Активные</button><button data-pf="open">Новые</button><button data-pf="in_progress">В работе</button><button data-pf="done">Готово</button><button data-pf="resolved">Принято</button></div><div class="pinList"></div>`;c.querySelectorAll('[data-pf]').forEach(b=>{b.classList.toggle('active',b.dataset.pf===state.pinFilter);b.onclick=()=>{state.pinFilter=b.dataset.pf;renderPinDrawer()}});const list=c.querySelector('.pinList'),arr=filterPins();list.innerHTML=arr.map((p,i)=>`<div class="pinItem" data-pin-index="${i}"><div><span class="dot ${statusClass(p.status)}"></span><strong>${esc(p.pin_code||'PIN')}</strong></div><p>${esc(p.comment||p.target_label||p.page_key||'')}</p><span class="rowMeta">${esc(p.status||'')} · ${esc(p.version||'')}</span></div>`).join('')||'<div class="empty">Пинов в этой выборке нет.</div>';list.querySelectorAll('[data-pin-index]').forEach(el=>el.onclick=()=>openPin(arr[Number(el.dataset.pinIndex)]))}
function openModal(html){$('modalBody').innerHTML=html;$('modal').classList.add('open')}
function closeModal(){$('modal').classList.remove('open');$('modalBody').innerHTML=''}
async function openPin(p){try{const t=await api('pin_thread',{pinCode:p.pin_code}),msgs=t.messages||t.thread||[];openModal(`<h2>${esc(p.pin_code||'PIN')}</h2><p>${esc(p.comment||'')}</p><div class="rows">${(Array.isArray(msgs)?msgs:[]).map(m=>`<div class="row"><strong class="rowTitle">${esc(m.author_kind||m.authorKind||m.actor_ref||'')}</strong><div>${esc(m.message||m.body||m.text||'')}</div><span class="rowMeta">${esc(m.created_at||m.createdAt||'')}</span></div>`).join('')||'<div class="row"><div class="empty">Диалог пуст.</div></div>'}</div><label>Ответ по пину</label><textarea id="pinReply" rows="3"></textarea><label>Статус</label><select id="pinStatus"><option value="open">Новый</option><option value="in_progress">В работе</option><option value="done">Готово</option><option value="resolved">Принято</option></select><div class="modalActions"><button class="ghostBtn" id="pinSend">Ответить</button><button class="primaryBtn" id="pinSaveStatus">Сохранить статус</button></div>`);$('pinStatus').value=String(p.status||'open');$('pinSend').onclick=async()=>{const m=$('pinReply').value.trim();if(!m)return;await api('pin_message',{pinCode:p.pin_code,message:m});toast('Ответ отправлен');closeModal();await loadPins()};$('pinSaveStatus').onclick=async()=>{await api('pin_status',{pinCode:p.pin_code,status:$('pinStatus').value,implementedInVersion:workingVersion()});toast('Статус обновлён');closeModal();await loadPins()}}catch(e){toast(e.message)}}
async function openEvent(x){openModal(`<h2>${esc(x.summary||bestText(x))}</h2><p>${esc(metaText(x))}</p><pre>${esc(JSON.stringify(x,null,2))}</pre><label>Ответ событию</label><textarea id="eventReply" rows="3"></textarea><div class="modalActions"><button class="ghostBtn" id="eventRead">Отметить прочитанным</button><button class="primaryBtn" id="eventSend">Ответить</button></div>`);$('eventRead').onclick=async()=>{try{await api('computer_event_mark',{eventKey:x.event_key,state:'READ'});toast('Отмечено');closeModal();await refresh()}catch(e){toast(e.message)}};$('eventSend').onclick=async()=>{const m=$('eventReply').value.trim();if(!m)return;try{await api('computer_event_reply',{eventKey:x.event_key,message:m,payload:{}});toast('Ответ записан');closeModal();await refresh()}catch(e){toast(e.message)}}}
async function loadPins(){try{const d=await api('pins',{version:'',surface:'president'});state.pins=Array.isArray(d.pins)?d.pins:(Array.isArray(d)?d:[]);if(state.boot)state.boot.pins=state.pins;renderHeader();if($('drawer').classList.contains('open'))renderDrawer()}catch(e){console.warn(e)}}
function pinSelector(el){if(!el)return'';if(el.dataset?.pin)return`[data-pin="${CSS.escape(el.dataset.pin)}"]`;if(el.id)return`#${CSS.escape(el.id)}`;return el.tagName?.toLowerCase()||''}
function setPinMode(on){state.pinMode=on;document.body.classList.toggle('pinArmed',on);$('pinsBtn').classList.toggle('recording',on);toast(on?'Выбери точное место на фронте':'PIN отменён')}
function onPinClick(e){if(!state.pinMode)return;const el=e.target.closest('[data-pin],button,.row,.sourceGroup,.majorCard,.moduleCard,.sectorCard');if(!el||['pinsBtn','pencilBtn','mailBtn','idBtn'].includes(el.id))return;e.preventDefault();e.stopPropagation();setPinMode(false);const key=el.dataset.pin||el.id||bestText({title:el.textContent?.trim().slice(0,120)}),rect=el.getBoundingClientRect();openModal(`<h2>Новый PIN</h2><p>${esc(key)}</p><label>Что здесь нужно сделать / уточнить?</label><textarea id="newPinComment" rows="5"></textarea><div class="modalActions"><button class="ghostBtn" id="pinCancel">Отмена</button><button class="primaryBtn" id="pinCreate">Сохранить PIN</button></div>`);$('pinCancel').onclick=closeModal;$('pinCreate').onclick=async()=>{const comment=$('newPinComment').value.trim();if(!comment)return;try{await control('pin_create',{version:workingVersion(),surface:'president',pageKey:state.current,targetKey:key,targetLabel:(el.textContent||key).trim().slice(0,500),anchor:{kind:'element',selector:pinSelector(el),rx:.5,ry:.5,docX:Math.round(rect.left+rect.width/2+scrollX),docY:Math.round(rect.top+rect.height/2+scrollY)},viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio||1},comment});closeModal();toast('PIN создан');await loadPins()}catch(err){toast(err.message)}}}
function traceEvent(type,e={}){if(!trace.recording)return;const target=e.target?.closest?.('[data-pin],button,input,textarea,select,.row,.sourceGroup')||e.target;trace.events.push({type,t:Math.round(performance.now()-trace.started),page:state.current,target:target?.dataset?.pin||target?.id||target?.tagName||'',x:Number.isFinite(e.clientX)?Math.round(e.clientX):undefined,y:Number.isFinite(e.clientY)?Math.round(e.clientY):undefined});if(trace.events.length>=40)flushTrace()}
async function flushTrace(){if(!trace.recording||!trace.code||!trace.events.length)return;const batch=trace.events.splice(0);try{await control('trace_append',{traceCode:trace.code,checkpoint:'MOTHER_SHIP_FRONT',frontVersion:`${FRONT_VERSION}@${workingVersion()}`,segmentKey:trace.segment,chunkSeq:trace.seq++,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio||1},summary:{eventCount:batch.length,page:state.current},events:batch})}catch(e){console.warn(e)}}
async function togglePencil(){if(!trace.recording){try{const d=await control('trace_start',{checkpoint:'MOTHER_SHIP_FRONT',frontVersion:`${FRONT_VERSION}@${workingVersion()}`,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio||1}});trace.recording=true;trace.code=d.traceCode||d.trace_code||d.code;trace.segment='SEG-'+crypto.randomUUID().slice(0,10).toUpperCase();trace.seq=0;trace.events=[];trace.started=performance.now();$('pencilBtn').classList.add('recording');$('pencilBtn').querySelector('.label').textContent='Стоп';toast(`Карандаш ${trace.code||''} записывает`) }catch(e){toast(e.message)}return}
 await flushTrace();trace.recording=false;$('pencilBtn').classList.remove('recording');$('pencilBtn').querySelector('.label').textContent='Карандаш';openModal(`<h2>Завершить Карандаш</h2><p>${esc(trace.code||'TRACE')}</p><label>Что ты хотела показать?</label><textarea id="traceComment" rows="5"></textarea><div class="modalActions"><button class="ghostBtn" id="traceResume">Продолжить</button><button class="primaryBtn" id="traceFinish">Сохранить</button></div>`);$('traceResume').onclick=()=>{closeModal();trace.recording=true;$('pencilBtn').classList.add('recording')};$('traceFinish').onclick=async()=>{try{await control('trace_finalize',{traceCode:trace.code,title:`Карандаш · ${state.current}`,comment:$('traceComment').value.trim(),summary:{frontVersion:FRONT_VERSION,workingVersion:workingVersion(),page:state.current}});toast('Карандаш сохранён');closeModal()}catch(e){toast(e.message)}finally{trace.code='';trace.events=[]}}}
function openIdentity(){openModal(`<h2>Создать SETKA ID</h2><p>Новый ID создаёт системный генератор. Роль и доступ назначаются поверх identity.</p><label>Имя / метка</label><input id="idName" placeholder="Например, Саша"><label>Природа</label><select id="idNature"><option value="human">Человек</option><option value="synthetic">Синтетик</option></select><label><input type="checkbox" id="idFront" checked> Доступ к front</label><label><input type="checkbox" id="idBack"> Доступ к back</label><label>Задача / роль</label><textarea id="idTask" rows="3"></textarea><div class="modalActions"><button class="primaryBtn" id="idCreate">Создать</button></div>`);$('idCreate').onclick=async()=>{try{const d=await api('identity_create',{displayName:$('idName').value.trim(),nature:$('idNature').value,frontEnabled:$('idFront').checked,backEnabled:$('idBack').checked,task:$('idTask').value.trim()});const r=d.result||{};openModal(`<h2>ID создан</h2><p><strong>${esc(r.setkaId||r.setka_id||r.identityRef||'')}</strong></p><label>Персональный ключ — показывается один раз</label><textarea id="newKey" rows="2" readonly>${esc(d.personalKey||'')}</textarea><div class="modalActions"><button class="primaryBtn" id="copyNewId">Скопировать ID + ключ</button></div>`);$('copyNewId').onclick=async()=>{await navigator.clipboard.writeText(`${r.setkaId||r.setka_id||''}\n${d.personalKey||''}`);toast('Скопировано')}}catch(e){toast(e.message)}}}
function showLogin(){$('loginScreen').classList.add('show')}
function hideLogin(){$('loginScreen').classList.remove('show')}
async function login(){const setkaId=$('loginId').value.trim().toUpperCase(),key=$('loginKey').value.trim();if(!setkaId||!key)return;try{const d=await post(AUTH,'president_login',{setkaId,presidentKey:key},false);setToken(d.sessionToken);hideLogin();await refresh()}catch(e){$('loginError').textContent=e.message}}
async function refresh(){if(!token()){showLogin();return}try{const d=await api('bootstrap');state.boot=d;state.pins=Array.isArray(d.pins)?d.pins:[];renderHeader();renderRail();if(state.current==='HOME')renderDashboard();else if(state.module)await openModule(state.module.key);hideLogin()}catch(e){if(String(e.message).includes('Президент'))return;toast(e.message)}}
function bind(){
 $('refreshBtn').onclick=refresh;$('pinsBtn').onclick=()=>state.pinMode?setPinMode(false):setPinMode(true);$('mailBtn').onclick=()=>openDrawer('mail');$('idBtn').onclick=openIdentity;$('pencilBtn').onclick=togglePencil;$('computerFab').onclick=openComputer;$('computerClose').onclick=closeComputer;$('drawerClose').onclick=closeDrawer;$('modalClose').onclick=closeModal;$('moduleBack').onclick=goHome;$('moduleSearch').oninput=renderModuleSources;$('computerForm').onsubmit=e=>{e.preventDefault();sendComputer($('computerInput').value)};$('loginBtn').onclick=login;$('loginKey').addEventListener('keydown',e=>{if(e.key==='Enter')login()});document.addEventListener('click',onPinClick,true);document.addEventListener('pointerdown',e=>traceEvent('pointerdown',e),true);document.addEventListener('pointerup',e=>traceEvent('pointerup',e),true);document.addEventListener('click',e=>{if(!state.pinMode)traceEvent('click',e)},true);document.addEventListener('scroll',e=>{if(!trace.recording)return;const now=performance.now();if(now-trace.lastScroll<150)return;trace.lastScroll=now;trace.events.push({type:'scroll',t:Math.round(now-trace.started),page:state.current,x:Math.round(scrollX),y:Math.round(scrollY)});},true);window.addEventListener('beforeunload',()=>{if(trace.recording&&trace.events.length)flushTrace()});}
bind();refresh();
})();