(()=>{
'use strict';
const API='https://gfchgaphzhxufwdhrcis.supabase.co/functions/v1/setka-mother-president-v1';
const AUTH='https://gfchgaphzhxufwdhrcis.supabase.co/functions/v1/setka-foundation-v018';
const CONTROL='https://gfchgaphzhxufwdhrcis.supabase.co/functions/v1/setka-foundation-control';
const SESSION_KEY='setka:foundation:president:session';
const $=id=>document.getElementById(id);
const state={boot:null,current:'HOME',versions:null,pins:[],pinFilter:'active',history:['HOME'],historyIndex:0,pinMode:false,pinTarget:null};
const trace={recording:false,code:'',segment:'',seq:0,events:[],started:0,lastMove:0,lastScroll:0};
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const token=()=>{try{return localStorage.getItem(SESSION_KEY)||''}catch{return''}};
const setToken=v=>{try{if(v)localStorage.setItem(SESSION_KEY,v);else localStorage.removeItem(SESSION_KEY)}catch{}};
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2400)}
async function post(url,action,payload={},auth=true){const headers={'content-type':'application/json'};if(auth&&token())headers['x-setka-session']=token();const r=await fetch(url,{method:'POST',headers,body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({}));if(r.status===401&&auth){showLogin();throw new Error('Нужна Президентская сессия')}if(!r.ok)throw new Error(d.detail||d.error||'Ошибка запроса');return d}
const api=(action,payload={})=>post(API,action,payload,true);
const control=(action,payload={})=>post(CONTROL,action,payload,true);
function iconFor(ref,kind=''){const k=(ref+' '+kind).toUpperCase();if(k.includes('BRIDGE')||k.includes('COMMAND'))return'🧭';if(k.includes('VERSTAK')||k.includes('WORK'))return'🛠';if(k.includes('CREW'))return'👥';if(k.includes('KNOWLEDGE'))return'🧬';if(k.includes('ENGINE'))return'⚙️';if(k.includes('SECURITY'))return'🛡';if(k.includes('OBSERV'))return'📡';if(k.includes('POLYGON')||k.includes('EXPER'))return'🧪';if(k.includes('HOLD')||k.includes('STORAGE'))return'📦';return'◈'}
function shortPurpose(s){return s?.canonical_state?.purpose||s?.canonical_state?.role||''}
function sectorKey(s){return String(s.sector_ref||'').split('/').at(-1)||'UNKNOWN'}
function visibleSectors(){return (state.boot?.sectors||[]).filter(s=>s.sector_ref!=='SHIP/SETKA'&&String(s.sector_ref||'').startsWith('SHIP/SETKA/'))}
function renderNav(){const nav=$('sectorNav');nav.innerHTML='';for(const s of visibleSectors()){const key=sectorKey(s);const b=document.createElement('button');b.dataset.section=key;b.innerHTML=`<span>${iconFor(s.sector_ref,s.sector_kind)}</span><em>${esc(String(s.display_name_ru||key).replace(/^\S+\s*/,''))}</em>`;b.onclick=()=>go(key,true);nav.appendChild(b)}setActiveNav()}
function setActiveNav(){document.querySelectorAll('.railHome,.sectorNav button').forEach(b=>b.classList.toggle('active',b.dataset.section===state.current))}
function stat(label,value){return `<div class="stat"><strong>${esc(value)}</strong><span>${esc(label)}</span></div>`}
function renderHome(){const b=state.boot;if(!b)return;$('shipTitle').textContent=b.ship?.display_name_ru||'Материнский корабль SETKA';$('shipMeta').textContent=`${b.ship?.ship_code||''} · ${b.ship?.state||'—'} · владелец ${b.ship?.owner_identity_ref||'—'}`;$('shipState').innerHTML=`<i></i><span>${esc(b.ship?.state==='active'?'Корабль активен':'Состояние: '+(b.ship?.state||'—'))}</span>`;$('heroStats').innerHTML=stat('отсеков',visibleSectors().length)+stat('экипаж',Array.isArray(b.crew)?b.crew.length:0)+stat('дочерних кораблей',Array.isArray(b.children)?b.children.length:0)+stat('PIN',state.pins.length);
 const grid=$('roomGrid');grid.innerHTML='';for(const s of visibleSectors()){const key=sectorKey(s),d=document.createElement('article');d.className='room';d.dataset.pinKey=`sector:${s.sector_ref}`;d.innerHTML=`<div><div class="roomTop"><div class="roomIcon">${iconFor(s.sector_ref,s.sector_kind)}</div><span class="kicker">${esc(s.sector_kind||'SECTOR')}</span></div><h3>${esc(s.display_name_ru||key)}</h3><p>${esc(shortPurpose(s)||'Открыть реальное состояние сектора.')}</p></div><div class="roomFoot"><span>${esc(s.state||'')}</span><span>Войти →</span></div>`;d.onclick=()=>go(key,true);grid.appendChild(d)}
 renderEvents();renderChildren();renderComputer();renderPinsBadge();
}
function bestText(x){if(x==null)return'—';if(typeof x==='string')return x;if(typeof x==='number'||typeof x==='boolean')return String(x);if(Array.isArray(x))return x.length?bestText(x[0]):'—';for(const k of ['title_ru','title','display_name_ru','display_name','summary_ru','summary','event_type','eventType','message','body','name','code','ship_code','pin_code','position_ref','entity_ref','setka_id','identity_ref'])if(x[k])return String(x[k]);return Object.entries(x).slice(0,2).map(([k,v])=>`${k}: ${typeof v==='object'?'…':v}`).join(' · ')||'Запись'}
function secondText(x){if(!x||typeof x!=='object')return'';for(const k of ['description_ru','description','purpose','status','state','created_at','updated_at','occurred_at','event_time','source_ref','scope_ref'])if(x[k])return `${k}: ${typeof x[k]==='object'?JSON.stringify(x[k]):x[k]}`;return''}
function renderEvents(){const e=state.boot?.eventInbox;const arr=Array.isArray(e)?e:(e?.items||e?.events||[]);const box=$('eventPreview');box.innerHTML='';if(!Array.isArray(arr)||!arr.length){box.innerHTML='<div class="empty">Нет событий для показа.</div>';return}for(const x of arr.slice(0,6)){const d=document.createElement('div');d.className='feedItem';d.innerHTML=`<strong>${esc(bestText(x))}</strong><span>${esc(secondText(x))}</span>`;box.appendChild(d)}}
function renderChildren(){const box=$('childShips');box.innerHTML='';const arr=Array.isArray(state.boot?.children)?state.boot.children:[];if(!arr.length){box.innerHTML='<div class="empty">Дочерних кораблей пока нет.</div>';return}for(const x of arr.slice(0,8)){const d=document.createElement('div');d.className='card';d.innerHTML=`<strong>${esc(x.display_name_ru||x.ship_code)}</strong><span>${esc(x.ship_code)} · ${esc(x.state||'')}</span>`;box.appendChild(d)}}
function renderComputer(){const c=state.boot?.computer;$('computerStatus').textContent=c?`${c.display_name_ru||'Бортовой'} · ${c.status||''}`:'Недоступен';$('computerSummary').textContent=c?'Бортовой компьютер подключён к Материнскому кораблю. Он отвечает сам и использует Command Bus только для разрешённых операций.':'Нет данных о бортовом компьютере.';const q=$('quickActions');q.innerHTML='';const arr=Array.isArray(state.boot?.quickActions)?state.boot.quickActions:(state.boot?.quickActions?.items||[]);if(!arr?.length){q.innerHTML='<span class="empty">Нет быстрых действий.</span>';return}for(const x of arr.slice(0,10)){const b=document.createElement('button');b.textContent=bestText(x);b.title=secondText(x);b.onclick=()=>runQuick(x);q.appendChild(b)}}
async function runQuick(x){try{const code=x.command_code||x.commandCode||x.code;if(code){const d=await api('command_submit',{commandCode:code,arguments:{},scopeKind:x.scope_kind||'SHIP',scopeRef:x.scope_ref||'SHIP-SETKA-MOTHER',autoExecute:false});appendChat('system',`Команда ${code} принята: ${bestText(d.result||d)}`);return}const msg=bestText(x);$('computerInput').value=msg;await sendComputer(msg)}catch(e){toast(e.message)}}
function renderPinsBadge(){const n=state.pins.filter(p=>['open','in_progress','proposed'].includes(String(p.status))).length;const b=$('pinsBadge');if(n){b.textContent=String(n);b.style.display='flex'}else b.style.display='none'}
function setViews(){const home=state.current==='HOME';$('homeView').classList.toggle('active',home);$('sectionView').classList.toggle('active',!home);setActiveNav()}
function pushHistory(k){state.history=state.history.slice(0,state.historyIndex+1);state.history.push(k);state.historyIndex=state.history.length-1}
async function go(key,push=false){key=String(key||'HOME').toUpperCase();state.current=key;if(push)pushHistory(key);setViews();if(key==='HOME'){renderHome();return}await loadSection(key)}
function sectorByKey(key){return visibleSectors().find(s=>sectorKey(s)===key)}
async function loadSection(key){const s=sectorByKey(key);$('sectionKind').textContent=s?.sector_kind||key;$('sectionTitle').textContent=s?.display_name_ru||key;$('sectionPurpose').textContent=shortPurpose(s)||'Реальное состояние backend-сектора.';$('sectionSources').innerHTML='<span>Загрузка backend-связей…</span>';$('sectionData').innerHTML='<div class="loading">Загружаю данные сектора…</div>';try{const d=await api('section',{key});$('sectionSources').innerHTML=(d.sources||[]).map(x=>`<span>${esc(x)}</span>`).join('')||'<span>Нет источников</span>';renderDataGroups(d.data||{})}catch(e){$('sectionData').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
function asArray(v){if(Array.isArray(v))return v;if(v&&typeof v==='object'&&v.__error)return null;if(v&&typeof v==='object'){for(const k of ['items','rows','data','pins','events','reports','tasks','missions'])if(Array.isArray(v[k]))return v[k]}return v==null?[]:[v]}
function renderDataGroups(data){const box=$('sectionData');box.innerHTML='';for(const [name,val] of Object.entries(data)){const g=document.createElement('section');g.className='dataGroup';const arr=asArray(val);if(arr===null){g.innerHTML=`<div class="dataGroupHead"><h3>${esc(name)}</h3><span>ошибка источника</span></div><div class="row"><div class="error">${esc(val.__source||'')}: ${esc(val.__error||'')}</div></div>`;box.appendChild(g);continue}g.innerHTML=`<div class="dataGroupHead"><h3>${esc(name)}</h3><span>${arr.length} записей</span></div><div class="rows"></div>`;const rows=g.querySelector('.rows');if(!arr.length)rows.innerHTML='<div class="row"><div class="empty">Пусто</div></div>';for(const x of arr.slice(0,40)){const d=document.createElement('details');d.className='row';d.dataset.pinKey=`${state.current}:${name}:${bestText(x).slice(0,80)}`;d.innerHTML=`<summary><span class="rowTitle">${esc(bestText(x))}</span><span class="rowMeta">${esc(secondText(x))}</span></summary><pre>${esc(JSON.stringify(x,null,2))}</pre>`;rows.appendChild(d)}if(arr.length>40){const more=document.createElement('div');more.className='row';more.innerHTML=`<div class="empty">Показаны первые 40 из ${arr.length}. Источник подключён полностью через API сектора.</div>`;rows.appendChild(more)}box.appendChild(g)}if(!Object.keys(data).length)box.innerHTML='<div class="empty">Для этого сектора пока нет поверхности данных.</div>'}
function openDrawer(kind){$('drawer').classList.add('open');$('drawer').setAttribute('aria-hidden','false');if(kind==='pins'||kind==='mail'){state.pinFilter=kind==='mail'?'active':'all';$('drawerKicker').textContent=kind==='mail'?'ПОЧТА PIN':'PIN SYSTEM';$('drawerTitle').textContent=kind==='mail'?'Почта / диалоги':'Пины Материнского корабля';renderPinsDrawer()} }
function closeDrawer(){$('drawer').classList.remove('open');$('drawer').setAttribute('aria-hidden','true')}
function statusClass(s){s=String(s||'');if(s==='open'||s==='proposed')return'red';if(s==='in_progress')return'yellow';if(s==='done')return'green';if(s==='resolved')return'green';return'grey'}
function filterPins(){if(state.pinFilter==='all')return state.pins;if(state.pinFilter==='active')return state.pins.filter(p=>!['resolved','rejected','deleted'].includes(String(p.status)));return state.pins.filter(p=>p.status===state.pinFilter)}
function renderPinsDrawer(){const b=$('drawerBody');b.innerHTML=`<div class="pinFilters"><button data-f="all">Все</button><button data-f="active">Активные</button><button data-f="open">Новые</button><button data-f="in_progress">В работе</button><button data-f="done">Готово</button><button data-f="resolved">Принято</button></div><div class="pinList"></div>`;b.querySelectorAll('[data-f]').forEach(x=>{x.classList.toggle('active',x.dataset.f===state.pinFilter);x.onclick=()=>{state.pinFilter=x.dataset.f;renderPinsDrawer()}});const list=b.querySelector('.pinList'),arr=filterPins();if(!arr.length){list.innerHTML='<div class="empty">Пинов в этой выборке нет.</div>';return}for(const p of arr){const d=document.createElement('div');d.className='pinItem';d.innerHTML=`<div class="pinLine"><strong><i class="dot ${statusClass(p.status)}"></i>${esc(p.pin_code||'PIN')}</strong><span class="rowMeta">${esc(p.status||'')}</span></div><p>${esc(p.comment||p.target_label||'')}</p>`;d.onclick=()=>openPin(p);list.appendChild(d)}}
async function loadPins(){try{const d=await api('pins',{version:'',surface:'president'});state.pins=Array.isArray(d.pins)?d.pins:[];renderPinsBadge();if($('drawer').classList.contains('open'))renderPinsDrawer()}catch(e){console.warn(e)}}
function openModal(html){$('modalBody').innerHTML=html;$('modal').classList.add('open');$('modal').setAttribute('aria-hidden','false')}
function closeModal(){$('modal').classList.remove('open');$('modal').setAttribute('aria-hidden','true');$('modalBody').innerHTML=''}
async function openPin(p){try{const t=await api('pin_thread',{pinCode:p.pin_code});const msgs=Array.isArray(t.messages)?t.messages:[],briefs=Array.isArray(t.semanticBriefs)?t.semanticBriefs:[];openModal(`<h2>${esc(p.pin_code)}</h2><div class="kicker">${esc(p.status||'')} · ${esc(p.version||'')} · ${esc(p.page_key||'')}</div><p>${esc(p.comment||'')}</p><div class="dataGroup"><div class="dataGroupHead"><h3>Диалог</h3><span>${msgs.length}</span></div><div class="rows">${msgs.map(m=>`<div class="row"><div class="rowTitle">${esc(m.authorKind||'')}</div><div>${esc(m.body||'')}</div><div class="rowMeta">${esc(m.createdAt||'')}</div></div>`).join('')||'<div class="row"><div class="empty">Диалог пуст.</div></div>'}</div></div>${briefs.length?`<div class="dataGroup" style="margin-top:10px"><div class="dataGroupHead"><h3>Смысл</h3><span>${briefs.length}</span></div><div class="rows">${briefs.map(x=>`<div class="row"><strong>${esc(x.summary||x.assistantInterpretation||'')}</strong></div>`).join('')}</div></div>`:''}<div class="formGrid" style="margin-top:12px"><label>Ответ в PIN</label><textarea id="pinReply" rows="3"></textarea><button id="pinReplyBtn" class="primaryBtn">Отправить ответ</button><label>Статус</label><select id="pinStatus"><option value="open">🔴 Новый</option><option value="in_progress">🟡 В работе</option><option value="done">🟢 Готово</option><option value="resolved">✓ Принято</option></select><button id="pinStatusBtn" class="secondaryBtn">Изменить статус</button></div>`);$('pinStatus').value=['open','in_progress','done','resolved'].includes(p.status)?p.status:'open';$('pinReplyBtn').onclick=async()=>{const message=$('pinReply').value.trim();if(!message)return;await api('pin_message',{pinCode:p.pin_code,message});toast('Ответ записан');await loadPins();openPin(p)};$('pinStatusBtn').onclick=async()=>{await api('pin_status',{pinCode:p.pin_code,status:$('pinStatus').value,implementedInVersion:$('versionSelect').value||''});toast('Статус обновлён');closeModal();await loadPins()}}catch(e){toast(e.message)}}
function startPinMode(){state.pinMode=true;document.body.classList.add('pinTargetMode');toast('Нажми на точное место для PIN');const handler=e=>{if(!state.pinMode)return;state.pinMode=false;document.body.classList.remove('pinTargetMode');document.removeEventListener('click',handler,true);e.preventDefault();e.stopPropagation();const el=e.target.closest('[data-pin-key],[id],button,article,section,details')||e.target;state.pinTarget={targetKey:el.dataset?.pinKey||el.id||el.tagName.toLowerCase(),targetLabel:(el.textContent||el.getAttribute?.('aria-label')||'область').trim().replace(/\s+/g,' ').slice(0,260),anchor:{kind:'document',docX:e.clientX+scrollX,docY:e.clientY+scrollY},viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio||1}};el.classList.add('pinFlash');setTimeout(()=>el.classList.remove('pinFlash'),700);openModal(`<h2>Новый PIN</h2><div class="kicker">${esc(state.pinTarget.targetLabel)}</div><div class="formGrid"><label>Комментарий</label><textarea id="newPinComment" rows="5" maxlength="4000"></textarea><button id="newPinSave" class="primaryBtn">Сохранить PIN</button></div>`);$('newPinSave').onclick=saveNewPin};setTimeout(()=>document.addEventListener('click',handler,true),0)}
async function saveNewPin(){const comment=$('newPinComment').value.trim();if(!comment)return;try{await control('pin_create',{version:$('versionSelect').value||'0.1.8',surface:'president',pageKey:state.current.toLowerCase(),targetKey:state.pinTarget.targetKey,targetLabel:state.pinTarget.targetLabel,anchor:state.pinTarget.anchor,viewport:state.pinTarget.viewport,comment});closeModal();toast('PIN создан');await loadPins()}catch(e){toast(e.message)}}
function traceEvent(type,extra={}){if(!trace.recording)return;trace.events.push({type,t:Math.round(performance.now()-trace.started),page:state.current,version:$('versionSelect').value||'',...extra});if(trace.events.length>=50)flushTrace()}
async function flushTrace(){if(!trace.recording||!trace.events.length||!trace.code)return;const ev=trace.events.splice(0);try{await control('trace_append',{traceCode:trace.code,checkpoint:state.current,frontVersion:$('versionSelect').value||'',segmentKey:trace.segment,chunkSeq:trace.seq++,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio||1},summary:{eventCount:ev.length},events:ev})}catch(e){console.warn(e)}}
async function togglePencil(){if(!trace.recording){try{const d=await control('trace_start',{checkpoint:state.current,frontVersion:$('versionSelect').value||'',viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio||1}});trace.recording=true;trace.code=d.traceCode||d.trace_code||d.code;trace.segment='SEG-'+crypto.randomUUID().slice(0,8).toUpperCase();trace.seq=0;trace.events=[];trace.started=performance.now();$('pencilBtn').classList.add('active');$('pencilBtn').innerHTML='■ <span>Стоп</span>';toast('Карандаш пишет путь')}catch(e){toast(e.message)}return}await flushTrace();trace.recording=false;$('pencilBtn').classList.remove('active');$('pencilBtn').innerHTML='✏️ <span>Карандаш</span>';openModal(`<h2>Завершить Карандаш</h2><div class="kicker">${esc(trace.code||'TRACE')}</div><div class="formGrid"><label>Название</label><input id="traceTitle"><label>Что ты хотела показать?</label><textarea id="traceComment" rows="5"></textarea><button id="traceFinish" class="primaryBtn">Сохранить TRACE</button></div>`);$('traceFinish').onclick=async()=>{try{await control('trace_finalize',{traceCode:trace.code,title:$('traceTitle').value.trim()||'Путь Президента',comment:$('traceComment').value.trim(),summary:{front:'mother-president-v1',page:state.current}});closeModal();toast('Карандаш сохранён');trace.code=''}catch(e){toast(e.message)}}}
document.addEventListener('click',e=>{if(trace.recording)traceEvent('click',{target:(e.target.closest('[data-pin-key],[id],button')?.dataset?.pinKey||e.target.id||e.target.tagName).slice(0,180),x:Math.round(e.clientX),y:Math.round(e.clientY)})},true);window.addEventListener('scroll',()=>{const n=performance.now();if(trace.recording&&n-trace.lastScroll>150){trace.lastScroll=n;traceEvent('scroll',{x:Math.round(scrollX),y:Math.round(scrollY)})}},true);
async function sendComputer(message){message=String(message||'').trim();if(!message)return;appendChat('me',message);$('computerInput').value='';try{const d=await api('computer_chat',{message});appendChat('system',bestText(d.result||d))}catch(e){appendChat('system','Ошибка: '+e.message)}}
function appendChat(kind,text){const d=document.createElement('div');d.className='chatMsg '+kind;d.textContent=text;$('chatLog').appendChild(d);$('chatLog').scrollTop=$('chatLog').scrollHeight}
function showLogin(){if($('modal').classList.contains('open')&&$('loginForm'))return;openModal(`<h2>Вход Президента</h2><p>Этот фронт использует тот же Президентский доступ Foundation.</p><div id="loginForm" class="formGrid"><label>SETKA ID</label><input id="loginId" value="SETKA-0001-0001"><label>Президентский ключ</label><input id="loginKey" type="password" autocomplete="current-password"><button id="loginSubmit" class="primaryBtn">Войти на Материнский корабль</button></div>`);$('loginSubmit').onclick=async()=>{try{const d=await post(AUTH,'president_login',{setkaId:$('loginId').value,presidentKey:$('loginKey').value},false);setToken(d.sessionToken);closeModal();toast('Президентская сессия активна');await init()}catch(e){toast(e.message)}}}
async function loadVersions(){try{const d=await api('versions');state.versions=d.manifest;const select=$('versionSelect'),ptr=d.manifest?.pointers||{};select.innerHTML=(d.manifest?.versions||[]).map(v=>`<option value="${esc(v.version)}">${esc(v.version)}${ptr.working===v.version?' · WORKING':''}${ptr.canon===v.version?' · CANON':''}</option>`).join('');if(ptr.working)select.value=ptr.working}catch(e){$('versionSelect').innerHTML='<option>LIVE</option>'}}
async function init(){if(!token()){showLogin();return}try{const [boot]=await Promise.all([api('bootstrap'),loadVersions()]);state.boot=boot;state.pins=Array.isArray(boot.pins)?boot.pins:[];renderNav();renderHome();setViews()}catch(e){if(!/сессия|session/i.test(e.message))toast(e.message)}}
$('computerForm').addEventListener('submit',e=>{e.preventDefault();sendComputer($('computerInput').value)});$('pinsBtn').onclick=()=>openDrawer('pins');$('mailBtn').onclick=()=>openDrawer('mail');$('pencilBtn').onclick=togglePencil;$('idBtn').onclick=()=>{openModal(`<h2>Создать ID</h2><div class="formGrid"><label>Тип</label><select id="newNature"><option value="human">Человек</option><option value="synthetic">Синтетик</option></select><label>Имя</label><input id="newName"><label>Назначение / задача</label><textarea id="newTask" rows="3"></textarea><label>Характер (для синтетика)</label><textarea id="newPersonality" rows="2"></textarea><label><input id="frontEnabled" type="checkbox" checked> Front доступ</label><label><input id="backEnabled" type="checkbox"> Back доступ</label><button id="createIdBtn" class="primaryBtn">Создать системный ID</button></div>`);$('createIdBtn').onclick=async()=>{try{const d=await api('identity_create',{nature:$('newNature').value,displayName:$('newName').value,task:$('newTask').value,personality:$('newPersonality').value,frontEnabled:$('frontEnabled').checked,backEnabled:$('backEnabled').checked});$('modalBody').innerHTML=`<h2>ID создан</h2><pre>${esc(JSON.stringify(d.result,null,2))}</pre><div class="formGrid"><label>Персональный ключ — показывается сейчас</label><input value="${esc(d.personalKey||'')}" readonly><button id="copyKey" class="primaryBtn">Скопировать ключ</button></div>`;$('copyKey').onclick=()=>navigator.clipboard?.writeText(d.personalKey||'').then(()=>toast('Ключ скопирован'))}catch(e){toast(e.message)}}};$('refreshBtn').onclick=init;$('drawerClose').onclick=closeDrawer;$('modalClose').onclick=closeModal;$('sectionBack').onclick=()=>go('HOME',true);document.querySelector('.railHome').onclick=()=>go('HOME',true);document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go,true));$('logoutBtn').onclick=async()=>{try{await post(AUTH,'logout',{},true)}catch{}setToken('');location.reload()};$('computerCollapse').onclick=()=>{$('computer').classList.toggle('collapsed');$('computerCollapse').textContent=$('computer').classList.contains('collapsed')?'‹':'›'};$('backBtn').onclick=()=>{if(state.historyIndex>0){state.historyIndex--;go(state.history[state.historyIndex],false)}};$('forwardBtn').onclick=()=>{if(state.historyIndex<state.history.length-1){state.historyIndex++;go(state.history[state.historyIndex],false)}};
init();
})();