(()=>{
'use strict';
const API='https://gfchgaphzhxufwdhrcis.supabase.co/functions/v1/setka-mother-president-v4';
const AUTH='https://gfchgaphzhxufwdhrcis.supabase.co/functions/v1/setka-foundation-v018';
const SESSION_KEY='setka:foundation:president:session';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const token=()=>{try{return localStorage.getItem(SESSION_KEY)||''}catch{return''}};
const setToken=v=>{try{v?localStorage.setItem(SESSION_KEY,v):localStorage.removeItem(SESSION_KEY)}catch{}};
const MODULES=[
 ['HOME','⌂','Главная','Материнский корабль'],
 ['FLEET','🚀','Флот','Корабли, кандидаты на рождение, Ghost Fleet, обмен между кораблями'],
 ['EXPERIMENTS','🧪','Эксперименты','Полигоны, Ghost G2, Crown, Pocket Core и испытания'],
 ['WORK','🧭','Мостик / работа','Миссии, атомарные задачи, приоритеты и выполнение'],
 ['VERSTAK','🛠','VERSTAK','Проекты, отсеки проектов, UI PIN, Pencil и события'],
 ['CREW','👥','Экипаж','Люди, занятость, должности, duty и профессиональные карты'],
 ['SYNTHETICS','🤖','Синтетики','Neural runs, пробуждения, runtime, handoff и автономия'],
 ['KNOWLEDGE','🧬','Сущности / знания','Карточки сущностей, позвоночник, отношения, источники и кандидаты'],
 ['CAPABILITIES','⚡','Capability / Command Bus','Команды, запросы, события, gaps и promotion'],
 ['OBSERVATORY','📡','Обсерватория','Пульс, графы, время, достижения и телеметрия'],
 ['TRANSCRIPT','🕰','Стенограмма / рапорты','Append-only история, системные и синтетические отчёты'],
 ['MEMORY','🧠','Память','Слои памяти, физиология, retention, capsules и архивирование'],
 ['SECURITY','🛡','Безопасность','Guards, admission, authority, integrity и runtime audit'],
 ['STORAGE','📦','Контейнеры / архив','Хранилища, cold archive, transcript archive и recovery evidence'],
 ['COMMUNICATION','✉️','Связь / Event Hub','Диалоги, события, ответы, контакты и маршрутизация'],
 ['GOVERNANCE','👑','Президент / Governance','Полномочия, решения, режимы, политики и admission'],
 ['ATLAS','🗺️','Атлас backend','Полный безопасный каталог backend-отношений']
].map(([key,icon,title,subtitle])=>({key,icon,title,subtitle}));
let current='HOME', currentData=null, currentModule=null, lastSearch='';
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
async function post(url,action,payload={},auth=true){const headers={'content-type':'application/json'};if(auth&&token())headers['x-setka-session']=token();const r=await fetch(url,{method:'POST',headers,body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({}));if(r.status===401&&auth){showLogin();throw new Error('Нужна Президентская сессия')}if(!r.ok)throw new Error(d.detail||d.error||`HTTP ${r.status}`);return d}
const api=(action,payload={})=>post(API,action,payload,true);
function showLogin(){$('login').classList.add('show')}
function hideLogin(){$('login').classList.remove('show')}
function renderSidebar(){const box=$('sidebar');box.innerHTML=MODULES.map(m=>`<button class="navBtn ${m.key===current?'active':''}" data-key="${m.key}" title="${esc(m.title)}"><span class="ico">${m.icon}</span><span class="txt">${esc(m.title)}</span></button>`).join('');box.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>openKey(b.dataset.key))}
function renderHome(){current='HOME';$('home').classList.add('active');$('module').classList.remove('active');renderSidebar();$('homeGrid').innerHTML=MODULES.filter(m=>m.key!=='HOME').map(m=>`<button class="homeCard" data-open="${m.key}"><div class="bigIco">${m.icon}</div><h3>${esc(m.title)}</h3><p>${esc(m.subtitle)}</p></button>`).join('');$('homeGrid').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openModule(b.dataset.open))}
async function openKey(key){if(key==='HOME')return renderHome();return openModule(key)}
function titleFor(key){return MODULES.find(m=>m.key===key)||{key,icon:'◈',title:key,subtitle:''}}
async function openModule(key){current=key;currentModule=titleFor(key);currentData=null;lastSearch='';$('home').classList.remove('active');$('module').classList.add('active');renderSidebar();$('moduleIcon').textContent=currentModule.icon;$('moduleTitle').textContent=currentModule.title;$('moduleSubtitle').textContent=currentModule.subtitle;$('search').value='';$('moduleStatus').innerHTML='<span class="loading">Подключаю живые данные…</span>';$('sources').innerHTML='';try{const d=await api('module',{key,limit:18});currentData=d;renderModule(d);$('moduleStatus').textContent=`Открыт живой backend · ${Object.keys(d.sources||{}).length} источников`}catch(e){$('moduleStatus').textContent='';$('sources').innerHTML=`<div class="errorBox">${esc(e.message)}</div>`}}
function bestText(x){if(x==null)return'—';if(typeof x==='string'||typeof x==='number'||typeof x==='boolean')return String(x);for(const k of ['display_name_ru','title_ru','title','name','setka_id','identity_ref','local_identity_ref','ship_code','mission_ref','mission_code','experiment_code','experiment_ref','candidate_code','report_ref','pin_code','event_type','eventType','command_code','commandCode','entity_ref','source_ref','position_ref','role_ref'])if(x?.[k]!=null&&x[k]!=='')return String(x[k]);const p=Object.entries(x||{}).find(([,v])=>['string','number','boolean'].includes(typeof v));return p?String(p[1]):'Запись'}
function meta(row){const bits=[];for(const k of ['state','status','stage','kind','role','role_ref','position_ref','ship_code','sector_ref','scope_ref','event_type','created_at','updated_at','occurred_at','generated_at','prepared_at','admitted_at'])if(row?.[k]!=null&&row[k]!==''&&bits.length<4)bits.push(`${k}: ${typeof row[k]==='object'?JSON.stringify(row[k]):row[k]}`);return bits.join(' · ')}
function chips(row){const keys=['setka_id','identity_ref','local_identity_ref','ship_code','experiment_code','mission_ref','mission_code','position_ref','role_ref','state','status','stage','kind'];return keys.filter(k=>row?.[k]!=null&&row[k]!=='').slice(0,5).map(k=>`<span class="chip">${esc(k)}: ${esc(typeof row[k]==='object'?JSON.stringify(row[k]):row[k])}</span>`).join('')}
function card(row,source,key){const title=bestText(row);let extra='';if(key==='CREW'||key==='SYNTHETICS'){const who=row.display_name_ru||row.name||row.identity_ref||row.setka_id||row.local_identity_ref||title;extra=`<h4>${esc(who)}</h4><div class="meta">${esc(meta(row))}</div>`}else if(key==='FLEET'){extra=`<h4>${esc(row.display_name_ru||row.ship_code||title)}</h4><div class="meta">${esc(meta(row))}</div>`}else if(key==='EXPERIMENTS'){extra=`<h4>${esc(row.title_ru||row.experiment_code||row.experiment_ref||title)}</h4><div class="meta">${esc(meta(row))}</div>`}else{extra=`<h4>${esc(title)}</h4><div class="meta">${esc(meta(row))}</div>`}return `<article class="dataCard" title="${esc(source)}">${extra}<div class="chips">${chips(row)}</div></article>`}
function renderModule(d){const q=$('search').value.trim().toLowerCase();lastSearch=q;const entries=Object.entries(d.sources||{});const out=[];for(const [name,src] of entries){const rows=Array.isArray(src.rows)?src.rows:[];if(src.rows&&src.rows.__error){out.push(`<section class="source"><div class="sourceHead"><h3>${esc(src.title||name)}</h3><span>ошибка источника</span></div><div class="errorBox">${esc(src.rows.__error)}</div></section>`);continue}const filtered=!q?rows:rows.filter(r=>`${bestText(r)} ${meta(r)} ${JSON.stringify(r)}`.toLowerCase().includes(q));if(q&&!filtered.length&&!String(src.title||name).toLowerCase().includes(q))continue;out.push(`<section class="source"><div class="sourceHead"><h3>${esc(src.title||name)}</h3><span>${src.count==null?'':src.count+' всего'} · foundation.${esc(name)}</span></div><div class="cards">${filtered.length?filtered.map(r=>card(r,name,current)).join(''):'<div class="empty">Нет записей.</div>'}</div></section>`)}$('sources').innerHTML=out.length?out.join(''):'<div class="empty">Ничего не найдено.</div>'}
function openDrawer(title,sub,html){$('drawerTitle').textContent=title;$('drawerSub').textContent=sub||'';$('drawerBody').innerHTML=html;$('drawer').classList.add('open')}
function closeDrawer(){$('drawer').classList.remove('open')}
async function openPins(){openDrawer('PIN','Президентская PIN-почта','<div class="loading">Загружаю PIN…</div>');try{const d=await api('pins',{version:''});const arr=d.pins||d.items||[];$('drawerBody').innerHTML=`<div class="drawerList">${arr.map(p=>`<div class="drawerItem"><strong>${esc(p.pin_code||'PIN')}</strong><small>${esc([p.status,p.version,p.surface].filter(Boolean).join(' · '))}</small><div>${esc(p.comment||p.target_label||p.page_key||'')}</div></div>`).join('')||'<div class="empty">PIN нет.</div>'}</div>`}catch(e){$('drawerBody').innerHTML=`<div class="errorBox">${esc(e.message)}</div>`}}
async function openMail(){openDrawer('Почта / Event Hub','События Материнского корабля','<div class="loading">Загружаю события…</div>');try{const d=await api('computer_events',{limit:50});const arr=d.items||[];$('drawerBody').innerHTML=`<div class="drawerList">${arr.map(x=>`<div class="drawerItem"><strong>${esc(x.summary||bestText(x))}</strong><small>${esc([x.event_category,x.state,x.occurred_at].filter(Boolean).join(' · '))}</small></div>`).join('')||'<div class="empty">Событий нет.</div>'}</div>`}catch(e){$('drawerBody').innerHTML=`<div class="errorBox">${esc(e.message)}</div>`}}
async function openTraces(){openDrawer('Карандаш / TRACE','Сохранённые пути действий','<div class="loading">Загружаю TRACE…</div>');try{const d=await api('traces',{limit:80});const arr=d.traces||d.items||[];$('drawerBody').innerHTML=`<div class="drawerList">${arr.map(x=>`<div class="drawerItem"><strong>${esc(x.trace_code||x.trace_ref||bestText(x))}</strong><small>${esc(meta(x))}</small></div>`).join('')||'<div class="empty">TRACE пока нет.</div>'}</div>`}catch(e){$('drawerBody').innerHTML=`<div class="errorBox">${esc(e.message)}</div>`}}
function openId(){openDrawer('Создать SETKA ID','ID создаёт единый системный генератор',`<div class="drawerList"><input id="idName" placeholder="Имя / метка"><select id="idNature"><option value="human">Человек</option><option value="synthetic">Синтетик</option></select><textarea id="idTask" rows="4" placeholder="Задача / назначение"></textarea><label><input id="idFront" type="checkbox" checked> Front-доступ</label><label><input id="idBack" type="checkbox"> Back-доступ</label><button class="primary" id="createId" style="height:44px">Создать ID</button><div id="idResult"></div></div>`);$('createId').onclick=async()=>{try{const d=await api('identity_create',{displayName:$('idName').value.trim(),nature:$('idNature').value,frontEnabled:$('idFront').checked,backEnabled:$('idBack').checked,task:$('idTask').value.trim()});const r=d.result||{};$('idResult').innerHTML=`<div class="drawerItem"><strong>${esc(r.setkaId||r.setka_id||r.identityRef||'ID создан')}</strong><small>Персональный ключ показывается один раз</small><div style="margin-top:8px;word-break:break-all">${esc(d.personalKey||'')}</div></div>`}catch(e){$('idResult').innerHTML=`<div class="errorBox">${esc(e.message)}</div>`}}}
function openComputer(){$('computer').classList.add('open')}
function closeComputer(){$('computer').classList.remove('open')}
function appendChat(kind,text){const b=document.createElement('div');b.className=`bubble ${kind}`;b.textContent=text;$('chat').appendChild(b);$('chat').scrollTop=$('chat').scrollHeight}
function answerText(d){const x=d.result??d;if(typeof x==='string')return x;return x.response||x.answer||x.message||bestText(x)}
async function sendComputer(msg){msg=String(msg||'').trim();if(!msg)return;appendChat('user',msg);$('computerInput').value='';try{const d=await api('computer_chat',{message:msg});appendChat('bot',answerText(d))}catch(e){appendChat('bot','Ошибка: '+e.message)}}
async function login(){const setkaId=$('loginId').value.trim().toUpperCase(),presidentKey=$('loginKey').value.trim();if(!setkaId||!presidentKey)return;try{const d=await post(AUTH,'president_login',{setkaId,presidentKey},false);setToken(d.sessionToken);hideLogin();await init()}catch(e){$('loginError').textContent=e.message}}
async function init(){renderSidebar();renderHome();if(!token())return showLogin();try{const d=await api('versions');const w=d.manifest?.pointers?.working||d.manifest?.working||d.manifest?.version||'WORKING';$('workingVersion').textContent=`${w} · WORKING`;hideLogin()}catch(e){if(String(e.message).includes('Президент'))showLogin();else toast(e.message)}}
$('backBtn').onclick=renderHome;$('search').oninput=()=>currentData&&renderModule(currentData);$('pinsBtn').onclick=openPins;$('pencilBtn').onclick=openTraces;$('mailBtn').onclick=openMail;$('idBtn').onclick=openId;$('refreshBtn').onclick=()=>current==='HOME'?init():openModule(current);$('drawerClose').onclick=closeDrawer;$('computerFab').onclick=openComputer;$('computerClose').onclick=closeComputer;$('computerForm').onsubmit=e=>{e.preventDefault();sendComputer($('computerInput').value)};$('loginBtn').onclick=login;$('loginKey').addEventListener('keydown',e=>{if(e.key==='Enter')login()});
init();
})();