(()=>{
'use strict';
const LABELS={
 summary:'Описание',surface:'Поверхность',version:'Версия',event_no:'Номер события',actor_kind:'Кто действовал',entity_ref:'Сущность',event_type:'Тип события',source_key:'Источник',entity_type:'Тип сущности',occurred_at:'Когда произошло',recorded_at:'Когда записано',created_at:'Создано',updated_at:'Обновлено',generated_at:'Сформировано',prepared_at:'Подготовлено',admitted_at:'Допущено',metadata:'Дополнительные сведения',patternId:'Паттерн',pattern_id:'Паттерн',synthetic:'Синтетик',state:'Состояние',status:'Статус',stage:'Этап',kind:'Тип',role:'Роль',role_ref:'Роль',position_ref:'Должность',ship_code:'Корабль',parent_ship_code:'Родительский корабль',owner_identity_ref:'Владелец',ip_owner_identity_ref:'Владелец интеллектуальной собственности',operator_identity_refs:'Операторы',display_name_ru:'Название',computer_key:'Бортовой компьютер',lineage:'Происхождение',setka_id:'SETKA ID',identity_ref:'SETKA ID',local_identity_ref:'Локальный ID',mission_ref:'Миссия',mission_code:'Код миссии',experiment_code:'Код эксперимента',experiment_ref:'Эксперимент',candidate_code:'Кандидат',report_ref:'Рапорт',pin_code:'PIN',command_code:'Команда',commandCode:'Команда',source_ref:'Источник',scope_ref:'Контур',sector_ref:'Отсек',title:'Название',title_ru:'Название',name:'Имя',message:'Сообщение',action:'Действие',result:'Результат',reason:'Причина',payload:'Данные',context:'Контекст',root:'Корневой',fractalOrigin:'Фрактальное происхождение',detached_at:'Отделён',enabled:'Включено',active:'Активно',front_enabled:'Доступ к фронту',back_enabled:'Доступ к бэку',event_category:'Категория события',response:'Ответ',answer:'Ответ',task:'Задача',duty:'Обязанность',description:'Описание',notes:'Примечания',source:'Источник',key:'Ключ',id:'ID'
};
const VALUES={
 synthetic:'Синтетик',human:'Человек',president:'Президент',operator:'Оператор',FRONT:'Фронт',BACK:'Бэк',front:'Фронт',back:'Бэк',login:'Вход',logout:'Выход',active:'Активно',inactive:'Неактивно',open:'Открыто',closed:'Закрыто',pending:'Ожидает',completed:'Завершено',done:'Готово',approved:'Одобрено',rejected:'Отклонено',working:'В работе',true:'Да',false:'Нет',browser_runner:'Браузерный исполнитель',system:'Система',user:'Пользователь',assistant:'Синтетик',READY:'Готово',PASS:'Пройдено',FAIL:'Ошибка',SUCCEEDED:'Выполнено',FAILED:'Ошибка',NULL:'—',null:'—'
};
const PHRASES={
 'LIVE BACKEND':'ЖИВЫЕ ДАННЫЕ','LIVE backend':'живые данные','Открыт живой backend':'Данные подключены','Полная запись из живого backend':'Полная карточка из системы','Capability / Command Bus':'Возможности / Шина команд','Neural runs':'Нейронные запуски','Runtime sessions':'Сеансы работы','Runtime admissions':'Допуски к работе','Wake signals':'Сигналы пробуждения','Interwake handoffs':'Передачи между пробуждениями','Interwake memory':'Память между пробуждениями','Action tapes':'Ленты действий','Automation opportunities':'Возможности автоматизации','Resource pools':'Пулы ресурсов','Resource snapshot':'Состояние ресурсов','Ghost Fleet':'Теневой флот','Ghost Fleet runs':'Запуски теневого флота','Ghost G2 events':'События Ghost G2','Ghost G2 history':'История Ghost G2','Ghost decisions':'Решения теневого флота','Pocket Core experiments':'Эксперименты Pocket Core','Crown experiments':'Эксперименты Crown','Front-доступ':'Доступ к фронту','Back-доступ':'Доступ к бэку','backend':'система'
};
function keyLabel(k){if(LABELS[k])return LABELS[k];const parts=String(k).split('_');const tok={event:'событие',type:'тип',source:'источник',entity:'сущность',actor:'участник',kind:'тип',created:'создано',updated:'обновлено',recorded:'записано',occurred:'произошло',generated:'сформировано',admitted:'допущено',at:'время',ref:'ссылка',code:'код',ship:'корабль',mission:'миссия',experiment:'эксперимент',candidate:'кандидат',report:'рапорт',command:'команда',identity:'ID',local:'локальный',position:'должность',role:'роль',state:'состояние',status:'статус',stage:'этап',scope:'контур',sector:'отсек',owner:'владелец',parent:'родительский',display:'отображаемое',name:'имя',title:'название',message:'сообщение',reason:'причина',result:'результат',action:'действие',summary:'описание',metadata:'сведения',version:'версия',surface:'поверхность',number:'номер',count:'количество',current:'текущее'};const out=parts.map(p=>tok[p]||p).join(' ');return out.charAt(0).toUpperCase()+out.slice(1)}
function valueLabel(v){if(v==null)return'—';const s=String(v);if(Object.prototype.hasOwnProperty.call(VALUES,s))return VALUES[s];if(/^\d{4}-\d{2}-\d{2}T/.test(s)){const d=new Date(s);if(!Number.isNaN(d.getTime()))return d.toLocaleString('ru-RU',{dateStyle:'medium',timeStyle:'medium'})}return s}
function translateMeta(el){let t=el.textContent||'';t=t.split(' · ').map(part=>{const m=part.match(/^([A-Za-z0-9_]+):\s*(.*)$/);if(!m)return valueLabel(part);return `${keyLabel(m[1])}: ${valueLabel(m[2])}`}).join(' · ');el.textContent=t}
function humanObject(obj,depth=0){if(depth>4)return document.createTextNode('См. технические данные ниже');const wrap=document.createElement('div');wrap.className='ruObject';if(Array.isArray(obj)){if(!obj.length){wrap.textContent='Нет данных';return wrap}obj.forEach((v,i)=>{const row=document.createElement('div');row.className='ruPair';const k=document.createElement('div');k.className='ruKey';k.textContent=`Элемент ${i+1}`;const val=document.createElement('div');val.className='ruVal';if(v&&typeof v==='object')val.appendChild(humanObject(v,depth+1));else val.textContent=valueLabel(v);row.append(k,val);wrap.appendChild(row)});return wrap}Object.entries(obj||{}).forEach(([kk,v])=>{const row=document.createElement('div');row.className='ruPair';const k=document.createElement('div');k.className='ruKey';k.textContent=keyLabel(kk);const val=document.createElement('div');val.className='ruVal';if(v&&typeof v==='object')val.appendChild(humanObject(v,depth+1));else val.textContent=valueLabel(v);row.append(k,val);wrap.appendChild(row)});return wrap}
function convertPre(pre){if(pre.dataset.ruDone)return;pre.dataset.ruDone='1';let obj;try{obj=JSON.parse(pre.textContent)}catch{return}const human=humanObject(obj);const details=document.createElement('details');details.className='techDetails';const summary=document.createElement('summary');summary.textContent='Технические данные для разработчика';details.append(summary,pre.cloneNode(true));pre.replaceWith(human,details)}
function translateModal(root){root.querySelectorAll('#modalBody div').forEach(el=>{const t=(el.textContent||'').trim();if(el.children.length===0&&/^[A-Za-z][A-Za-z0-9_]*$/.test(t)&&t.length<80){if(LABELS[t]||t.includes('_'))el.textContent=keyLabel(t)}else if(el.children.length===0&&Object.prototype.hasOwnProperty.call(VALUES,t)){el.textContent=valueLabel(t)}});root.querySelectorAll('#modalBody pre').forEach(convertPre);root.querySelectorAll('#modalBody .eyebrow').forEach(el=>{if((el.textContent||'').startsWith('foundation.')){el.textContent='Источник данных';el.title='Технический источник: '+(el.textContent||'')}})}
function translateGeneral(root){root.querySelectorAll('.chip,.meta').forEach(el=>{if(!el.dataset.ruDone){el.dataset.ruDone='1';translateMeta(el)}});root.querySelectorAll('.sourceHead span').forEach(el=>{const t=el.textContent||'';if(t.includes('foundation.')){el.textContent=t.split('·')[0].trim()||'Живые данные'}});root.querySelectorAll('*').forEach(el=>{if(el.children.length===0){let t=el.textContent||'';for(const [a,b] of Object.entries(PHRASES))if(t.includes(a))t=t.split(a).join(b);if(t!==el.textContent)el.textContent=t}})}
function apply(root=document){translateGeneral(root);translateModal(root)}
const style=document.createElement('style');style.textContent='.ruObject{display:flex;flex-direction:column;gap:4px}.ruPair{padding:9px 0;border-bottom:1px solid #182530}.ruKey{font-size:11px;letter-spacing:.04em;color:#7f93a3;margin-bottom:4px}.ruVal{font-size:15px;color:#e3ebf0;word-break:break-word}.techDetails{margin-top:12px;border:1px solid #1d2b36;border-radius:10px;padding:10px;background:#070c11}.techDetails summary{cursor:pointer;color:#7f93a3;font-size:12px}.techDetails pre{margin-top:10px}.sourceHead span{max-width:45%;text-align:right}';document.head.appendChild(style);
const obs=new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes)if(n.nodeType===1)apply(n)});obs.observe(document.body,{childList:true,subtree:true});apply(document);
})();
