// @ts-nocheck
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8"};
const J=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H});
const T=(v:any,m=500)=>String(v??"").trim().slice(0,m),N=(v:any,f=0)=>Number.isFinite(Number(v))?Number(v):f,clamp=(v:number,a:number,b:number)=>Math.min(b,Math.max(a,v));
const CONSENT_VERSION="research-v2-2026-09-17";
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function adminAuth(k:string){if(!k)return false;const q=await db.from("admin_keys").select("id").eq("key_hash",await sha(T(k,300))).eq("active",true).maybeSingle();if(q.error)throw q.error;return!!q.data}
async function auth(token:string){if(!token)return null;const h=await sha(token),now=new Date().toISOString();const q=await db.from("prototype_v40_tester_sessions").select("id,tester_id,expires_at").eq("token_hash",h).is("revoked_at",null).gt("expires_at",now).maybeSingle();if(q.error)throw q.error;if(!q.data)return null;const a=await db.from("prototype_v40_tester_accounts").select("research_subject_id,active,consent_version,consent_at").eq("tester_id",q.data.tester_id).maybeSingle();if(a.error)throw a.error;if(!a.data?.active)return null;return{...q.data,researchSubjectId:a.data.research_subject_id,consentAt:a.data.consent_at||null,consented:!!(a.data.consent_at&&a.data.consent_version===CONSENT_VERSION)}}
function config(c:any){const x=c&&typeof c==="object"&&!Array.isArray(c)?c:{},o:any={};const pid=T(x.patternId||x.baseId,100);if(pid)o.patternId=pid;for(const k of ["numTentacles","tentacleLength","baseRadius","movementSpeed","colorSpeed","circleSize","lineWeight","segmentStep","colorModeIndex","v1","numShapes","angleSpeed","tSpeed","backgroundAlpha","pointSize","zoom","numLayers","ringSpacing","waveSpeed","waveAmplitude","glitchOffset","ringAlpha","strokeW","baseLen","pulseSpd","pulseAmp","branches","layers","hueRate","pulseSpeed","maxDepth","levelSpeedRatio","firstLevelFactor","numRings","baseSpacing","angleStep","spacing","numPoints","amplitude","eyeSeparation","stereoAngle","glowStrength","timeSpeed"]){if(Number.isFinite(Number(x[k])))o[k]=Number(x[k])}for(const k of ["glitchEnabled","invertDirection"]){if(x[k]!=null)o[k]=!!x[k]}if(Array.isArray(x.v1History))o.v1History=x.v1History.map(Number).filter(Number.isFinite).slice(-64);return o}
function versionFor(id:string,v:any){if(Number.isFinite(Number(v)))return clamp(Math.round(Number(v)),1,999);if(id==="fish-wave")return 35;if(id==="rgb-glitch-rings")return 36;return 1}
function median(a:number[]){if(!a.length)return null;const s=a.slice().sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2}
function agg(rows:any[],keyFn:(r:any)=>string,metaFn:(r:any)=>any){const map=new Map<string,any>();for(const r of rows){const k=keyFn(r);if(!k)continue;let g=map.get(k);if(!g){g={...metaFn(r),subjects:new Set(),rows:0,totalMs:0,durations:[],saves:0,outcomeWeight:0,stateDeltaWeighted:0,stateDeltaWeight:0,stateUpWeight:0,stateDownWeight:0,stateSameWeight:0,helped0:0,helped1:0,helped2:0,pulseWeighted:0,pulseSamples:0,lastAt:null};map.set(k,g)}g.subjects.add(String(r.research_subject_id));g.rows++;const ms=Math.max(0,N(r.duration_ms));g.totalMs+=ms;g.durations.push(ms);if(r.saved)g.saves++;const w=Number.isFinite(Number(r.participation_weight))?clamp(Number(r.participation_weight),0,1):0;if(r.pre_state!=null&&r.post_state!=null&&w>0){const d=N(r.post_state)-N(r.pre_state);g.outcomeWeight+=w;g.stateDeltaWeighted+=d*w;g.stateDeltaWeight+=w;if(d>0)g.stateUpWeight+=w;else if(d<0)g.stateDownWeight+=w;else g.stateSameWeight+=w}if(r.helped!=null&&w>0){if(Number(r.helped)===0)g.helped0+=w;if(Number(r.helped)===1)g.helped1+=w;if(Number(r.helped)===2)g.helped2+=w}if(Number(r.heart_rate_avg)>0&&Number(r.heart_rate_samples)>0){g.pulseWeighted+=Number(r.heart_rate_avg)*Number(r.heart_rate_samples);g.pulseSamples+=Number(r.heart_rate_samples)}const t=r.updated_at||r.created_at;if(t&&(!g.lastAt||Date.parse(t)>Date.parse(g.lastAt)))g.lastAt=t}
return[...map.values()].map(g=>({patternId:g.patternId,patternVersion:g.patternVersion||1,configKey:g.configKey||null,config:g.config||{},uniqueParticipants:g.subjects.size,contributions:g.rows,totalDurationMs:g.totalMs,medianDurationMs:median(g.durations),saves:g.saves,outcomeWeight:Number(g.outcomeWeight.toFixed(3)),avgStateDelta:g.stateDeltaWeight?Number((g.stateDeltaWeighted/g.stateDeltaWeight).toFixed(3)):null,stateShift:{up:Number(g.stateUpWeight.toFixed(3)),down:Number(g.stateDownWeight.toFixed(3)),same:Number(g.stateSameWeight.toFixed(3))},helped:{no:Number(g.helped0.toFixed(3)),partly:Number(g.helped1.toFixed(3)),yes:Number(g.helped2.toFixed(3))},heartRateAvg:g.pulseSamples?Number((g.pulseWeighted/g.pulseSamples).toFixed(1)):null,heartRateSamples:g.pulseSamples,lastContributionAt:g.lastAt}))}
async function publicNoteCounts(){const q=await db.from("prototype_v36_public_notes").select("config_key,pattern_id").eq("is_public",true).eq("moderation_status","published");if(q.error)throw q.error;const byConfig=new Map(),byPattern=new Map();for(const x of q.data||[]){if(x.config_key)byConfig.set(x.config_key,(byConfig.get(x.config_key)||0)+1);if(x.pattern_id)byPattern.set(x.pattern_id,(byPattern.get(x.pattern_id)||0)+1)}return{byConfig,byPattern}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return J({error:"method_not_allowed"},405);try{const b=await req.json().catch(()=>({})),action=T(b.action,50);
 if(action==="contribute"){
   const s=await auth(T(b.sessionToken,200));if(!s)return J({error:"auth_required"},401);if(!s.consented)return J({error:"consent_required",requiredConsentVersion:CONSENT_VERSION},403);const items=Array.isArray(b.contributions)?b.contributions.slice(0,400):[];let accepted=0;const consentTs=Date.parse(s.consentAt||"");for(const x of items){const startedTs=Date.parse(T(x.sessionStartedAt,80));if(!Number.isFinite(consentTs)||!Number.isFinite(startedTs)||startedTs<consentTs)continue;const pid=T(x.patternId||x.config?.patternId,100),ck=T(x.configKey,800),clientKey=T(x.contributionKey,200);if(!pid||!ck||!clientKey)continue;const rawPhase=T(x.phase,40),phase=["measured","after_feedback","exploration"].includes(rawPhase)?rawPhase:null,pre=x.preState==null?null:clamp(Math.round(N(x.preState)),1,5),post=x.postState==null?null:clamp(Math.round(N(x.postState)),1,5),help=x.helped==null?null:clamp(Math.round(N(x.helped)),0,2),day=["night","morning","day","evening"].includes(T(x.daypart,20))?T(x.daypart,20):null,hr=x.heartRate&&typeof x.heartRate==="object"?x.heartRate:{},group=T(x.outcomeGroup,200),row={research_subject_id:s.researchSubjectId,contribution_key_hash:await sha(`${s.researchSubjectId}|${clientKey}`),outcome_group_hash:group?await sha(`${s.researchSubjectId}|${group}`):null,participation_weight:Number.isFinite(Number(x.participationWeight))?clamp(Number(x.participationWeight),0,1):null,pattern_id:pid,pattern_version:versionFor(pid,x.patternVersion),config_key:ck,config:config(x.config),phase,request_key:T(x.requestKey,80)||null,duration_ms:Math.max(0,Math.min(14400000,Math.round(N(x.durationMs)))),saved:!!x.saved,pre_state:pre,post_state:post,helped:help,completed:!!x.completed,daypart:day,heart_rate_avg:Number.isFinite(Number(hr.avg))?clamp(Number(hr.avg),20,260):null,heart_rate_min:Number.isFinite(Number(hr.min))?clamp(Number(hr.min),20,260):null,heart_rate_max:Number.isFinite(Number(hr.max))?clamp(Number(hr.max),20,260):null,heart_rate_samples:Number.isFinite(Number(hr.samples))?clamp(Math.round(Number(hr.samples)),0,100000):0,updated_at:new Date().toISOString()};const q=await db.from("prototype_v40_pattern_contributions").upsert(row,{onConflict:"research_subject_id,contribution_key_hash"});if(q.error)throw q.error;accepted++}return J({ok:true,accepted,privacy:{personalCorpus:"private-account-only",storedFields:["pattern/config","duration","phase","request category","outcome summary","save","optional pulse summary"],excluded:["testerId","deviceId","sessionId","note text","raw timeline"]}})
 }
 if(action==="my-status"){
   const s=await auth(T(b.sessionToken,200));if(!s)return J({error:"auth_required"},401);const q=await db.from("prototype_v40_pattern_contributions").select("pattern_id,updated_at").eq("research_subject_id",s.researchSubjectId).order("updated_at",{ascending:false}).limit(5000);if(q.error)throw q.error;const rows=q.data||[];return J({ok:true,contributions:rows.length,patterns:new Set(rows.map((x:any)=>x.pattern_id)).size,lastContributionAt:rows[0]?.updated_at||null,consented:s.consented,privacyMode:"private-account-corpus"})
 }
 if(action==="admin-feed"){
   if(!(await adminAuth(T(b.adminKey,300))))return J({error:"invalid_admin_key"},403);const q=await db.from("prototype_v40_pattern_contributions").select("research_subject_id,pattern_id,pattern_version,config_key,config,phase,request_key,duration_ms,saved,pre_state,post_state,helped,completed,daypart,heart_rate_avg,heart_rate_samples,participation_weight,created_at,updated_at").order("updated_at",{ascending:false}).limit(50000);if(q.error)throw q.error;const rows=q.data||[],notes=await publicNoteCounts();let configs=agg(rows,r=>String(r.config_key||""),r=>({patternId:r.pattern_id,patternVersion:r.pattern_version,configKey:r.config_key,config:r.config||{}}));let patterns=agg(rows,r=>String(r.pattern_id||""),r=>({patternId:r.pattern_id,patternVersion:r.pattern_version,configKey:null,config:{}}));configs=configs.map(x=>({...x,publicNotes:notes.byConfig.get(x.configKey)||0}));patterns=patterns.map(x=>({...x,publicNotes:notes.byPattern.get(x.patternId)||0,configCount:configs.filter(c=>c.patternId===x.patternId).length}));patterns.sort((a,b)=>b.uniqueParticipants-a.uniqueParticipants||b.totalDurationMs-a.totalDurationMs);configs.sort((a,b)=>b.uniqueParticipants-a.uniqueParticipants||b.totalDurationMs-a.totalDurationMs);
   const curQ=await db.from("prototype_v41_service_metrics_current").select("*").maybeSingle();if(curQ.error)throw curQ.error;
   const curP=await db.from("prototype_v41_pattern_metrics_current").select("*").order("exposures",{ascending:false}).order("likes",{ascending:false});if(curP.error)throw curP.error;
   const sm=curQ.data||{},today=new Date().toISOString().slice(0,10),now=new Date().toISOString();
   const snap=await db.from("prototype_v40_service_metric_snapshots").upsert({day:today,participants:N(sm.connected_accounts),connected_testers:N(sm.connected_accounts),sessions:N(sm.sessions),exposures:N(sm.exposures),patterns:N(sm.patterns),configurations:N(sm.saved_configurations),saves:N(sm.configuration_saves),published_notes:notes.total||0,active_participants_30d:N(sm.active_accounts_30d),updated_at:now},{onConflict:"day"});if(snap.error)throw snap.error;
   if((curP.data||[]).length){const pr=(curP.data||[]).map((x:any)=>({day:today,pattern_id:x.pattern_id,participants:N(x.viewing_accounts),sessions:N(x.sessions),exposures:N(x.exposures),configurations:N(x.saved_configurations),saves:N(x.likes),duration_ms:N(x.duration_ms),published_notes:notes.byPattern.get(x.pattern_id)||0,updated_at:now}));const pu=await db.from("prototype_v40_pattern_metric_snapshots").upsert(pr,{onConflict:"day,pattern_id"});if(pu.error)throw pu.error}
   const sh=await db.from("prototype_v40_service_metric_snapshots").select("day,participants,connected_testers,sessions,exposures,patterns,configurations,saves,published_notes,active_participants_30d,updated_at").order("day",{ascending:false}).limit(90);if(sh.error)throw sh.error;
   const patternHistory=(curP.data||[]).map((x:any)=>({day:today,pattern_id:x.pattern_id,participants:N(x.viewing_accounts),viewing_accounts:N(x.viewing_accounts),sessions:N(x.sessions),exposures:N(x.exposures),configurations:N(x.saved_configurations),saved_configurations:N(x.saved_configurations),configuration_saves:N(x.configuration_saves),saves:N(x.likes),likes:N(x.likes),duration_ms:N(x.duration_ms),published_notes:notes.byPattern.get(x.pattern_id)||0,updated_at:now}));
   const serviceMetrics={participants:N(sm.connected_accounts),connected_accounts:N(sm.connected_accounts),connected_testers:N(sm.connected_accounts),sessions:N(sm.sessions),exposures:N(sm.exposures),patterns:N(sm.patterns),configurations:N(sm.saved_configurations),saved_configurations:N(sm.saved_configurations),configuration_saves:N(sm.configuration_saves),saves:N(sm.configuration_saves),active_participants_30d:N(sm.active_accounts_30d),active_accounts_30d:N(sm.active_accounts_30d),published_notes:notes.total||0};
   return J({ok:true,patterns,configs,counts:{contributions:rows.length,patterns:patterns.length,configs:configs.length,participants:new Set(rows.map((x:any)=>String(x.research_subject_id))).size},serviceMetrics,serviceHistory:sh.data||[],patternHistory,privacy:{containsDirectIdentity:false,containsTesterId:false,containsDeviceId:false,containsSessionId:false,containsPrivateNotes:false}})
 }
 return J({error:"unknown_action"},400)
}catch(e){console.error(e);return J({error:"server_error",detail:String(e?.message||e)},500)}});