// @ts-nocheck
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const J=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H});
const T=(v:any,m=500)=>String(v??"").trim().slice(0,m);
const N=(v:any,f=0)=>Number.isFinite(Number(v))?Number(v):f;
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function requireAdmin(key:string){if(!key)return false;const q=await db.from("admin_keys").select("id").eq("key_hash",await sha(key)).eq("active",true).maybeSingle();return !q.error&&!!q.data}

const C:any={
 participant:{label:"Участники",icon:"👤",table:"api_verstak_v34_participants_current_v1",id:"participant_key",desc:"Один человек как логическая сущность поверх связанных устройств."},
 device:{label:"Устройства",icon:"📱",table:"prototype_v34_devices",id:"device_id",desc:"Конкретный браузер или установка, производящая телеметрию."},
 visit:{label:"Визиты",icon:"🚪",table:"prototype_v35_visits",id:"visit_id",desc:"Один непрерывный заход в приложение."},
 session:{label:"Сессии",icon:"⏱",table:"prototype_v34_sessions",id:"session_id",desc:"Одна осмысленная исследовательская сессия."},
 pattern:{label:"Паттерны",icon:"◉",table:"api_verstak_v34_patterns_v1",id:"pattern_id",desc:"Базовые визуальные паттерны приложения."},
 config:{label:"Конфигурации",icon:"⚙️",table:"api_verstak_v34_pattern_configs_current_v1",id:"config_key",desc:"Уникальные конфигурации паттернов без размножения одной сущности по метрикам."},
 exposure:{label:"Просмотры паттерна",icon:"👁",table:"prototype_v35_pattern_exposures",id:"exposure_id",desc:"Факт реального времени, когда конкретная конфигурация была видна пользователю."},
 state:{label:"Состояния",icon:"♡",table:"participant_symptoms",id:"id",desc:"Состояния и симптомы, которые отслеживает пользователь."},
 observation:{label:"Измерения состояния",icon:"📍",table:"symptom_checkins",id:"id",desc:"Одна оценка интенсивности состояния в конкретный момент."},
 assessment:{label:"Оценки сессии",icon:"Δ",table:"prototype_v34_sessions",id:"session_id",desc:"Оценка до/после и производная дельта результата сессии."},
 favorite:{label:"Сохранённое",icon:"♥",table:"prototype_v35_favorites",id:"favorite_id",desc:"Постоянная связь пользователя с сохранённой конфигурацией."},
 note:{label:"Заметки",icon:"✎",table:"participant_notes",id:"id",desc:"Пользовательские заметки с контекстом."},
 physiology:{label:"Физиология",icon:"♥︎",table:"physiological_samples",id:"id",desc:"Физиологические наблюдения и их источники."},
 community_config:{label:"Конфигурации сообщества",icon:"◌",table:"community_configs",id:"id",desc:"Опубликованные конфигурации сообщества."},
 community_save:{label:"Сохранения сообщества",icon:"↳",table:"community_saves",id:"config_id",desc:"Связи пользователей с конфигурациями сообщества."},
 raw_event:{label:"Сырые UX-события",icon:"·",table:"prototype_v34_raw_events",id:"event_id",desc:"Временная телеметрия для UX-реконструкции."},
 replay:{label:"Replay / путь",icon:"↻",table:"prototype_v34_replay_digests",id:"replay_key",desc:"Сжатая память пользовательского пути."},
 snapshot:{label:"Снимки",icon:"▣",table:"prototype_v34_snapshots",id:"device_id",desc:"Транспортные снимки состояния для восстановления и совместимости."}
};

async function count(def:any){const r=await db.from(def.table).select("*",{count:"exact",head:true});if(r.error)throw r.error;return r.count||0}
function uid(type:string,row:any){if(type==="config")return `${row.pattern_id||""}::${row.config_key||""}`;if(type==="assessment")return `${row.device_id||""}::${row.session_id||""}`;if(type==="community_save")return `${row.config_id||""}::${row.participant_id||""}`;return String(row?.[C[type].id]??"")}
function norm(type:string,row:any){const id=uid(type,row);let title=id||C[type].label,sub="";
 if(type==="participant"){title=row.label||row.participant_key;sub=`${row.device_count||0} устройств · активность ${row.last_seen_at||"—"}`}
 else if(type==="device"){title=row.label||row.subject_key||row.device_id;sub=`Устройство · ${row.last_seen_at||"—"}`}
 else if(type==="visit"){title=`Визит ${String(row.visit_id||"").slice(0,12)}`;sub=`${row.started_at||""} → ${row.last_seen_at||row.ended_at||""}`}
 else if(type==="session"){title=row.request_key||row.session_type||"Сессия";sub=`${row.completed?"Завершена":"Не завершена"} · ${Math.round(N(row.measured_active_ms)/60000)} мин`}
 else if(type==="pattern"){title=row.title_ru||row.pattern_id;sub=`Паттерн · ${row.pattern_id}`}
 else if(type==="config"){title=`${row.pattern_id||"Паттерн"} · конфигурация`;sub=`${Math.round(N(row.total_ms)/1000)} сек · ${N(row.exposure_count)} просмотров · ${N(row.participant_count)} участн.`}
 else if(type==="exposure"){title=`${row.pattern_id||"Паттерн"} · ${Math.round(N(row.duration_ms)/1000)} сек`;sub=`${row.context||row.session_type||""} · ${row.started_at||""}`}
 else if(type==="state"){title=row.name||row.symptom_key||"Состояние";sub=row.active===false?"Не отслеживается":"Отслеживается"}
 else if(type==="observation"){title=`Интенсивность ${row.intensity??"—"}/10`;sub=`${row.phase||""} · ${row.observed_at||""}`}
 else if(type==="assessment"){const d=row.pre_state==null||row.post_state==null?null:N(row.post_state)-N(row.pre_state);title=`${row.request_key||"Сессия"} · ${d==null?"нет пары до/после":`Δ ${d>0?"+":""}${d}`}`;sub=`До ${row.pre_state??"—"} · после ${row.post_state??"—"} · помогло ${row.helped??"—"}`}
 else if(type==="favorite"){title=`${row.pattern_id||"Паттерн"} · сохранено`;sub=row.saved_at||""}
 else if(type==="note"){title=T(row.note_text,90)||"Заметка";sub=row.observed_at||row.created_at||""}
 else if(type==="physiology"){title=`${row.metric||"Показатель"}: ${row.value??"—"} ${row.unit||""}`;sub=`${row.quality||""} · ${row.observed_at||""}`}
 else if(type==="community_config"){title=`${row.pattern_id||"Паттерн"} · конфигурация сообщества`;sub=row.created_at||""}
 else if(type==="community_save"){title="Сохранение из сообщества";sub=row.created_at||""}
 else if(type==="raw_event"){title=`${row.type||"Событие"} · ${String(row.event_id||"").slice(0,12)}`;sub=row.wall_at||""}
 else if(type==="replay"){title=`${row.kind||"Replay"} · ${String(row.replay_key||"").slice(0,22)}`;sub=`${row.event_count||0} событий · ${Math.round(N(row.duration_ms)/1000)} сек`}
 else if(type==="snapshot"){title=`Снимок ${String(row.device_id||"").slice(0,12)}`;sub=row.captured_at||row.updated_at||""}
 return{id,title,subtitle:sub,raw:row};
}
function orderFor(type:string){if(["participant","device"].includes(type))return["last_seen_at",false];if(["visit","session","exposure","assessment"].includes(type))return["started_at",false];if(type==="raw_event")return["wall_at",false];if(["observation","note","physiology"].includes(type))return["observed_at",false];if(type==="replay")return["started_at",false];if(type==="pattern")return["ordinal",true];if(type==="config")return["total_ms",false];if(type==="favorite")return["saved_at",false];if(["community_config","community_save"].includes(type))return["created_at",false];if(type==="snapshot")return["captured_at",false];return null}
async function list(type:string,limit:number){const def=C[type];if(!def)throw new Error("Неизвестный тип сущности");let q=db.from(def.table).select("*").limit(limit);const o=orderFor(type);if(o)q=q.order(o[0],{ascending:o[1]});const r=await q;if(r.error)throw r.error;return(r.data||[]).map((x:any)=>norm(type,x))}
async function findOne(type:string,id:string){const def=C[type];if(!def)throw new Error("Неизвестный тип сущности");let q=db.from(def.table).select("*");if(type==="config"){const p=id.indexOf("::");q=q.eq("pattern_id",id.slice(0,p)).eq("config_key",id.slice(p+2))}else if(type==="assessment"){const p=id.indexOf("::");q=q.eq("device_id",id.slice(0,p)).eq("session_id",id.slice(p+2))}else if(type==="community_save"){const p=id.indexOf("::");q=q.eq("config_id",id.slice(0,p)).eq("participant_id",id.slice(p+2))}else q=q.eq(def.id,id);const r=await q.maybeSingle();if(r.error)throw r.error;return r.data}
async function add(out:any[],label:string,target:string,q:any){const r=await q.limit(12);if(r.error)return;if(r.data?.length)out.push({label,target,count:r.data.length,items:r.data.map((x:any)=>norm(target,x))})}
async function relations(type:string,row:any){const out:any[]=[];
 if(type==="participant"){const ds=row.device_ids||[];if(ds.length)await Promise.all([add(out,"Устройства","device",db.from("prototype_v34_devices").select("*").in("device_id",ds).order("last_seen_at",{ascending:false})),add(out,"Сессии","session",db.from("prototype_v34_sessions").select("*").in("device_id",ds).order("started_at",{ascending:false})),add(out,"Просмотры паттернов","exposure",db.from("prototype_v35_pattern_exposures").select("*").in("device_id",ds).order("started_at",{ascending:false})),add(out,"Сохранённое","favorite",db.from("prototype_v35_favorites").select("*").in("device_id",ds).order("saved_at",{ascending:false}))])}
 if(type==="device")await Promise.all([add(out,"Участник","participant",db.from("api_verstak_v34_participants_current_v1").select("*").eq("participant_key",row.subject_key||row.device_id)),add(out,"Визиты","visit",db.from("prototype_v35_visits").select("*").eq("device_id",row.device_id).order("started_at",{ascending:false})),add(out,"Сессии","session",db.from("prototype_v34_sessions").select("*").eq("device_id",row.device_id).order("started_at",{ascending:false})),add(out,"Replay","replay",db.from("prototype_v34_replay_digests").select("*").eq("device_id",row.device_id).order("started_at",{ascending:false}))]);
 if(type==="visit")await Promise.all([add(out,"Устройство","device",db.from("prototype_v34_devices").select("*").eq("device_id",row.device_id)),add(out,"Просмотры этого визита","exposure",db.from("prototype_v35_pattern_exposures").select("*").eq("device_id",row.device_id).eq("visit_id",row.visit_id).order("started_at",{ascending:false})),add(out,"Replay визита","replay",db.from("prototype_v34_replay_digests").select("*").eq("device_id",row.device_id).eq("visit_id",row.visit_id).order("started_at",{ascending:false}))]);
 if(type==="session"||type==="assessment")await Promise.all([add(out,"Устройство","device",db.from("prototype_v34_devices").select("*").eq("device_id",row.device_id)),add(out,"Просмотры сессии","exposure",db.from("prototype_v35_pattern_exposures").select("*").eq("device_id",row.device_id).eq("session_id",row.session_id).order("started_at",{ascending:true})),add(out,"Replay сессии","replay",db.from("prototype_v34_replay_digests").select("*").eq("device_id",row.device_id).eq("replay_key",`pv34::${row.device_id}::${row.session_id}`))]);
 if(type==="pattern")await Promise.all([add(out,"Конфигурации","config",db.from("api_verstak_v34_pattern_configs_current_v1").select("*").eq("pattern_id",row.pattern_id).order("total_ms",{ascending:false})),add(out,"Просмотры","exposure",db.from("prototype_v35_pattern_exposures").select("*").eq("pattern_id",row.pattern_id).order("started_at",{ascending:false})),add(out,"Сохранённое","favorite",db.from("prototype_v35_favorites").select("*").eq("pattern_id",row.pattern_id).order("saved_at",{ascending:false})),add(out,"Сообщество","community_config",db.from("community_configs").select("*").eq("pattern_id",row.pattern_id).order("created_at",{ascending:false}))]);
 if(type==="config")await Promise.all([add(out,"Паттерн","pattern",db.from("api_verstak_v34_patterns_v1").select("*").eq("pattern_id",row.pattern_id)),add(out,"Просмотры конфигурации","exposure",db.from("prototype_v35_pattern_exposures").select("*").eq("pattern_id",row.pattern_id).eq("config_key",row.config_key).order("started_at",{ascending:false})),add(out,"Сохранённое","favorite",db.from("prototype_v35_favorites").select("*").eq("pattern_id",row.pattern_id).eq("config_key",row.config_key))]);
 if(type==="exposure")await Promise.all([add(out,"Устройство","device",db.from("prototype_v34_devices").select("*").eq("device_id",row.device_id)),add(out,"Визит","visit",db.from("prototype_v35_visits").select("*").eq("device_id",row.device_id).eq("visit_id",row.visit_id)),...(row.session_id?[add(out,"Сессия","session",db.from("prototype_v34_sessions").select("*").eq("device_id",row.device_id).eq("session_id",row.session_id))]:[]),add(out,"Паттерн","pattern",db.from("api_verstak_v34_patterns_v1").select("*").eq("pattern_id",row.pattern_id)),add(out,"Конфигурация","config",db.from("api_verstak_v34_pattern_configs_current_v1").select("*").eq("pattern_id",row.pattern_id).eq("config_key",row.config_key))]);
 if(type==="state")await add(out,"Измерения состояния","observation",db.from("symptom_checkins").select("*").eq("symptom_id",row.id).order("observed_at",{ascending:false}));
 if(type==="observation")await add(out,"Состояние","state",db.from("participant_symptoms").select("*").eq("id",row.symptom_id));
 if(type==="favorite")await Promise.all([add(out,"Паттерн","pattern",db.from("api_verstak_v34_patterns_v1").select("*").eq("pattern_id",row.pattern_id)),add(out,"Конфигурация","config",db.from("api_verstak_v34_pattern_configs_current_v1").select("*").eq("pattern_id",row.pattern_id).eq("config_key",row.config_key)),add(out,"Просмотры этой конфигурации","exposure",db.from("prototype_v35_pattern_exposures").select("*").eq("device_id",row.device_id).eq("config_key",row.config_key).order("started_at",{ascending:false}))]);
 if(type==="community_config")await Promise.all([add(out,"Паттерн","pattern",db.from("api_verstak_v34_patterns_v1").select("*").eq("pattern_id",row.pattern_id)),add(out,"Сохранения сообщества","community_save",db.from("community_saves").select("*").eq("config_id",row.id).order("created_at",{ascending:false}))]);
 if(type==="community_save")await add(out,"Конфигурация сообщества","community_config",db.from("community_configs").select("*").eq("id",row.config_id));
 if(type==="raw_event")await add(out,"Устройство","device",db.from("prototype_v34_devices").select("*").eq("device_id",row.device_id));
 if(type==="replay")await Promise.all([add(out,"Устройство","device",db.from("prototype_v34_devices").select("*").eq("device_id",row.device_id)),...(row.visit_id?[add(out,"Визит","visit",db.from("prototype_v35_visits").select("*").eq("device_id",row.device_id).eq("visit_id",row.visit_id))]:[])]);
 if(type==="snapshot")await add(out,"Устройство","device",db.from("prototype_v34_devices").select("*").eq("device_id",row.device_id));
 return out;
}
async function calculations(type:string,row:any){
 if(type==="participant"){const ds=row.device_ids||[];if(!ds.length)return{};const r=await db.from("prototype_v35_participant_facts").select("*").in("device_id",ds);const a=r.data||[];return{devices:row.device_count,activeDays:Math.max(0,...a.map((x:any)=>N(x.active_days))),sessions:a.reduce((s:number,x:any)=>s+N(x.session_count),0),patternTimeMinutes:a.reduce((s:number,x:any)=>s+N(x.total_pattern_ms),0)/60000,views:a.reduce((s:number,x:any)=>s+N(x.exposure_count),0),favorites:a.reduce((s:number,x:any)=>s+N(x.favorite_count),0),backtracks:a.reduce((s:number,x:any)=>s+N(x.backtracks),0)}}
 if(type==="pattern"){const r=await db.from("prototype_v35_pattern_facts").select("*").eq("pattern_id",row.pattern_id);const a=r.data||[];return{participants:a.length,totalMinutes:a.reduce((s:number,x:any)=>s+N(x.total_ms),0)/60000,measuredMinutes:a.reduce((s:number,x:any)=>s+N(x.measured_ms),0)/60000,views:a.reduce((s:number,x:any)=>s+N(x.exposure_count),0),outcomeSessions:a.reduce((s:number,x:any)=>s+N(x.outcome_session_count),0),improvedSessions:a.reduce((s:number,x:any)=>s+N(x.improved_outcome_sessions),0)}}
 if(type==="config")return{participants:row.participant_count,totalMinutes:N(row.total_ms)/60000,measuredMinutes:N(row.measured_ms)/60000,freeMinutes:N(row.free_ms)/60000,views:row.exposure_count,sessions:row.session_count,outcomeSessions:row.outcome_session_count,weightedDelta:N(row.outcome_weight_sum)?N(row.outcome_weighted_delta_sum)/N(row.outcome_weight_sum):null,favorite:!!row.favorite_any,notes:row.note_count};
 if(type==="session"||type==="assessment")return{delta:row.pre_state==null||row.post_state==null?null:N(row.post_state)-N(row.pre_state),completed:!!row.completed,measuredMinutes:N(row.measured_active_ms)/60000,afterFeedbackMinutes:N(row.after_feedback_active_ms)/60000,helped:row.helped};
 if(type==="state"){const r=await db.from("symptom_checkins").select("intensity").eq("symptom_id",row.id);const a=(r.data||[]).map((x:any)=>N(x.intensity));return{measurements:a.length,average:a.length?a.reduce((x:number,y:number)=>x+y,0)/a.length:null,min:a.length?Math.min(...a):null,max:a.length?Math.max(...a):null}}
 if(type==="exposure")return{seconds:N(row.duration_ms)/1000,context:row.context,sessionType:row.session_type};
 if(type==="replay")return{seconds:N(row.duration_ms)/1000,events:N(row.event_count),pinned:!!row.pinned,rawUntil:row.raw_until,compactedAt:row.compacted_at};
 return null;
}
async function overview(){const entries=Object.entries(C);const pairs=await Promise.all(entries.map(async([k,d]:any)=>[k,await count(d)]));const counts=Object.fromEntries(pairs);
 const healthQ=await Promise.all([
  db.from("prototype_v34_sessions").select("device_id").then(async r=>{if(r.error)throw r.error;const ids=[...new Set((r.data||[]).map((x:any)=>x.device_id))];if(!ids.length)return 0;const d=await db.from("prototype_v34_devices").select("device_id").in("device_id",ids);const ok=new Set((d.data||[]).map((x:any)=>x.device_id));return ids.filter(x=>!ok.has(x)).length}),
  db.from("prototype_v35_pattern_exposures").select("device_id,visit_id,session_id,pattern_id").then(async r=>{if(r.error)throw r.error;const rows=r.data||[];const devs=new Set((await db.from("prototype_v34_devices").select("device_id")).data?.map((x:any)=>x.device_id)||[]);const visits=new Set((await db.from("prototype_v35_visits").select("visit_id")).data?.map((x:any)=>x.visit_id)||[]);const sessions=new Set((await db.from("prototype_v34_sessions").select("session_id")).data?.map((x:any)=>x.session_id)||[]);const pats=new Set((await db.from("api_verstak_v34_patterns_v1").select("pattern_id")).data?.map((x:any)=>x.pattern_id)||[]);return{noDevice:rows.filter((x:any)=>!devs.has(x.device_id)).length,noVisit:rows.filter((x:any)=>!visits.has(x.visit_id)).length,noSession:rows.filter((x:any)=>x.session_id&&!sessions.has(x.session_id)).length,unknownPattern:rows.filter((x:any)=>!pats.has(x.pattern_id)).length}}),
  db.from("prototype_v35_participant_facts").select("device_id").then(async r=>{const have=new Set((r.data||[]).map((x:any)=>x.device_id));const all=(await db.from("prototype_v34_devices").select("device_id")).data||[];return all.filter((x:any)=>!have.has(x.device_id)).length}),
  db.from("sessions").select("*",{count:"exact",head:true}).then((r:any)=>r.count||0),db.from("participants").select("*",{count:"exact",head:true}).then((r:any)=>r.count||0)
 ]);
 const health={sessionsWithoutDevice:healthQ[0],exposuresWithoutDevice:healthQ[1].noDevice,exposuresWithoutVisit:healthQ[1].noVisit,exposuresWithoutSession:healthQ[1].noSession,unknownPattern:healthQ[1].unknownPattern,devicesWithoutFacts:healthQ[2],legacySessions:healthQ[3],legacyParticipants:healthQ[4]};
 const rec:any[]=[];if(health.devicesWithoutFacts)rec.push({level:"attention",title:"Не все устройства имеют семантический профиль",why:`Без расчётного профиля: ${health.devicesWithoutFacts}.`,action:"Пересчитать participant facts для свежих или пустых устройств."});if(health.legacySessions||health.legacyParticipants)rec.push({level:"attention",title:"Есть старый параллельный слой исследований",why:`Legacy sessions: ${health.legacySessions}, participants: ${health.legacyParticipants}.`,action:"Не использовать его как вторую истину; держать только для совместимости."});if(!health.sessionsWithoutDevice&&!health.exposuresWithoutDevice&&!health.exposuresWithoutVisit&&!health.exposuresWithoutSession&&!health.unknownPattern)rec.push({level:"good",title:"Главный контур связан",why:"Сессии, визиты, просмотры и паттерны не имеют найденных критических сирот.",action:"Можно переходить к поиску продуктовых и UX-оптимизаций."});if(counts.raw_event===0&&counts.replay>0)rec.push({level:"good",title:"Сырые UX-события уже сжаты",why:`RAW: 0, Replay: ${counts.replay}.`,action:"Путь пользователя сохранён в digest, а сырые точки не занимают постоянную память."});
 return{counts,health,recommendations:rec,catalog:entries.map(([key,d]:any)=>({key,...d,count:counts[key]}))};
}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return J({error:"method_not_allowed"},405);try{const b=await req.json().catch(()=>({}));if(!(await requireAdmin(T(b.adminKey,300))))return J({error:"invalid_admin_key",detail:"Ключ администратора не принят."},403);const a=T(b.action,40);if(a==="overview")return J({ok:true,...await overview()});if(a==="list"){const type=T(b.type,50);return J({ok:true,type,def:C[type],items:await list(type,Math.max(1,Math.min(100,N(b.limit,50))))})}if(a==="inspect"){const type=T(b.type,50),id=T(b.id,1000),row=await findOne(type,id);if(!row)return J({error:"not_found",detail:"Сущность не найдена."},404);return J({ok:true,type,def:C[type],item:norm(type,row),calculations:await calculations(type,row),relations:await relations(type,row)})}return J({error:"unknown_action",detail:"Неизвестное действие."},400)}catch(e){console.error(e);const detail=(e&&typeof e==="object")?(e.message||e.details||e.hint||JSON.stringify(e)):String(e);return J({error:"server_error",detail},500)}});
