// @ts-nocheck
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
const SHIP="SHIP-SETKA-MOTHER", COMPUTER="SETKA-ONBOARD-COMPUTER", PRESIDENT="SETKA-0001-0001";
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store,max-age=0","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-setka-session","Access-Control-Allow-Methods":"POST,OPTIONS","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer"};
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H});
const text=(v:any,m=6000)=>String(v??"").trim().slice(0,m);
const lim=(v:any,d=80,m=250)=>Math.max(1,Math.min(m,Number(v)||d));
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function rpc(name:string,args:any={}){const r=await db.rpc(name,args);if(r.error)throw r.error;return r.data}
async function actor(req:Request,body:any){const tok=text(req.headers.get("x-setka-session")||body.sessionToken,256);if(!tok)return null;const hash=await sha256(tok);const a=await rpc("foundation_session_actor_v018",{p_session_hash:hash}).catch(()=>null);if(!a?.identityId||!a?.president)return null;return {...a,hash}}
const S=(name:string,title:string,order?:string,summary=false,eq?:any[])=>({name,title,order,summary,eq});
const MODULES=[
 {key:"FLEET",icon:"🚀",title:"Флот",subtitle:"Корабли, рождение, Ghost Fleet, обмен и автокран",sources:[S("ship_registry_current_v1","Реестр кораблей",undefined,true),S("ship_nodes","Узлы кораблей",undefined,true),S("ship_birth_candidates","Кандидаты на рождение","created_at",true),S("ship_birth_manifests","Манифесты рождения","created_at"),S("ghost_ship_instances","Ghost Fleet","created_at",true),S("ship_exchange_packets","Обмен между кораблями","created_at"),S("ship_autocrane_state","Автокран · состояние"),S("ship_autocrane_decisions","Автокран · решения","created_at"),S("fractal_branch_mission_profiles","Профили фрактальных веток","created_at"),S("fractal_branch_exchange_events","События обмена веток","created_at")]},
 {key:"EXPERIMENTS",icon:"🧪",title:"Эксперименты",subtitle:"Полигоны, Ghost G2, Crown, pocket core и испытания",sources:[S("ship_pocket_core_experiments","Pocket Core experiments","created_at",true),S("crown_mission_experiments","Crown experiments","created_at",true),S("ghost_ship_instances","Ghost Fleet runs","created_at",true),S("ghost_g2_events","Ghost G2 events","created_at"),S("ghost_g2_events_history_v2","Ghost G2 history"),S("ghost_ship_seen_decisions","Ghost decisions","created_at"),S("polygon_local_transcript_events","Стенограмма полигонов","created_at"),S("entity_candidate_tests","Тесты кандидатов","created_at"),S("synthetic_optimization_scenarios","Optimization scenarios","created_at"),S("synthetic_field_missions","Полевые миссии","prepared_at")]},
 {key:"WORK",icon:"🧭",title:"Мостик и работа",subtitle:"Миссии, задачи, приоритеты и исполнение",sources:[S("mission_cards","Миссии","updated_at",true),S("atomic_tasks","Атомарные задачи","updated_at",true),S("ai_shift_plan_tasks","План задач ИИ","created_at"),S("synthetic_missions","Миссии синтетиков","created_at"),S("synthetic_mission_events","События миссий","created_at"),S("task_completion_coverage_v020","Покрытие завершения задач",undefined,true),S("task_completion_evidence_gate_v020","Evidence gate задач"),S("trace_work_events","Рабочие TRACE-события","created_at"),S("trace_priority_events","Приоритеты TRACE","created_at")]},
 {key:"VERSTAK",icon:"🛠",title:"VERSTAK / проекты",subtitle:"Проекты, отсеки, PIN, Pencil и события верстака",sources:[S("verstak_user_projects","Проекты","updated_at",true),S("verstak_project_compartments","Отсеки проектов","created_at",true),S("verstak_project_identity_bindings","Участники проектов","created_at"),S("verstak_project_positions","Должности проектов","created_at"),S("verstak_ship_events","События VERSTAK","occurred_at",true),S("verstak_ui_pins","UI PIN","created_at",true),S("verstak_pencil_events","Pencil events","created_at"),S("verstak_pin_messages","PIN messages","created_at")]},
 {key:"CREW",icon:"👥",title:"Экипаж",subtitle:"Позиции, занятость, роли, duty и профессиональные карты",sources:[S("ship_scoped_crew_current_v1","Экипаж Материнского",undefined,true,[["ship_code",SHIP]]),S("ship_position_index","Должности",undefined,true),S("ship_position_occupancies","Занятость должностей","created_at"),S("ship_sector_positions_v1","Позиции по секторам"),S("identity_assignments","Назначения identity","created_at"),S("synthetic_duty_current","Текущие обязанности",undefined,true),S("synthetic_professional_cards","Профессиональные карты","created_at"),S("synthetic_current_hierarchy_v1","Иерархия синтетиков",undefined,true),S("synthetic_career_stats","Карьерная статистика")]},
 {key:"SYNTHETICS",icon:"🤖",title:"Синтетики и runtime",subtitle:"Neural runs, пробуждения, handoff, автономия и ресурсы",sources:[S("synthetic_neural_runs","Neural runs","created_at",true),S("synthetic_runtime_sessions","Runtime sessions","created_at",true),S("synthetic_runtime_admissions","Runtime admissions","admitted_at"),S("synthetic_wake_signals","Wake signals","created_at",true),S("synthetic_interwake_handoffs","Interwake handoffs","created_at"),S("synthetic_interwake_memory_packets","Interwake memory","created_at"),S("synthetic_action_tapes","Action tapes","created_at"),S("synthetic_runtime_automation_opportunities_v1","Automation opportunities",undefined,true),S("synthetic_resource_pools","Resource pools","created_at"),S("synthetic_resource_snapshot","Resource snapshot"),S("synthetic_ship_movement_current_v1","Текущее перемещение") ]},
 {key:"KNOWLEDGE",icon:"🧬",title:"Сущности и знания",subtitle:"Единый индекс, позвоночник, отношения, источники и кандидаты",sources:[S("setka_entity_card_v6","Карточки сущностей",undefined,true),S("setka_canonical_spine","Канонический позвоночник",undefined,true),S("setka_entity_graph_edges_v2","Граф сущностей",undefined,true),S("entity_relation_registry_v2","Реестр отношений",undefined,true),S("entity_source_links","Источники сущностей","created_at",true),S("entity_semantic_source_gaps_v1","Semantic source gaps",undefined,true),S("entity_candidate_incubator_active_v1","Активный инкубатор",undefined,true),S("entity_taxonomy_current_v1","Таксономия"),S("entity_who_what_where_when_v1","4W представление"),S("knowledge_capability_transition_current_v1","Knowledge → capability") ]},
 {key:"CAPABILITIES",icon:"⚡",title:"Capability / Command Bus",subtitle:"Каталог команд, запросы, события, gaps и promotion",sources:[S("capability_command_catalog","Каталог capabilities",undefined,true),S("capability_command_current_v1","Текущие команды",undefined,true),S("capability_command_requests","Запросы команд","created_at",true),S("capability_command_events","События Command Bus","created_at"),S("capability_composition_candidates","Composition candidates","created_at"),S("capability_gap_report_v1","Capability gaps",undefined,true),S("capability_portfolio_report_v1","Capability portfolio"),S("capability_promotion_queue_v2","Promotion queue",undefined,true),S("system_capability_library_v1","System capability library") ]},
 {key:"OBSERVATORY",icon:"📡",title:"Обсерватория",subtitle:"Пульс, графы, время, достижения и системная телеметрия",sources:[S("entity_pulse_current_v2","Пульс сущностей",undefined,true),S("system_time_spine_health_v1","Здоровье временного позвоночника",undefined,true),S("achievement_signal_events","Достижения","created_at"),S("entity_family_velocity_v1","Скорость семейств"),S("entity_family_progress_delta_v1","Дельта прогресса"),S("entity_metabolism_current_v1","Метаболизм сущностей"),S("crown_mission_projection_v1","Crown projection"),S("system_report_federation_health_v1","Федерация отчётов") ]},
 {key:"TRANSCRIPT",icon:"🕰",title:"Стенограмма и отчёты",subtitle:"Append-only история, системные отчёты и provenance",sources:[S("system_transcript_events","Системная стенограмма","event_no",true),S("system_reports","Системные отчёты","generated_at",true),S("synthetic_session_reports","Рапорты синтетиков","created_at",true),S("event_provenance_links","Provenance событий","created_at"),S("system_transcript_effective_provenance_v018","Effective provenance"),S("system_transcript_visual_provenance_v018","Visual provenance"),S("project_chat_turns","Project chat turns","created_at"),S("control_events","Control events","created_at") ]},
 {key:"MEMORY",icon:"🧠",title:"Память",subtitle:"Слои памяти, физиология, капсулы, retention и архивирование",sources:[S("memory_layer_registry","Слои памяти","created_at",true),S("memory_layer_summary_v1","Сводка слоёв",undefined,true),S("memory_physiology_current_v2","Физиология памяти",undefined,true),S("memory_retention_registry_v1","Retention registry","created_at"),S("memory_compaction_capsules_v1","Compaction capsules","prepared_at",true),S("ephemeral_memory_archive_manifests_v1","Archive manifests","created_at"),S("ephemeral_memory_archive_rows_v1","Archive rows","created_at"),S("short_term_memory_entries","Short-term memory","created_at"),S("synthetic_memory_capsules","Память синтетиков","created_at"),S("synthetic_self_capsules","Self capsules","created_at") ]},
 {key:"SECURITY",icon:"🛡",title:"Безопасность и guards",subtitle:"Admission, authority, integrity и контроль runtime",sources:[S("canon_guard_events","Canon guards","created_at",true),S("architecture_admissions","Architecture admissions","requested_at",true),S("identity_authority_current_v1","Authority",undefined,true),S("session_hash_admission_health_v1","Session admission health",undefined,true),S("runtime_admission_class_audit_v1","Runtime admission audit",undefined,true),S("entity_integrity_health_v1","Entity integrity",undefined,true),S("synthetic_trusted_gateway_coverage_v1","Trusted gateway coverage"),S("entity_source_coverage_v1","Source coverage"),S("setka_entity_integration_health_v1","Entity integration health") ]},
 {key:"STORAGE",icon:"📦",title:"Контейнеры и архив",subtitle:"Хранилища, cold archive, local transcript archive и recovery evidence",sources:[S("ship_storage_containers","Контейнеры кораблей",undefined,true),S("entity_candidate_incubator_cold_archive_v1","Cold archive",undefined,true),S("ship_local_transcript_archive_manifests_v2","Local transcript manifests","created_at",true),S("ship_local_transcript_archive_events_v2","Local transcript archive events","created_at"),S("ship_local_transcript_distillates_v2","Transcript distillates","created_at"),S("memory_archive_proof_events_v2","Memory archive proofs","created_at"),S("prototype_v34_lossless_archive_state_events_v2","Prototype archive states","created_at") ]},
 {key:"COMMUNICATION",icon:"✉️",title:"Связь и Event Hub",subtitle:"Диалоги, события, ответы, контакты и маршрутизация",sources:[S("ship_computer_dialogue_turns","Диалоги бортового компьютера","created_at",true),S("ship_computer_event_interactions","Event interactions","created_at",true),S("ship_computer_event_receipts","Event receipts","created_at"),S("ship_contact_routes","Маршруты связи","created_at"),S("ship_exchange_packets","Ship exchange packets","created_at"),S("pin_messages","PIN messages","created_at"),S("ship_local_pin_messages","Ship local PIN messages","created_at"),S("synthetic_contact_tree_history","Contact tree history","created_at") ]},
 {key:"GOVERNANCE",icon:"👑",title:"Президент / Governance",subtitle:"Полномочия, решения, режимы, политики и admission",sources:[S("president_session_mode_events","Режимы Президента","created_at",true),S("president_report_policy","Политика рапортов",undefined,true),S("identity_authority_current_v1","Authority",undefined,true),S("authority_command_edges","Цепочки полномочий","created_at"),S("entity_review_stamps","Review stamps","created_at"),S("architecture_admissions","Architecture admissions","requested_at"),S("senior_inspection_seal_events","Senior inspection seals","created_at"),S("control_events","Control events","created_at") ]}
];
const BYKEY=Object.fromEntries(MODULES.map(m=>[m.key,m]));
async function rows(src:any,limit=60){try{let q=db.schema("foundation").from(src.name).select("*");for(const [k,v] of (src.eq||[]))q=q.eq(k,v);if(src.order)q=q.order(src.order,{ascending:false});q=q.limit(limit);const r=await q;if(r.error)throw r.error;return r.data||[]}catch(e){return {__error:String(e?.message||e),__source:`foundation.${src.name}`}}}
async function count(src:any){try{let q=db.schema("foundation").from(src.name).select("*",{count:"exact",head:true});for(const [k,v] of (src.eq||[]))q=q.eq(k,v);const r=await q;if(r.error)throw r.error;return Number(r.count||0)}catch{return null}}
async function one(name:string,eq:any[]=[]){try{let q=db.schema("foundation").from(name).select("*");for(const [k,v] of eq)q=q.eq(k,v);const r=await q.limit(1);if(r.error)throw r.error;return r.data?.[0]||null}catch{return null}}
async function moduleSummaries(){return await Promise.all(MODULES.map(async m=>{const prim=m.sources.filter((s:any)=>s.summary).slice(0,4);const cs=await Promise.all(prim.map((s:any)=>count(s)));return {...m,sources:m.sources.map((s:any)=>({name:s.name,title:s.title})),recordCount:cs.reduce((a:number,b:any)=>a+(Number.isFinite(b)?b:0),0),countedSources:cs.filter((x:any)=>x!==null).length,totalSources:m.sources.length}}))}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return json({error:"method_not_allowed"},405);try{const body=await req.json().catch(()=>({}));const a=await actor(req,body);if(!a)return json({error:"invalid_president_session"},401);const action=text(body.action,80);
 if(action==="bootstrap"){
  const [ship,computer,sectors,mods,quick,inbox,pins,manifest]=await Promise.all([
   one("ship_registry_current_v1",[["ship_code",SHIP]]),one("ship_computers",[["computer_key",COMPUTER]]),rows({name:"ship_sectors",order:"created_at"},80),moduleSummaries(),rpc("ship_computer_quick_actions_v1",{p_actor_setka_id:PRESIDENT,p_computer_key:COMPUTER,p_limit:12}).catch(()=>({actions:[]})),rpc("ship_computer_event_inbox_v1",{p_computer_key:COMPUTER,p_viewer_setka_id:PRESIDENT,p_limit:20,p_only_unread:false,p_min_importance:0}).catch(()=>({events:[]})),rpc("foundation_pin_list_v018",{p_session_hash:a.hash,p_version:"",p_surface:"president"}).catch(()=>({pins:[]})),rpc("foundation_control_manifest").catch(()=>null)
  ]);
  const motherSectors=Array.isArray(sectors)?sectors.filter((s:any)=>s.sector_ref==="SHIP/SETKA"||String(s.sector_ref||"").startsWith("SHIP/SETKA/")):[];
  const crewCount=await count({name:"ship_scoped_crew_current_v1",eq:[["ship_code",SHIP]]});
  const fleetCount=await count({name:"ship_registry_current_v1"});
  const expCount=await count({name:"ship_pocket_core_experiments"});
  return json({ok:true,frontVersion:"MOTHER-PRESIDENT-V2",asOf:new Date().toISOString(),ship,computer,sectors:motherSectors,modules:mods,quickActions:quick?.actions||quick?.items||[],eventInbox:inbox?.events||[],pins:pins?.pins||[],manifest,stats:{crew:crewCount||0,fleet:fleetCount||0,experiments:expCount||0,modules:mods.length}})
 }
 if(action==="module"){
  const key=text(body.key,40).toUpperCase(),m=BYKEY[key];if(!m)return json({error:"unknown_module"},404);const limit=lim(body.limit,60,150);const pairs=await Promise.all(m.sources.map(async(src:any)=>[src.name,{title:src.title,count:await count(src),rows:await rows(src,limit)}]));return json({ok:true,module:{key:m.key,icon:m.icon,title:m.title,subtitle:m.subtitle},sources:Object.fromEntries(pairs)})
 }
 if(action==="computer_chat")return json({ok:true,result:await rpc("ship_computer_human_language_v22",{p_actor_setka_id:PRESIDENT,p_computer_key:COMPUTER,p_message:text(body.message)})});
 if(action==="quick_actions"){const q=await rpc("ship_computer_quick_actions_v1",{p_actor_setka_id:PRESIDENT,p_computer_key:COMPUTER,p_limit:lim(body.limit,12,30)});return json({ok:true,items:q?.actions||q?.items||[]})}
 if(action==="computer_events"){const q=await rpc("ship_computer_event_inbox_v1",{p_computer_key:COMPUTER,p_viewer_setka_id:PRESIDENT,p_limit:lim(body.limit,50,100),p_only_unread:Boolean(body.onlyUnread),p_min_importance:Number(body.minImportance)||0});return json({ok:true,items:q?.events||[]})}
 if(action==="computer_event_reply")return json({ok:true,result:await rpc("ship_computer_event_reply_v1",{p_computer_key:COMPUTER,p_actor_setka_id:PRESIDENT,p_event_key:text(body.eventKey,200),p_input_text:text(body.message),p_payload:body.payload&&typeof body.payload==="object"?body.payload:{}})});
 if(action==="computer_event_mark")return json({ok:true,result:await rpc("ship_computer_event_mark_v1",{p_computer_key:COMPUTER,p_actor_setka_id:PRESIDENT,p_event_key:text(body.eventKey,200),p_state:text(body.state,30)})});
 if(action==="commands")return json({ok:true,items:await rpc("capability_command_available_v1",{p_actor_setka_id:PRESIDENT,p_scope_kind:text(body.scopeKind,30)||"SHIP",p_scope_ref:text(body.scopeRef,200)||SHIP})});
 if(action==="command_submit")return json({ok:true,result:await rpc("capability_command_submit_v1",{p_actor_setka_id:PRESIDENT,p_command_code:text(body.commandCode,120),p_arguments:body.arguments&&typeof body.arguments==="object"?body.arguments:{},p_scope_kind:text(body.scopeKind,30)||"SHIP",p_scope_ref:text(body.scopeRef,200)||SHIP,p_actor_channel:"PRESIDENT_FRONT",p_idempotency_key:text(body.idempotencyKey,160)||crypto.randomUUID(),p_auto_execute:Boolean(body.autoExecute)})});
 if(action==="pins")return json(await rpc("foundation_pin_list_v018",{p_session_hash:a.hash,p_version:text(body.version,40),p_surface:"president"}));
 if(action==="pin_thread")return json(await rpc("foundation_pin_thread_v018",{p_session_hash:a.hash,p_pin_code:text(body.pinCode,40).toUpperCase()}));
 if(action==="pin_message")return json(await rpc("foundation_pin_message_create_v018",{p_session_hash:a.hash,p_pin_code:text(body.pinCode,40).toUpperCase(),p_message:text(body.message)}));
 if(action==="pin_status")return json(await rpc("foundation_pin_status_v018",{p_session_hash:a.hash,p_pin_code:text(body.pinCode,40).toUpperCase(),p_status:text(body.status,30),p_implemented_in_version:text(body.implementedInVersion,40)}));
 if(action==="pin_review")return json(await rpc("foundation_pin_review_v018",{p_session_hash:a.hash,p_pin_code:text(body.pinCode,40).toUpperCase(),p_decision:text(body.decision,20)}));
 if(action==="transcript")return json({ok:true,items:await rpc("foundation_system_transcript_v018",{p_session_hash:a.hash,p_limit:lim(body.limit,250,500),p_before:body.before?text(body.before,80):null})});
 if(action==="traces")return json({ok:true,...await rpc("diamond_trace_list_v2",{p_session_hash:a.hash,p_limit:lim(body.limit,80,100)})});
 if(action==="versions")return json({ok:true,manifest:await rpc("foundation_control_manifest")});
 if(action==="identity_create"){const raw=`KEY-${crypto.randomUUID().replaceAll("-","").slice(0,18).toUpperCase().match(/.{1,6}/g)?.join("-")}`;const out=await rpc("foundation_issue_identity_v018",{p_session_hash:a.hash,p_display_name:text(body.displayName,120),p_secret_hash:await sha256(raw),p_nature:text(body.nature,20)||"human",p_front_enabled:Boolean(body.frontEnabled),p_back_enabled:Boolean(body.backEnabled),p_task:text(body.task,2000)||null,p_personality:text(body.personality,2000)||null});return json({ok:true,result:out,personalKey:raw})}
 if(action==="report_generate")return json({ok:true,result:await rpc("generate_system_report_v1",{p_period_hours:Math.max(1,Number(body.periodHours)||24),p_report_kind:text(body.reportKind,80)||"PRESIDENT_ON_DEMAND",p_request_text:text(body.requestText,4000),p_requested_by_kind:"PRESIDENT",p_requested_by_ref:PRESIDENT,p_actor_setka_id:PRESIDENT})});
 return json({error:"unknown_action"},400)
}catch(e){console.error("setka-mother-president-v3",e);return json({error:"server_error",detail:String(e?.message||e)},500)}});