import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const CORS={
  "Access-Control-Allow-Origin":"*",
  "Access-Control-Allow-Headers":"content-type,x-verstak-access,apikey",
  "Access-Control-Allow-Methods":"POST,OPTIONS",
  "Content-Type":"application/json; charset=utf-8"
};
const json=(body:any,status=200)=>new Response(JSON.stringify(body),{status,headers:CORS});
const clean=(v:any,n=500)=>String(v??"").trim().slice(0,n);
const bytesHex=(b:Uint8Array)=>[...b].map(x=>x.toString(16).padStart(2,"0")).join("");
const hexBytes=(h:string)=>new Uint8Array((h.match(/.{1,2}/g)||[]).map(x=>parseInt(x,16)));
const sha256=async(s:string)=>{const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return bytesHex(new Uint8Array(d));};
const derivePin=async(pin:string,saltHex:string,iterations:number)=>{const raw=await crypto.subtle.importKey("raw",new TextEncoder().encode(pin),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:hexBytes(saltHex),iterations},raw,256);return bytesHex(new Uint8Array(bits));};
const sameHex=(a:string,b:string)=>{if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0;};
const randomHex=(n:number)=>{const b=new Uint8Array(n);crypto.getRandomValues(b);return bytesHex(b)};
const randomToken=()=>{const b=new Uint8Array(32);crypto.getRandomValues(b);return btoa(String.fromCharCode(...b)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")};
const code=(prefix:string)=>`${prefix}-${crypto.randomUUID().replaceAll("-","").slice(0,12).toUpperCase()}`;

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS") return new Response("ok",{headers:CORS});
  if(req.method!=="POST") return json({ok:false,error:"method_not_allowed"},405);
  const url=Deno.env.get("SUPABASE_URL"),svc=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if(!url||!svc) return json({ok:false,error:"server_not_configured"},500);
  const db=createClient(url,svc,{auth:{persistSession:false}});const f=db.schema("foundation"),d=db.schema("diamond");
  const body=await req.json().catch(()=>({}));const action=clean(body.action,80);

  if(action==="login"){
    const setkaId=clean(body.setkaId,64).toUpperCase(),pin=clean(body.pin,16);
    if(!/^SETKA-H-[A-Z0-9]{4}-[A-Z0-9]{4}$/.test(setkaId)||!/^\d{6}$/.test(pin)) return json({ok:false,error:"invalid_credentials"},401);
    let q=db.from("verstak_auth_credentials").select("*").eq("login_setka_id",setkaId).eq("state","ACTIVE");const shipHint=clean(body.shipCode,100);if(shipHint)q=q.eq("ship_code",shipHint);
    const {data:creds,error:ce}=await q.limit(2);if(ce)return json({ok:false,error:"auth_storage_unavailable"},503);if(!creds?.length)return json({ok:false,error:"invalid_credentials"},401);if(creds.length>1&&!shipHint)return json({ok:false,error:"ship_required"},409);
    const cred:any=creds[0];if(cred.locked_until&&Date.parse(cred.locked_until)>Date.now())return json({ok:false,error:"temporarily_locked",retryAfterSeconds:Math.max(1,Math.ceil((Date.parse(cred.locked_until)-Date.now())/1000))},429);
    const derived=await derivePin(pin,cred.pin_salt_hex,Number(cred.pbkdf2_iterations)||120000);
    if(!sameHex(derived,cred.pin_hash_hex)){const attempts=(Number(cred.failed_attempts)||0)+1;const locked=attempts>=5?new Date(Date.now()+10*60*1000).toISOString():null;await db.from("verstak_auth_credentials").update({failed_attempts:attempts,locked_until:locked,last_failed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("identity_id",cred.identity_id).eq("ship_code",cred.ship_code);return json({ok:false,error:locked?"temporarily_locked":"invalid_credentials"},locked?429:401);}
    const {data:ident}=await db.from("verstak_auth_identities").select("setka_id,status").eq("id",cred.identity_id).maybeSingle();if(!ident||ident.status!=="active")return json({ok:false,error:"identity_inactive"},403);
    const token=randomToken(),tokenHash=await sha256(token),expires=new Date(Date.now()+30*24*60*60*1000).toISOString();const {error:se}=await db.from("verstak_auth_sessions").insert({identity_id:cred.identity_id,ship_code:cred.ship_code,session_token_sha256:tokenHash,expires_at:expires,user_agent:clean(req.headers.get("user-agent"),500),created_via:"SETKA_ID_PIN"});if(se)return json({ok:false,error:"session_create_failed"},500);
    await db.from("verstak_auth_credentials").update({failed_attempts:0,locked_until:null,last_login_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("identity_id",cred.identity_id).eq("ship_code",cred.ship_code);
    const {data:inv}=await db.from("verstak_auth_invites").select("display_name_ru").eq("identity_id",cred.identity_id).eq("ship_code",cred.ship_code).eq("state","ACTIVE").order("created_at",{ascending:false}).limit(1).maybeSingle();
    return json({ok:true,accessToken:token,expiresAt:expires,identity:{setkaId:ident.setka_id,displayNameRu:inv?.display_name_ru||"Пользователь"},shipCode:cred.ship_code});
  }

  const access=req.headers.get("x-verstak-access")||"";if(access.length<20)return json({ok:false,error:"access_required"},401);const tokenHash=await sha256(access);
  let actorId="",shipCode="",displayNameRu="",authMode="",sessionId:string|null=null;
  const {data:sess}=await db.from("verstak_auth_sessions").select("session_id,identity_id,ship_code,state,expires_at").eq("session_token_sha256",tokenHash).maybeSingle();
  if(sess&&sess.state==="ACTIVE"&&Date.parse(sess.expires_at)>Date.now()){actorId=sess.identity_id;shipCode=sess.ship_code;authMode="SETKA_ID_PIN";sessionId=sess.session_id;await db.from("verstak_auth_sessions").update({last_used_at:new Date().toISOString()}).eq("session_id",sess.session_id);const {data:inv}=await db.from("verstak_auth_invites").select("display_name_ru").eq("identity_id",actorId).eq("ship_code",shipCode).eq("state","ACTIVE").order("created_at",{ascending:false}).limit(1).maybeSingle();displayNameRu=inv?.display_name_ru||"Пользователь";}
  else{const {data:invite,error:ie}=await db.from("verstak_auth_invites").select("invite_code,identity_id,ship_code,display_name_ru,state,expires_at").eq("token_sha256",tokenHash).maybeSingle();if(ie||!invite||invite.state!=="ACTIVE"||(invite.expires_at&&Date.parse(invite.expires_at)<Date.now()))return json({ok:false,error:"access_denied"},401);actorId=invite.identity_id;shipCode=invite.ship_code;displayNameRu=invite.display_name_ru;authMode="INVITE";await db.from("verstak_auth_invites").update({last_used_at:new Date().toISOString()}).eq("invite_code",invite.invite_code);}
  const {data:ident}=await db.from("verstak_auth_identities").select("setka_id,status").eq("id",actorId).maybeSingle();if(!ident||ident.status!=="active")return json({ok:false,error:"identity_inactive"},403);const setkaId=ident.setka_id;

  if(action==="set_pin"){const pin=clean(body.pin,16);if(!/^\d{6}$/.test(pin))return json({ok:false,error:"pin_must_be_6_digits"},400);const saltHex=randomHex(16),iterations=120000,pinHash=await derivePin(pin,saltHex,iterations);const {error}=await db.rpc("verstak_auth_set_pin_hash_v1",{p_identity_id:actorId,p_ship_code:shipCode,p_setka_id:setkaId,p_salt:saltHex,p_hash:pinHash,p_iterations:iterations});if(error)return json({ok:false,error:"pin_setup_failed",detail:error.message},500);return json({ok:true,setkaId,shipCode,pinConfigured:true});}
  if(action==="logout"){if(sessionId)await db.from("verstak_auth_sessions").update({state:"REVOKED"}).eq("session_id",sessionId);return json({ok:true});}

  const ownProject=async(id:string)=>{const {data}=await f.from("verstak_user_projects").select("*").eq("id",id).eq("ship_code",shipCode).eq("owner_identity_id",actorId).maybeSingle();return data;};
  const ownCompartment=async(id:string,projectId:string)=>{if(!id)return null;const {data}=await f.from("verstak_project_compartments").select("*").eq("id",id).eq("project_id",projectId).maybeSingle();return data;};
  const logEvent=async(projectId:string|null,compartmentId:string|null,eventType:string,objectKind:string,objectRef:string,summary:string,payload:any={})=>{await f.from("verstak_ship_events").insert({ship_code:shipCode,project_id:projectId,compartment_id:compartmentId,actor_identity_id:actorId,actor_kind:"HUMAN",event_type:eventType,object_kind:objectKind,object_ref:objectRef,summary_ru:summary,payload});};
  const queueSolai=async(projectId:string|null,pinCode:string|null,kind:string,sourceRef:string,question:string)=>{await f.from("verstak_solai_queue").insert({ship_code:shipCode,project_id:projectId,pin_code:pinCode,requested_by_identity_id:actorId,request_kind:kind,source_ref:sourceRef,question_ru:clean(question,2000),status:"PENDING"});};

  if(action==="bootstrap"){
    const [{data:ship},{data:projects},{data:events},{data:queue},{data:cred}]=await Promise.all([
      f.from("ship_nodes").select("ship_code,display_name_ru,state,computer_key,parent_ship_code").eq("ship_code",shipCode).maybeSingle(),
      f.from("verstak_user_projects").select("*").eq("ship_code",shipCode).order("created_at",{ascending:true}),
      f.from("verstak_ship_events").select("*").eq("ship_code",shipCode).order("event_no",{ascending:false}).limit(50),
      f.from("verstak_solai_queue").select("id,project_id,pin_code,request_kind,source_ref,question_ru,status,response_ru,response_payload,created_at,responded_at").eq("ship_code",shipCode).order("created_at",{ascending:false}).limit(50),
      db.from("verstak_auth_credentials").select("state").eq("identity_id",actorId).eq("ship_code",shipCode).maybeSingle()
    ]);
    const ids=(projects??[]).map((p:any)=>p.id);let compartments:any[]=[],pins:any[]=[];
    if(ids.length){const [cr,pr]=await Promise.all([f.from("verstak_project_compartments").select("*").in("project_id",ids).order("ordinal"),f.from("verstak_ui_pins").select("*").in("project_id",ids).order("created_at",{ascending:false}).limit(50)]);compartments=cr.data??[];pins=pr.data??[];if(pins.length){const pc=pins.map((x:any)=>x.pin_code);const {data:msgs}=await f.from("verstak_pin_messages").select("*").in("pin_code",pc).order("created_at",{ascending:true});const by=new Map<string,any[]>();for(const m of msgs??[]){if(!by.has(m.pin_code))by.set(m.pin_code,[]);by.get(m.pin_code)!.push(m)};pins=pins.map((p:any)=>({...p,verstak_pin_messages:by.get(p.pin_code)||[]}));}}
    return json({ok:true,identity:{setkaId,displayNameRu},ship,projects:projects??[],compartments,events:events??[],pins,solaiQueue:queue??[],pinConfigured:!!cred,authMode,features:{pin:true,pencil:true,customCompartments:true,boardComputer:true,transcript:true,projectCreation:true,setkaIdPinLogin:true},alpha:true});
  }

  if(action==="create_project"){const title=clean(body.titleRu,120),desc=clean(body.descriptionRu,1200);if(title.length<2)return json({ok:false,error:"project_title_required"},400);const projectCode=code("PROJECT");const {data:p,error}=await f.from("verstak_user_projects").insert({project_code:projectCode,ship_code:shipCode,owner_identity_id:actorId,title_ru:title,description_ru:desc}).select().single();if(error)return json({ok:false,error:"project_create_failed",detail:error.message},500);const {data:comp}=await f.from("verstak_project_compartments").insert({project_id:p.id,compartment_code:code("COMP"),title_ru:"Общее",kind:"GENERAL",purpose_ru:"Стартовый отсек проекта",ordinal:10}).select().single();await logEvent(p.id,comp?.id??null,"PROJECT_CREATED","PROJECT",projectCode,`Создан проект «${title}».`,{projectCode});return json({ok:true,project:p,defaultCompartment:comp});}
  if(action==="create_compartment"){const projectId=clean(body.projectId,80),p=await ownProject(projectId);if(!p)return json({ok:false,error:"project_not_found"},404);const title=clean(body.titleRu,100),purpose=clean(body.purposeRu,500),kind=clean(body.kind,40)||"CUSTOM";if(title.length<2)return json({ok:false,error:"compartment_title_required"},400);const {data:c,error}=await f.from("verstak_project_compartments").insert({project_id:projectId,compartment_code:code("COMP"),title_ru:title,kind,purpose_ru:purpose,ordinal:Number(body.ordinal)||100}).select().single();if(error)return json({ok:false,error:"compartment_create_failed",detail:error.message},500);await logEvent(projectId,c.id,"COMPARTMENT_CREATED","COMPARTMENT",c.compartment_code,`Создан отсек «${title}».`,{kind});return json({ok:true,compartment:c});}
  if(action==="create_pin"){const projectId=clean(body.projectId,80),p=await ownProject(projectId);if(!p)return json({ok:false,error:"project_not_found"},404);const compartmentId=clean(body.compartmentId,80);if(compartmentId&&!(await ownCompartment(compartmentId,projectId)))return json({ok:false,error:"compartment_not_found"},404);const pinCode=code("PIN"),comment=clean(body.commentRu,2000),x=Number(body.xNorm),y=Number(body.yNorm);const row={pin_code:pinCode,project_id:projectId,compartment_id:compartmentId||null,creator_identity_id:actorId,route:clean(body.route,500),screen_key:clean(body.screenKey,120),target_key:clean(body.targetKey,300),target_label:clean(body.targetLabel,300),x_norm:Number.isFinite(x)?Math.max(0,Math.min(1,x)):null,y_norm:Number.isFinite(y)?Math.max(0,Math.min(1,y)):null,viewport:body.viewport&&typeof body.viewport==="object"?body.viewport:{},comment_ru:comment,payload:{source:"VERSTAK_ALPHA_FRONT",userAgent:clean(req.headers.get("user-agent"),300)}};const {data:pin,error}=await f.from("verstak_ui_pins").insert(row).select().single();if(error)return json({ok:false,error:"pin_create_failed",detail:error.message},500);if(comment)await f.from("verstak_pin_messages").insert({pin_code:pinCode,author_identity_id:actorId,author_kind:"HUMAN",message_ru:comment});await logEvent(projectId,compartmentId||null,"PIN_CREATED","PIN",pinCode,`Создан PIN: ${comment||row.target_label||row.target_key||"точка на экране"}.`,{screenKey:row.screen_key,targetKey:row.target_key,xNorm:row.x_norm,yNorm:row.y_norm});await queueSolai(projectId,pinCode,"PIN_REVIEW",pinCode,comment||`Проверь PIN ${pinCode} и помоги тестировщику.`);return json({ok:true,pin,queuedForSolai:true});}
  if(action==="pin_message"){const pinCode=clean(body.pinCode,80),message=clean(body.messageRu,2000);if(message.length<1)return json({ok:false,error:"message_required"},400);const {data:pin}=await f.from("verstak_ui_pins").select("project_id,compartment_id,pin_code").eq("pin_code",pinCode).maybeSingle();if(!pin||!(await ownProject(pin.project_id)))return json({ok:false,error:"pin_not_found"},404);const {data:m}=await f.from("verstak_pin_messages").insert({pin_code:pinCode,author_identity_id:actorId,author_kind:"HUMAN",message_ru:message}).select().single();await queueSolai(pin.project_id,pinCode,"PIN_REVIEW",pinCode,message);await logEvent(pin.project_id,pin.compartment_id,"PIN_MESSAGE","PIN",pinCode,"Добавлено сообщение к PIN.",{});return json({ok:true,message:m,queuedForSolai:true});}
  if(action==="pencil_start"){const projectId=clean(body.projectId,80),p=await ownProject(projectId);if(!p)return json({ok:false,error:"project_not_found"},404);const compartmentId=clean(body.compartmentId,80);if(compartmentId&&!(await ownCompartment(compartmentId,projectId)))return json({ok:false,error:"compartment_not_found"},404);const {data:s,error}=await f.from("verstak_pencil_sessions").insert({project_id:projectId,compartment_id:compartmentId||null,creator_identity_id:actorId,route:clean(body.route,500),screen_key:clean(body.screenKey,120),payload:{capturePolicy:"NO_TEXT_INPUT_VALUES"}}).select().single();if(error)return json({ok:false,error:"pencil_start_failed",detail:error.message},500);await logEvent(projectId,compartmentId||null,"PENCIL_STARTED","PENCIL",s.id,"Карандаш начал запись действий на экране.",{screenKey:s.screen_key});return json({ok:true,session:s});}
  if(action==="pencil_events"){const sessionId=clean(body.sessionId,80);const {data:s}=await f.from("verstak_pencil_sessions").select("*").eq("id",sessionId).maybeSingle();if(!s||s.status!=="RECORDING"||!(await ownProject(s.project_id)))return json({ok:false,error:"pencil_session_not_recording"},409);const events=Array.isArray(body.events)?body.events.slice(0,200):[];if(!events.length)return json({ok:true,accepted:0});const rows=events.map((e:any,i:number)=>{const data:any={};if(e.data&&typeof e.data==="object"){for(const k of ["action","href","checked","selectedIndex","tag","role"]){if(k in e.data)data[k]=e.data[k];}}const x=Number(e.xNorm),y=Number(e.yNorm);return {session_id:sessionId,seq:Number(e.seq)||i+1,event_type:clean(e.eventType,60)||"ACTION",t_ms:Math.max(0,Number(e.tMs)||0),x_norm:Number.isFinite(x)?Math.max(0,Math.min(1,x)):null,y_norm:Number.isFinite(y)?Math.max(0,Math.min(1,y)):null,target_key:clean(e.targetKey,300),target_label:clean(e.targetLabel,300),data};});const {error}=await f.from("verstak_pencil_events").upsert(rows,{onConflict:"session_id,seq",ignoreDuplicates:true});if(error)return json({ok:false,error:"pencil_events_failed",detail:error.message},500);return json({ok:true,accepted:rows.length});}
  if(action==="pencil_finish"){const sessionId=clean(body.sessionId,80),intention=clean(body.intentionRu,2000);const {data:s}=await f.from("verstak_pencil_sessions").select("*").eq("id",sessionId).maybeSingle();if(!s||!(await ownProject(s.project_id)))return json({ok:false,error:"pencil_session_not_found"},404);const {data:fin,error}=await f.from("verstak_pencil_sessions").update({status:"FINISHED",intention_ru:intention,finished_at:new Date().toISOString()}).eq("id",sessionId).eq("status","RECORDING").select().maybeSingle();if(error||!fin)return json({ok:false,error:"pencil_finish_failed"},409);await logEvent(s.project_id,s.compartment_id,"PENCIL_FINISHED","PENCIL",sessionId,`Карандаш завершил запись: ${intention||"без пояснения"}.`,{});await queueSolai(s.project_id,null,"PENCIL_REVIEW",sessionId,intention||`Разбери запись карандаша ${sessionId} и помоги тестировщику.`);return json({ok:true,session:fin,queuedForSolai:true});}
  if(action==="board_query"){const projectId=clean(body.projectId,80);if(projectId&&!(await ownProject(projectId)))return json({ok:false,error:"project_not_found"},404);const q=clean(body.questionRu,2000);if(q.length<2)return json({ok:false,error:"question_required"},400);const source=code("BOARD");await queueSolai(projectId||null,null,"BOARD_QUERY",source,q);await logEvent(projectId||null,null,"BOARD_QUERY","BOARD_QUERY",source,"Вопрос передан Бортовому компьютеру / Солаю.",{question:q});return json({ok:true,sourceRef:source,state:"QUEUED_FOR_SOLAI",messageRu:"Вопрос принят. Системный контур передал его Солаю."});}
  if(action==="health"){const {data:last}=await f.from("verstak_ship_events").select("event_no,occurred_at,event_type").eq("ship_code",shipCode).order("event_no",{ascending:false}).limit(1).maybeSingle();const {count:pending}=await f.from("verstak_solai_queue").select("id",{count:"exact",head:true}).eq("ship_code",shipCode).eq("status","PENDING");return json({ok:true,shipCode,setkaId,state:"GREEN_ALPHA",lastEvent:last??null,pendingSolai:pending??0,serverTime:new Date().toISOString(),authMode});}
  return json({ok:false,error:"unknown_action"},400);
});