// @ts-nocheck
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store,max-age=0","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,authorization,x-setka-session","Access-Control-Allow-Methods":"POST,OPTIONS","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer"};
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H});
const text=(v:any,m=10000)=>String(v??"").trim().slice(0,m);
const num=(v:any,f=0)=>Number.isFinite(Number(v))?Number(v):f;
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function randomToken(bytes=32){const a=new Uint8Array(bytes);crypto.getRandomValues(a);return [...a].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function rpc(name:string,args:Record<string,unknown>){const q=await db.rpc(name,args);if(q.error)throw q.error;return q.data}
async function resolveSession(raw:string){const token=text(raw,256);if(!token)return null;const hash=await sha256(token);const rows=await rpc("diamond_resolve_session",{p_session_hash:hash});const row=Array.isArray(rows)?rows[0]:null;if(!row)return null;const caps=Array.isArray(row.capabilities)?row.capabilities:[];if(!caps.includes("president"))return null;await rpc("diamond_touch_session",{p_session_hash:hash});return {...row,hash,capabilities:caps}}
async function liveSnapshot(){const [participantsQ,exposuresQ,favoritesQ,visitsQ,factsQ,configsQ,patternFactsQ]=await Promise.all([
 db.from("prototype_v35_participant_facts").select("device_id",{count:"exact",head:true}),
 db.from("prototype_v35_pattern_exposures").select("exposure_id",{count:"exact",head:true}),
 db.from("prototype_v35_favorites").select("config_key",{count:"exact",head:true}),
 db.from("prototype_v35_visits").select("visit_id",{count:"exact",head:true}),
 db.from("prototype_v35_participant_facts").select("device_id,total_pattern_ms,session_count,active_days,note_count,favorite_count,exposure_count"),
 db.from("prototype_v35_config_facts").select("config_key",{count:"exact",head:true}),
 db.from("prototype_v35_pattern_facts").select("pattern_id,total_ms,exposure_count,favorite_configs,session_count,outcome_weight_sum,outcome_weighted_delta_sum")
]);for(const q of [participantsQ,exposuresQ,favoritesQ,visitsQ,factsQ,configsQ,patternFactsQ])if(q.error)throw q.error;const people=factsQ.data||[];const pmap=new Map();for(const r of patternFactsQ.data||[]){const x=pmap.get(r.pattern_id)||{patternId:r.pattern_id,totalMs:0,exposures:0,saves:0,sessions:0,weight:0,weightedDelta:0};x.totalMs+=num(r.total_ms);x.exposures+=num(r.exposure_count);x.saves+=num(r.favorite_configs);x.sessions+=num(r.session_count);x.weight+=num(r.outcome_weight_sum);x.weightedDelta+=num(r.outcome_weighted_delta_sum);pmap.set(r.pattern_id,x)}const patterns=[...pmap.values()].map(x=>({...x,associationDelta:x.weight>0?x.weightedDelta/x.weight:null})).sort((a,b)=>b.totalMs-a.totalMs);const totalPatternMs=people.reduce((s,x)=>s+num(x.total_pattern_ms),0);const sessions=people.reduce((s,x)=>s+num(x.session_count),0);const notes=people.reduce((s,x)=>s+num(x.note_count),0);const returners=people.filter(x=>num(x.active_days)>=2).length;return{asOf:new Date().toISOString(),participants:participantsQ.count||0,exposures:exposuresQ.count||0,favorites:favoritesQ.count||0,visits:visitsQ.count||0,configs:configsQ.count||0,sessions,notes,returners,returnRate:people.length?returners/people.length:0,totalPatternMs,patterns}}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return json({error:"method_not_allowed"},405);try{const body=await req.json().catch(()=>({}));const action=text(body.action,80);
 if(action==="login"){const setkaId=text(body.setkaId,80).toUpperCase(),presidentKey=text(body.presidentKey,300);if(!setkaId||!presidentKey)return json({error:"invalid_credentials"},403);const rows=await rpc("diamond_resolve_credentials",{p_setka_id:setkaId,p_secret_hash:await sha256(presidentKey)});const row=Array.isArray(rows)?rows[0]:null;const caps=Array.isArray(row?.capabilities)?row.capabilities:[];if(!row||!caps.includes("president"))return json({error:"invalid_credentials"},403);const sessionToken=randomToken(),sessionHash=await sha256(sessionToken),expiresAt=new Date(Date.now()+12*60*60*1000).toISOString();await rpc("diamond_create_session",{p_identity_id:row.identity_id,p_session_hash:sessionHash,p_expires_at:expiresAt});await rpc("diamond_write_audit",{p_session_hash:sessionHash,p_action:"president_login",p_target_type:"identity",p_target_id:setkaId,p_payload:{gateway:"diamond-president-v2",apiVersion:4}});return json({ok:true,sessionToken,expiresAt,setkaId,capabilities:caps})}
 const session=await resolveSession(req.headers.get("x-setka-session")||text(body.sessionToken,256));if(!session)return json({error:"invalid_session"},401);
 if(action==="logout"){await rpc("diamond_write_audit",{p_session_hash:session.hash,p_action:"president_logout",p_target_type:"identity",p_target_id:session.setka_id,p_payload:{gateway:"diamond-president-v2"}});await rpc("diamond_revoke_session",{p_session_hash:session.hash});return json({ok:true})}
 if(action==="dashboard"){const [core,live,access,timeMachine,flow,architecture]=await Promise.all([rpc("diamond_core_snapshot",{p_session_hash:session.hash}),liveSnapshot(),rpc("diamond_access_spine_snapshot",{p_session_hash:session.hash}),rpc("diamond_time_machine_snapshot",{p_session_hash:session.hash}),rpc("diamond_flow_snapshot",{p_session_hash:session.hash}),rpc("diamond_architecture_snapshot",{p_session_hash:session.hash})]);return json({ok:true,apiVersion:4,core,live,access,timeMachine,flow,architecture})}
 if(action==="architecture_snapshot")return json({ok:true,architecture:await rpc("diamond_architecture_snapshot",{p_session_hash:session.hash})});
 if(action==="role_perspective")return json({ok:true,perspective:await rpc("diamond_role_perspective",{p_session_hash:session.hash,p_role_key:text(body.roleKey,120)})});
 if(action==="activate_checkpoint")return json(await rpc("diamond_activate_checkpoint",{p_session_hash:session.hash,p_checkpoint:text(body.checkpoint,120),p_reason:text(body.reason,500)}));
 if(action==="set_floor_door")return json(await rpc("diamond_set_floor_door",{p_session_hash:session.hash,p_floor_key:text(body.floorKey,120),p_state:text(body.state,40),p_reason:text(body.reason,500)}));
 if(action==="set_cabinet_door")return json(await rpc("diamond_set_cabinet_door",{p_session_hash:session.hash,p_cabinet_key:text(body.cabinetKey,120),p_state:text(body.state,40),p_reason:text(body.reason,500)}));
 if(action==="issue_identity")return json(await rpc("diamond_issue_identity",{p_session_hash:session.hash,p_role_key:body.roleKey?text(body.roleKey,120):null,p_note:text(body.note,500)}));
 if(action==="assign_role")return json(await rpc("diamond_assign_role",{p_session_hash:session.hash,p_setka_id:text(body.setkaId,80).toUpperCase(),p_role_key:text(body.roleKey,120),p_scope:body.scope&&typeof body.scope==="object"?body.scope:{},p_note:text(body.note,500)}));
 if(action==="flow_create")return json(await rpc("diamond_flow_create",{p_session_hash:session.hash,p_sender_role_key:text(body.senderRoleKey,120),p_kind:text(body.kind,40),p_subject:text(body.subject,240),p_recipient_type:text(body.recipientType,40),p_recipient_ref:text(body.recipientRef,240),p_body:text(body.body,10000),p_priority:text(body.priority||"normal",40),p_requested_capability:body.requestedCapability?text(body.requestedCapability,160):null,p_object_type:body.objectType?text(body.objectType,120):null,p_object_id:body.objectId?text(body.objectId,240):null}));
 if(action==="flow_snapshot")return json({ok:true,flow:await rpc("diamond_flow_snapshot",{p_session_hash:session.hash})});
 if(action==="me")return json({ok:true,setkaId:session.setka_id,capabilities:session.capabilities,expiresAt:session.expires_at});return json({error:"unknown_action"},400)}catch(e){console.error("diamond-president-v2",e);return json({error:"server_error",detail:String(e?.message||e)},500)}});