// @ts-nocheck
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
const SHIP="SHIP-SETKA-MOTHER",COMPUTER="SETKA-ONBOARD-COMPUTER",PRESIDENT="SETKA-0001-0001";
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store,max-age=0","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-setka-session","Access-Control-Allow-Methods":"POST,OPTIONS","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer"};
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H});
const text=(v:any,m=2000)=>String(v??"").trim().slice(0,m);
const lim=(v:any,d=100,m=500)=>Math.max(1,Math.min(m,Number(v)||d));
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function rpc(name:string,args:any={}){const r=await db.rpc(name,args);if(r.error)throw r.error;return r.data}
async function actor(req:Request,body:any){const tok=text(req.headers.get("x-setka-session")||body.sessionToken,256);if(!tok)return null;const hash=await sha256(tok);const a=await rpc("foundation_session_actor_v018",{p_session_hash:hash}).catch(()=>null);if(!a?.identityId||!a?.president)return null;return {...a,hash}}
async function q(name:string,opt:any={}){try{let x=db.schema("foundation").from(name).select("*");for(const [k,v] of (opt.eq||[]))x=x.eq(k,v);for(const [k,v] of (opt.like||[]))x=x.like(k,v);if(opt.order)x=x.order(opt.order,{ascending:false});x=x.limit(opt.limit||100);const r=await x;if(r.error)throw r.error;return r.data||[]}catch(e){return {__error:String(e?.message||e),__source:`foundation.${name}`}}}
async function one(name:string,opt:any={}){const r:any=await q(name,{...opt,limit:1});return Array.isArray(r)?(r[0]||null):r}
const sources={
BRIDGE:["ship_registry_current_v1","ship_computers","mission_cards","atomic_tasks","capability_command_available_v1","child ships"],
VERSTAK:["verstak_user_projects","verstak_project_compartments","verstak_ship_events","verstak_ui_pins","ship_nodes"],
CREW:["ship_scoped_crew_current_v1","ship_position_index","ship_sector_positions_v1","identity_assignments","synthetic_duty_current","synthetic_professional_cards"],
KNOWLEDGE:["setka_entity_card_v6","setka_canonical_spine","entity_relation_registry_v2","entity_source_links","entity_semantic_source_gaps_v1","foundation_constants_workspace_v018"],
ENGINE:["synthetic_neural_runs","synthetic_runtime_admissions","synthetic_runtime_sessions","ship_local_integrations","memory_physiology_current_v2","capability_command_catalog"],
SECURITY:["canon_guard_events","architecture_admissions","identity_authority_current_v1","session_hash_admission_health_v1","runtime_admission_class_audit_v1","entity_integrity_health_v1"],
OBSERVATORY:["system_transcript_events","system_reports","ship_computer_event_feed_v1","entity_pulse_current_v2","system_time_spine_health_v1","canonical_graphs"],
POLYGONS:["ship_pocket_core_experiments","ghost_ship_instances","crown_mission_experiments","polygon_local_transcript_events","synthetic_field_missions"],
HOLD:["ship_storage_containers","entity_candidate_incubator_active_v1","entity_candidate_incubator_cold_archive_v1","ephemeral_memory_archive_manifests_v1","memory_compaction_capsules_v1"]};
async function section(key:string,a:any){switch(key){
case"BRIDGE":return{ship:await one("ship_registry_current_v1",{eq:[["ship_code",SHIP]]}),computer:await one("ship_computers",{eq:[["computer_key",COMPUTER]]}),children:await q("ship_registry_current_v1",{eq:[["parent_ship_code",SHIP]],limit:100}),missions:await q("mission_cards",{order:"updated_at",limit:80}),tasks:await q("atomic_tasks",{order:"updated_at",limit:120}),commands:await rpc("capability_command_available_v1",{p_actor_setka_id:PRESIDENT,p_scope_kind:"SHIP",p_scope_ref:SHIP}).catch(()=>[])};
case"VERSTAK":return{projects:await q("verstak_user_projects",{order:"updated_at",limit:100}),compartments:await q("verstak_project_compartments",{order:"created_at",limit:150}),events:await q("verstak_ship_events",{order:"occurred_at",limit:120}),pins:await q("verstak_ui_pins",{order:"created_at",limit:120}),nodes:await q("ship_nodes",{limit:120})};
case"CREW":return{crew:await q("ship_scoped_crew_current_v1",{eq:[["ship_code",SHIP]],limit:150}),positions:await q("ship_position_index",{limit:180}),sectorPositions:await q("ship_sector_positions_v1",{like:[["sector_ref","SHIP/SETKA/%"]],limit:220}),identities:await q("identity_assignments",{limit:220}),duties:await q("synthetic_duty_current",{limit:220}),professional:await q("synthetic_professional_cards",{limit:120})};
case"KNOWLEDGE":return{entities:await q("setka_entity_card_v6",{limit:250}),spine:await q("setka_canonical_spine",{limit:150}),relations:await q("entity_relation_registry_v2",{limit:180}),sources:await q("entity_source_links",{order:"created_at",limit:140}),semanticGaps:await q("entity_semantic_source_gaps_v1",{limit:140}),constants:await rpc("foundation_constants_workspace_v018",{p_session_hash:a.hash}).catch(()=>null)};
case"ENGINE":return{neuralRuns:await q("synthetic_neural_runs",{order:"created_at",limit:120}),runtimeAdmissions:await q("synthetic_runtime_admissions",{order:"admitted_at",limit:120}),runtimeSessions:await q("synthetic_runtime_sessions",{order:"created_at",limit:120}),integrations:await q("ship_local_integrations",{limit:120}),memory:await q("memory_physiology_current_v2",{limit:80}),capabilities:await q("capability_command_catalog",{limit:180})};
case"SECURITY":return{guards:await q("canon_guard_events",{order:"created_at",limit:140}),admissions:await q("architecture_admissions",{order:"requested_at",limit:140}),authority:await q("identity_authority_current_v1",{limit:140}),sessionHealth:await q("session_hash_admission_health_v1",{limit:120}),runtimeAudit:await q("runtime_admission_class_audit_v1",{limit:140}),integrity:await q("entity_integrity_health_v1",{limit:140})};
case"OBSERVATORY":return{transcript:await rpc("foundation_system_transcript_v018",{p_session_hash:a.hash,p_limit:180,p_before:null}).catch(()=>null),reports:await q("system_reports",{order:"generated_at",limit:140}),computerFeed:await q("ship_computer_event_feed_v1",{limit:140}),pulse:await q("entity_pulse_current_v2",{limit:140}),timeSpine:await q("system_time_spine_health_v1",{limit:80}),graphs:await q("canonical_graphs",{order:"created_at",limit:100})};
case"POLYGONS":return{pocketCore:await q("ship_pocket_core_experiments",{order:"created_at",limit:120}),ghostFleet:await q("ghost_ship_instances",{order:"created_at",limit:140}),crown:await q("crown_mission_experiments",{order:"created_at",limit:120}),localTranscript:await q("polygon_local_transcript_events",{order:"created_at",limit:140}),fieldMissions:await q("synthetic_field_missions",{order:"prepared_at",limit:140})};
case"HOLD":return{containers:await q("ship_storage_containers",{limit:170}),incubator:await q("entity_candidate_incubator_active_v1",{limit:170}),coldArchive:await q("entity_candidate_incubator_cold_archive_v1",{limit:170}),memoryArchives:await q("ephemeral_memory_archive_manifests_v1",{order:"created_at",limit:120}),compaction:await q("memory_compaction_capsules_v1",{order:"prepared_at",limit:120})};
default:return{};}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return json({error:"method_not_allowed"},405);try{const body=await req.json().catch(()=>({}));const a=await actor(req,body);if(!a)return json({error:"invalid_president_session"},401);const action=text(body.action,80);
if(action==="bootstrap"){const [ship,computer,sectors,crew,children,pins,quick,inbox]=await Promise.all([one("ship_registry_current_v1",{eq:[["ship_code",SHIP]]}),one("ship_computers",{eq:[["computer_key",COMPUTER]]}),q("ship_sectors",{like:[["sector_ref","SHIP/SETKA%"]],limit:60}),q("ship_scoped_crew_current_v1",{eq:[["ship_code",SHIP]],limit:180}),q("ship_registry_current_v1",{eq:[["parent_ship_code",SHIP]],limit:120}),rpc("foundation_pin_list_v018",{p_session_hash:a.hash,p_version:"",p_surface:"president"}).catch(()=>({pins:[]})),rpc("ship_computer_quick_actions_v1",{p_actor_setka_id:PRESIDENT,p_computer_key:COMPUTER,p_limit:12}).catch(()=>({actions:[]})),rpc("ship_computer_event_inbox_v1",{p_computer_key:COMPUTER,p_viewer_setka_id:PRESIDENT,p_limit:24,p_only_unread:false,p_min_importance:0}).catch(()=>({events:[]}))]);return json({ok:true,asOf:new Date().toISOString(),actor:a,ship,computer,sectors:Array.isArray(sectors)?sectors:[],crew:Array.isArray(crew)?crew:[],children:Array.isArray(children)?children:[],pins:pins?.pins||[],quickActions:(quick?.actions||quick?.items||[]).map((x:any)=>({...x,title:x.prompt||x.label||x.commandCode||"Действие"})),eventInbox:inbox?.events||[],sourceMap:sources})}
if(action==="section"){const key=text(body.key,30).toUpperCase();return json({ok:true,key,sources:sources[key]||[],data:await section(key,a)})}
if(action==="computer_chat")return json({ok:true,result:await rpc("ship_computer_human_language_v22",{p_actor_setka_id:PRESIDENT,p_computer_key:COMPUTER,p_message:text(body.message,6000)})});
if(action==="quick_actions"){const qx=await rpc("ship_computer_quick_actions_v1",{p_actor_setka_id:PRESIDENT,p_computer_key:COMPUTER,p_limit:lim(body.limit,12,30)});return json({ok:true,items:(qx?.actions||qx?.items||[]).map((x:any)=>({...x,title:x.prompt||x.label||x.commandCode||"Действие"}))})}
if(action==="computer_events"){const x=await rpc("ship_computer_event_inbox_v1",{p_computer_key:COMPUTER,p_viewer_setka_id:PRESIDENT,p_limit:lim(body.limit,50,100),p_only_unread:Boolean(body.onlyUnread),p_min_importance:Number(body.minImportance)||0});return json({ok:true,items:x?.events||[]})}
if(action==="computer_event_reply")return json({ok:true,result:await rpc("ship_computer_event_reply_v1",{p_computer_key:COMPUTER,p_actor_setka_id:PRESIDENT,p_event_key:text(body.eventKey,200),p_input_text:text(body.message,6000),p_payload:body.payload&&typeof body.payload==="object"?body.payload:{}})});
if(action==="computer_event_mark")return json({ok:true,result:await rpc("ship_computer_event_mark_v1",{p_computer_key:COMPUTER,p_actor_setka_id:PRESIDENT,p_event_key:text(body.eventKey,200),p_state:text(body.state,30)})});
if(action==="commands")return json({ok:true,items:await rpc("capability_command_available_v1",{p_actor_setka_id:PRESIDENT,p_scope_kind:text(body.scopeKind,30)||"SHIP",p_scope_ref:text(body.scopeRef,200)||SHIP})});
if(action==="command_submit")return json({ok:true,result:await rpc("capability_command_submit_v1",{p_actor_setka_id:PRESIDENT,p_command_code:text(body.commandCode,120),p_arguments:body.arguments&&typeof body.arguments==="object"?body.arguments:{},p_scope_kind:text(body.scopeKind,30)||"SHIP",p_scope_ref:text(body.scopeRef,200)||SHIP,p_actor_channel:"PRESIDENT_FRONT",p_idempotency_key:text(body.idempotencyKey,160)||crypto.randomUUID(),p_auto_execute:Boolean(body.autoExecute)})});
if(action==="pins")return json(await rpc("foundation_pin_list_v018",{p_session_hash:a.hash,p_version:text(body.version,30),p_surface:text(body.surface,30)||"president"}));
if(action==="pin_thread")return json(await rpc("foundation_pin_thread_v018",{p_session_hash:a.hash,p_pin_code:text(body.pinCode,40).toUpperCase()}));
if(action==="pin_message")return json(await rpc("foundation_pin_message_create_v018",{p_session_hash:a.hash,p_pin_code:text(body.pinCode,40).toUpperCase(),p_message:text(body.message,6000)}));
if(action==="pin_status")return json(await rpc("foundation_pin_status_v018",{p_session_hash:a.hash,p_pin_code:text(body.pinCode,40).toUpperCase(),p_status:text(body.status,30),p_implemented_in_version:text(body.implementedInVersion,30)}));
if(action==="pin_review")return json(await rpc("foundation_pin_review_v018",{p_session_hash:a.hash,p_pin_code:text(body.pinCode,40).toUpperCase(),p_decision:text(body.decision,20)}));
if(action==="transcript")return json({ok:true,items:await rpc("foundation_system_transcript_v018",{p_session_hash:a.hash,p_limit:lim(body.limit,250),p_before:body.before?text(body.before,80):null})});
if(action==="traces")return json({ok:true,...await rpc("diamond_trace_list_v2",{p_session_hash:a.hash,p_limit:lim(body.limit,80,100)})});
if(action==="versions")return json({ok:true,manifest:await rpc("foundation_control_manifest")});
if(action==="identity_create"){const raw=`KEY-${crypto.randomUUID().replaceAll("-","").slice(0,18).toUpperCase().match(/.{1,6}/g)?.join("-")}`;const out=await rpc("foundation_issue_identity_v018",{p_session_hash:a.hash,p_display_name:text(body.displayName,120),p_secret_hash:await sha256(raw),p_nature:text(body.nature,20)||"human",p_front_enabled:Boolean(body.frontEnabled),p_back_enabled:Boolean(body.backEnabled),p_task:text(body.task,2000)||null,p_personality:text(body.personality,2000)||null});return json({ok:true,result:out,personalKey:raw})}
if(action==="report_generate")return json({ok:true,result:await rpc("generate_system_report_v1",{p_period_hours:Math.max(1,Number(body.periodHours)||24),p_report_kind:text(body.reportKind,80)||"PRESIDENT_ON_DEMAND",p_request_text:text(body.requestText,4000),p_requested_by_kind:"PRESIDENT",p_requested_by_ref:PRESIDENT,p_actor_setka_id:PRESIDENT})});
return json({error:"unknown_action"},400)}catch(e){console.error("setka-mother-president-v2",e);return json({error:"server_error",detail:String(e?.message||e)},500)}});