// @ts-nocheck
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store,max-age=0","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,authorization,x-setka-session","Access-Control-Allow-Methods":"POST,OPTIONS","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer"};
const json=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H}); const text=(v:any,m=10000)=>String(v??"").trim().slice(0,m); const num=(v:any,f=0)=>Number.isFinite(Number(v))?Number(v):f;
async function sha256(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")} function randomToken(bytes=32){const a=new Uint8Array(bytes);crypto.getRandomValues(a);return [...a].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function rpc(name:string,args:Record<string,unknown>){const q=await db.rpc(name,args);if(q.error)throw q.error;return q.data}
async function resolveSession(raw:string){const token=text(raw,256);if(!token)return null;const hash=await sha256(token);const rows=await rpc("diamond_resolve_session",{p_session_hash:hash});const row=Array.isArray(rows)?rows[0]:null;if(!row)return null;const caps=Array.isArray(row.capabilities)?row.capabilities:[];if(!caps.includes("president"))return null;await rpc("diamond_touch_session",{p_session_hash:hash});return {...row,hash,capabilities:caps}}
async function liveSnapshot(){const [p,e,f,v,facts,c,pf]=await Promise.all([db.from("prototype_v35_participant_facts").select("device_id",{count:"exact",head:true}),db.from("prototype_v35_pattern_exposures").select("exposure_id",{count:"exact",head:true}),db.from("prototype_v35_favorites").select("config_key",{count:"exact",head:true}),db.from("prototype_v35_visits").select("visit_id",{count:"exact",head:true}),db.from("prototype_v35_participant_facts").select("device_id,total_pattern_ms,session_count,active_days,note_count"),db.from("prototype_v35_config_facts").select("config_key",{count:"exact",head:true}),db.from("prototype_v35_pattern_facts").select("pattern_id,total_ms,exposure_count,favorite_configs,session_count")]);for(const q of [p,e,f,v,facts,c,pf])if(q.error)throw q.error;const people=facts.data||[];return{asOf:new Date().toISOString(),participants:p.count||0,exposures:e.count||0,favorites:f.count||0,visits:v.count||0,configs:c.count||0,sessions:people.reduce((s,x)=>s+num(x.session_count),0),notes:people.reduce((s,x)=>s+num(x.note_count),0),totalPatternMs:people.reduce((s,x)=>s+num(x.total_pattern_ms),0),patterns:(pf.data||[]).map(x=>({patternId:x.pattern_id,totalMs:num(x.total_ms),exposures:num(x.exposure_count),saves:num(x.favorite_configs),sessions:num(x.session_count)}))}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return json({error:"method_not_allowed"},405);try{const body=await req.json().catch(()=>({})),action=text(body.action,80);
 if(action==="login"){const setkaId=text(body.setkaId,80).toUpperCase(),presidentKey=text(body.presidentKey,300);if(!setkaId||!presidentKey)return json({error:"invalid_credentials"},403);const rows=await rpc("diamond_resolve_credentials",{p_setka_id:setkaId,p_secret_hash:await sha256(presidentKey)}),row=Array.isArray(rows)?rows[0]:null,caps=Array.isArray(row?.capabilities)?row.capabilities:[];if(!row||!caps.includes("president"))return json({error:"invalid_credentials"},403);const sessionToken=randomToken(),sessionHash=await sha256(sessionToken),expiresAt=new Date(Date.now()+12*60*60*1000).toISOString();await rpc("diamond_create_session",{p_identity_id:row.identity_id,p_session_hash:sessionHash,p_expires_at:expiresAt});await rpc("diamond_write_audit",{p_session_hash:sessionHash,p_action:"president_login",p_target_type:"identity",p_target_id:setkaId,p_payload:{gateway:"diamond-president-v3",apiVersion:9}});return json({ok:true,sessionToken,expiresAt,setkaId,capabilities:caps})}
 const s=await resolveSession(req.headers.get("x-setka-session")||text(body.sessionToken,256));if(!s)return json({error:"invalid_session"},401);
 if(action==="logout"){await rpc("diamond_write_audit",{p_session_hash:s.hash,p_action:"president_logout",p_target_type:"identity",p_target_id:s.setka_id,p_payload:{gateway:"diamond-president-v3"}});await rpc("diamond_revoke_session",{p_session_hash:s.hash});return json({ok:true})}
 if(action==="dashboard"){const [core,live,access,timeMachine,flow,architecture,simulation,blueprint]=await Promise.all([rpc("diamond_core_snapshot",{p_session_hash:s.hash}),liveSnapshot(),rpc("diamond_access_spine_snapshot",{p_session_hash:s.hash}),rpc("diamond_time_machine_snapshot",{p_session_hash:s.hash}),rpc("diamond_flow_snapshot",{p_session_hash:s.hash}),rpc("diamond_architecture_snapshot",{p_session_hash:s.hash}),rpc("diamond_simulation_snapshot",{p_session_hash:s.hash}),rpc("diamond_blueprint_snapshot",{p_session_hash:s.hash})]);return json({ok:true,apiVersion:9,core,live,access,timeMachine,flow,architecture,simulation,blueprint})}
 if(action==="role_perspective")return json({ok:true,perspective:await rpc("diamond_role_perspective",{p_session_hash:s.hash,p_role_key:text(body.roleKey,120)})});
 if(action==="activate_checkpoint")return json(await rpc("diamond_activate_checkpoint",{p_session_hash:s.hash,p_checkpoint:text(body.checkpoint,120),p_reason:text(body.reason,500)}));
 if(action==="set_floor_door")return json(await rpc("diamond_set_floor_door",{p_session_hash:s.hash,p_floor_key:text(body.floorKey,120),p_state:text(body.state,40),p_reason:text(body.reason,500)}));
 if(action==="set_cabinet_door")return json(await rpc("diamond_set_cabinet_door",{p_session_hash:s.hash,p_cabinet_key:text(body.cabinetKey,120),p_state:text(body.state,40),p_reason:text(body.reason,500)}));
 if(action==="issue_identity")return json(await rpc("diamond_issue_identity",{p_session_hash:s.hash,p_role_key:body.roleKey?text(body.roleKey,120):null,p_note:text(body.note,500)}));
 if(action==="assign_role")return json(await rpc("diamond_assign_role",{p_session_hash:s.hash,p_setka_id:text(body.setkaId,80).toUpperCase(),p_role_key:text(body.roleKey,120),p_scope:body.scope&&typeof body.scope==="object"?body.scope:{},p_note:text(body.note,500)}));
 if(action==="flow_create")return json(await rpc("diamond_flow_create",{p_session_hash:s.hash,p_sender_role_key:text(body.senderRoleKey,120),p_kind:text(body.kind,40),p_subject:text(body.subject,240),p_recipient_type:text(body.recipientType,40),p_recipient_ref:text(body.recipientRef,240),p_body:text(body.body,10000),p_priority:text(body.priority||"normal",40),p_requested_capability:body.requestedCapability?text(body.requestedCapability,160):null,p_object_type:body.objectType?text(body.objectType,120):null,p_object_id:body.objectId?text(body.objectId,240):null}));
 if(action==="architecture_create_node")return json(await rpc("diamond_architecture_create_node",{p_session_hash:s.hash,p_node_key:text(body.nodeKey,120),p_title_en:text(body.titleEn,240),p_title_ru:text(body.titleRu,240),p_description_en:text(body.descriptionEn,600),p_description_ru:text(body.descriptionRu,600),p_node_type:text(body.nodeType,40),p_criticality:text(body.criticality,40),p_disconnect_policy:text(body.disconnectPolicy,40)}));
 if(action==="architecture_connect")return json(await rpc("diamond_architecture_connect",{p_session_hash:s.hash,p_edge_key:text(body.edgeKey,160),p_from_node:text(body.fromNode,120),p_to_node:text(body.toNode,120),p_edge_type:text(body.edgeType,40),p_criticality:text(body.criticality,40),p_break_policy:text(body.breakPolicy,40),p_binding_mode:text(body.bindingMode,40),p_note:text(body.note,800)}));
 if(action==="architecture_set_edge_state")return json(await rpc("diamond_architecture_set_edge_state",{p_session_hash:s.hash,p_edge_key:text(body.edgeKey,160),p_active:Boolean(body.active),p_reason:text(body.reason,800)}));
 if(action==="simulation_create_persona")return json(await rpc("diamond_simulation_create_persona",{p_session_hash:s.hash,p_display_name:text(body.displayName,120),p_archetype:text(body.archetype,120),p_role_key:text(body.roleKey,120),p_characteristics:body.characteristics&&typeof body.characteristics==='object'?body.characteristics:{},p_behavior_policy:body.behaviorPolicy&&typeof body.behaviorPolicy==='object'?body.behaviorPolicy:{}}));
 if(action==="simulation_run")return json(await rpc("diamond_simulation_run",{p_session_hash:s.hash,p_persona_keys:Array.isArray(body.personaKeys)?body.personaKeys.map((x:any)=>text(x,120)):[],p_checkpoint:body.checkpoint?text(body.checkpoint,120):null,p_target_type:text(body.targetType||'headquarters',40),p_target_key:text(body.targetKey||'',160),p_isolation_mode:text(body.isolationMode||'integrated',40),p_scenario_key:text(body.scenarioKey||'behavioral',80)}));
 if(action==="blueprint_add_draft")return json(await rpc("diamond_blueprint_add_draft",{p_session_hash:s.hash,p_item_type:text(body.itemType,40),p_parent_key:text(body.parentKey||'',160),p_title:text(body.title,160),p_metadata:body.metadata&&typeof body.metadata==='object'?body.metadata:{}}));
 if(action==="blueprint_remove_draft")return json(await rpc("diamond_blueprint_remove_draft",{p_session_hash:s.hash,p_draft_key:text(body.draftKey,160)}));
 if(action==="trace_save"){const events=Array.isArray(body.events)?body.events:[];const result=await rpc("diamond_trace_save",{p_session_hash:s.hash,p_front_version:text(body.frontVersion,120),p_duration_ms:Math.max(0,Math.round(num(body.durationMs))),p_viewport:body.viewport&&typeof body.viewport==='object'?body.viewport:{},p_summary:body.summary&&typeof body.summary==='object'?body.summary:{},p_events:events});await rpc("diamond_write_audit",{p_session_hash:s.hash,p_action:"interaction_trace_saved",p_target_type:"trace",p_target_id:text(result?.traceCode||'',120),p_payload:{frontVersion:text(body.frontVersion,120),eventCount:events.length,durationMs:Math.max(0,Math.round(num(body.durationMs)))}});return json(result)}
 if(action==="trace_list")return json(await rpc("diamond_trace_list",{p_session_hash:s.hash,p_limit:Math.max(1,Math.min(100,Math.round(num(body.limit,30))))}));
 if(action==="trace_get")return json(await rpc("diamond_trace_get",{p_session_hash:s.hash,p_trace_code:text(body.traceCode,80).toUpperCase()}));
 if(action==="trace_start"){const result=await rpc("diamond_trace_start",{p_session_hash:s.hash,p_checkpoint:text(body.checkpoint,120),p_front_version:text(body.frontVersion,120),p_viewport:body.viewport&&typeof body.viewport==='object'?body.viewport:{}});await rpc("diamond_write_audit",{p_session_hash:s.hash,p_action:"research_trace_started",p_target_type:"trace",p_target_id:text(result?.traceCode||'',120),p_payload:{checkpoint:text(body.checkpoint,120),frontVersion:text(body.frontVersion,120)}});return json(result)}
 if(action==="trace_append"){const events=Array.isArray(body.events)?body.events:[];return json(await rpc("diamond_trace_append",{p_session_hash:s.hash,p_trace_code:text(body.traceCode,80).toUpperCase(),p_checkpoint:text(body.checkpoint,120),p_front_version:text(body.frontVersion,120),p_segment_key:text(body.segmentKey,120),p_chunk_seq:Math.max(0,Math.round(num(body.chunkSeq))),p_viewport:body.viewport&&typeof body.viewport==='object'?body.viewport:{},p_summary:body.summary&&typeof body.summary==='object'?body.summary:{},p_events:events}))}
 if(action==="trace_finalize"){const result=await rpc("diamond_trace_finalize",{p_session_hash:s.hash,p_trace_code:text(body.traceCode,80).toUpperCase(),p_title:text(body.title,240),p_comment:text(body.comment,6000),p_summary:body.summary&&typeof body.summary==='object'?body.summary:{}});await rpc("diamond_write_audit",{p_session_hash:s.hash,p_action:"research_trace_finalized",p_target_type:"trace",p_target_id:text(result?.traceCode||'',120),p_payload:{title:text(body.title,240),visitedVersions:result?.visitedVersions||[]}});return json(result)}
 if(action==="trace_list_v2")return json(await rpc("diamond_trace_list_v2",{p_session_hash:s.hash,p_limit:Math.max(1,Math.min(100,Math.round(num(body.limit,30))))}));
 if(action==="trace_get_v2")return json(await rpc("diamond_trace_get_v2",{p_session_hash:s.hash,p_trace_code:text(body.traceCode,80).toUpperCase()}));
 if(action==="me")return json({ok:true,setkaId:s.setka_id,capabilities:s.capabilities,expiresAt:s.expires_at});return json({error:"unknown_action"},400)}catch(e){console.error("diamond-president-v3",e);return json({error:"server_error",detail:String(e?.message||e)},500)}});
