// @ts-nocheck
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8"};
const J=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H});
const T=(v,m=500)=>String(v??"").trim().slice(0,m);const N=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;const C=(v,a,b)=>Math.min(b,Math.max(a,v));
async function sha(v){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("")}
function randomToken(){const a=new Uint8Array(32);crypto.getRandomValues(a);return Array.from(a,b=>b.toString(16).padStart(2,"0")).join("")}
function canon(v){if(Array.isArray(v))return v.map(canon);if(v&&typeof v==="object")return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canon(v[k])]));if(typeof v==="number")return Math.round(v*100000)/100000;return v}
async function cfgHash(patternId,version,config){return sha(`${patternId}|${version}|${JSON.stringify(canon(config||{}))}`)}
async function requireSession(id,token){if(!id||!token)return null;const h=await sha(token);const q=await db.from("sessions").select("id,participant_id,device_hash").eq("id",id).eq("session_token_hash",h).maybeSingle();return q.data||null}
async function requireAdmin(key){if(!key)return false;const h=await sha(key.trim());const q=await db.from("admin_keys").select("id").eq("key_hash",h).eq("active",true).maybeSingle();return !!q.data}
async function communityRows(){const q=await db.from("community_configs").select("id,pattern_id,pattern_version,config_hash,config,preview_frame,parent_config_id,created_at").order("created_at",{ascending:false}).limit(300);if(q.error)throw q.error;const ids=(q.data||[]).map(x=>x.id);if(!ids.length)return[];const s=await db.from("community_saves").select("config_id").in("config_id",ids);if(s.error)throw s.error;const count=new Map();for(const x of s.data||[])count.set(x.config_id,(count.get(x.config_id)||0)+1);return(q.data||[]).map(x=>({...x,saveCount:count.get(x.id)||0})).filter(x=>x.saveCount>0).sort((a,b)=>b.saveCount-a.saveCount||Date.parse(b.created_at)-Date.parse(a.created_at))}
async function findOrCreateSymptom(participantId,s){const name=T(s?.name,80);if(!name)return null;const norm=name.toLowerCase();let q=await db.from("participant_symptoms").select("id").eq("participant_id",participantId).eq("name_norm",norm).maybeSingle();if(q.error)throw q.error;if(q.data?.id){await db.from("participant_symptoms").update({active:s?.active!==false,updated_at:new Date().toISOString()}).eq("id",q.data.id);return q.data.id}const ins=await db.from("participant_symptoms").insert({participant_id:participantId,symptom_key:T(s?.symptomKey,60)||null,name,active:s?.active!==false}).select("id").single();if(ins.error)throw ins.error;return ins.data.id}
function asIso(v,fallback=new Date()){const d=v?new Date(v):fallback;return Number.isNaN(d.getTime())?fallback.toISOString():d.toISOString()}
async function ensureGuestTrial(body){const archiveId=T(body.archiveId,120);if(!archiveId)throw new Error("missing_archive_id");const started=asIso(body.startedAt||Date.now());const expires=asIso(body.expiresAt||new Date(Date.parse(started)+3600000));const row={archive_id:archiveId,started_at:started,expires_at:expires,last_seen_at:new Date().toISOString(),user_agent:T(body.userAgent,1000)||null,viewport:body.viewport&&typeof body.viewport==="object"?body.viewport:{},updated_at:new Date().toISOString()};const q=await db.from("guest_trials").upsert(row,{onConflict:"archive_id",ignoreDuplicates:false});if(q.error)throw q.error;return archiveId}
async function upsertGuestSessions(archiveId,sessions){for(const gs of (Array.isArray(sessions)?sessions.slice(0,50):[])){const gid=T(gs?.id,120);if(!gid)continue;const row={archive_id:archiveId,guest_session_id:gid,started_at:gs.startedAt?asIso(gs.startedAt):null,ended_at:gs.endedAt?asIso(gs.endedAt):null,request_key:T(gs.requestKey,60)||null,pre_state:gs.preState==null?null:C(Math.round(N(gs.preState)),1,5),post_state:gs.postState==null?null:C(Math.round(N(gs.postState)),1,5),helped:gs.helped==null?null:C(Math.round(N(gs.helped)),0,2),planned_seconds:gs.plannedSeconds?C(Math.round(N(gs.plannedSeconds)),60,7200):null,measured_active_ms:Math.max(0,Math.round(N(gs.measuredActiveMs))),after_feedback_active_ms:Math.max(0,Math.round(N(gs.afterFeedbackActiveMs))),continued_after_feedback:!!gs.continuedAfterFeedback,completed:!!gs.completed,completion_reason:T(gs.completionReason,40)||null,usage:Array.isArray(gs.usage)?gs.usage.slice(0,300).map(u=>({patternId:T(u.patternId,100)||"tentacle-orbit",communityConfigId:u.communityConfigId||null,configHash:T(u.configHash,128)||null,startedMs:Math.max(0,Math.round(N(u.startedMs))),endedMs:Math.max(0,Math.round(N(u.endedMs))),durationMs:Math.max(0,Math.round(N(u.durationMs))),saved:!!u.saved})):[],updated_at:new Date().toISOString()};const q=await db.from("guest_trial_sessions").upsert(row,{onConflict:"archive_id,guest_session_id"});if(q.error)throw q.error}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return J({error:"method_not_allowed"},405);try{const b=await req.json();const a=T(b?.action,80);
 if(a==="public-community")return J({ok:true,items:await communityRows()});
 if(a==="guest-heartbeat"){
   const archiveId=await ensureGuestTrial(b);await upsertGuestSessions(archiveId,b.sessions);
   const summary=b.summary&&typeof b.summary==="object"?b.summary:{};
   const patch={last_seen_at:new Date().toISOString(),session_count:C(Math.round(N(summary.sessionCount,Array.isArray(b.sessions)?b.sessions.length:0)),0,1000),completed_session_count:C(Math.round(N(summary.completedSessionCount)),0,1000),note_count:C(Math.round(N(summary.noteCount)),0,10000),symptom_count:C(Math.round(N(summary.symptomCount)),0,1000),symptom_checkin_count:C(Math.round(N(summary.symptomCheckinCount)),0,10000),favorite_count:C(Math.round(N(summary.favoriteCount)),0,10000),updated_at:new Date().toISOString()};
   const q=await db.from("guest_trials").update(patch).eq("archive_id",archiveId);if(q.error)throw q.error;return J({ok:true});
 }
 if(a==="guest-events"){
   const archiveId=await ensureGuestTrial(b);const items=Array.isArray(b.items)?b.items.slice(0,120):[];if(items.length){const rows=items.map(x=>({archive_id:archiveId,event_id:T(x.eventId,140)||crypto.randomUUID(),wall_at:asIso(x.wallAt||Date.now()),event_type:T(x.type,80)||"event",payload:x.payload&&typeof x.payload==="object"?x.payload:{}}));const q=await db.from("guest_trial_events").upsert(rows,{onConflict:"archive_id,event_id",ignoreDuplicates:true});if(q.error)throw q.error}return J({ok:true,count:items.length});
 }
 if(a==="guest-id-attempt"){
   const archiveId=await ensureGuestTrial(b);const q=await db.from("guest_trials").select("id_attempt_count").eq("archive_id",archiveId).maybeSingle();if(q.error)throw q.error;const n=(q.data?.id_attempt_count||0)+1;const u=await db.from("guest_trials").update({id_attempted_at:new Date().toISOString(),id_attempt_count:n,last_seen_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("archive_id",archiveId);if(u.error)throw u.error;return J({ok:true,count:n});
 }
 if(a==="import"){
   const auth=await requireSession(T(b.sessionId,80),T(b.sessionToken,220));if(!auth)return J({error:"invalid_session"},403);
   const archive=b?.archive&&typeof b.archive==="object"?b.archive:null;if(!archive)return J({error:"missing_archive"},400);
   const archiveId=T(archive.archiveId,120)||await sha(JSON.stringify(archive).slice(0,20000));
   await ensureGuestTrial({archiveId,startedAt:archive.startedAt,expiresAt:new Date(Date.parse(archive.startedAt||Date.now())+3600000).toISOString(),userAgent:archive.userAgent,viewport:archive.viewport});
   await upsertGuestSessions(archiveId,archive.sessions);
   const guestSessions=Array.isArray(archive.sessions)?archive.sessions.slice(0,50):[];
   const sessionMap=new Map();let importedSessions=0,importedNotes=0,importedCheckins=0;
   for(const gs of guestSessions){const gid=T(gs?.id,120);if(!gid)continue;const existing=await db.from("sessions").select("id").eq("participant_id",auth.participant_id).contains("meta",{guestSessionId:gid}).maybeSingle();if(existing.error)throw existing.error;if(existing.data?.id){sessionMap.set(gid,existing.data.id);continue}
     const start=new Date(gs.startedAt||Date.now()),end=new Date(gs.endedAt||gs.feedbackSubmittedAt||Date.now());const tokenHash=await sha(randomToken());const row={participant_id:auth.participant_id,device_hash:auth.device_hash||null,session_token_hash:tokenHash,started_at:Number.isNaN(start.getTime())?new Date().toISOString():start.toISOString(),ended_at:Number.isNaN(end.getTime())?new Date().toISOString():end.toISOString(),last_seen_at:Number.isNaN(end.getTime())?new Date().toISOString():end.toISOString(),app_version:"setka-guest-v11",user_agent:T(archive.userAgent,1000),viewport:archive.viewport||{},meta:{guestImport:true,guestArchiveId:archiveId,guestSessionId:gid},request_key:T(gs.requestKey,60)||null,pre_state:gs.preState==null?null:C(Math.round(N(gs.preState)),1,5),post_state:gs.postState==null?null:C(Math.round(N(gs.postState)),1,5),helped:gs.helped==null?null:C(Math.round(N(gs.helped)),0,2),feedback_at:gs.feedbackSubmittedAt||null,active_ms:Math.max(0,Math.round(N(gs.measuredActiveMs))),completed:!!gs.completed,research_started:true,local_started_at:gs.startedAt||null,planned_duration_seconds:gs.plannedSeconds?C(Math.round(N(gs.plannedSeconds)),60,7200):null,timer_started_at:gs.startedAt||null,timer_deadline_at:gs.deadlineAt||null,feedback_prompted_at:gs.feedbackPromptedAt||null,feedback_submitted_at:gs.feedbackSubmittedAt||null,feedback_delay_ms:gs.feedbackDelayMs==null?null:Math.max(0,Math.round(N(gs.feedbackDelayMs))),measured_active_ms:Math.max(0,Math.round(N(gs.measuredActiveMs))),continued_after_feedback:!!gs.continuedAfterFeedback,continuation_started_at:gs.continuationStartedAt||null,continuation_ended_at:gs.continuationEndedAt||null,after_feedback_active_ms:Math.max(0,Math.round(N(gs.afterFeedbackActiveMs))),completion_reason:T(gs.completionReason,40)||null};
     const ins=await db.from("sessions").insert(row).select("id").single();if(ins.error)throw ins.error;sessionMap.set(gid,ins.data.id);importedSessions++;
     const usages=Array.isArray(gs.usage)?gs.usage.slice(0,300):[];if(usages.length){const rows=usages.map(u=>({session_id:ins.data.id,participant_id:auth.participant_id,pattern_id:T(u.patternId,100)||"tentacle-orbit",community_config_id:u.communityConfigId||null,config_hash:T(u.configHash,128)||null,started_ms:Math.max(0,Math.round(N(u.startedMs))),ended_ms:Math.max(0,Math.round(N(u.endedMs))),duration_ms:Math.max(0,Math.round(N(u.durationMs))),saved:!!u.saved}));const uq=await db.from("session_pattern_usage").insert(rows);if(uq.error)throw uq.error}
   }
   const symptomMap=new Map();for(const s of Array.isArray(archive.symptoms)?archive.symptoms.slice(0,50):[]){const sid=await findOrCreateSymptom(auth.participant_id,s);if(sid)symptomMap.set(T(s.id,120),sid)}
   const checks=Array.isArray(archive.symptomCheckins)?archive.symptomCheckins.slice(0,1000):[];const checkRows=[];for(const x of checks){const sid=symptomMap.get(T(x.symptomId,120));if(!sid)continue;const phase=["pre","post","standalone"].includes(String(x.phase))?String(x.phase):"standalone";checkRows.push({participant_id:auth.participant_id,symptom_id:sid,session_id:phase==="standalone"?null:(sessionMap.get(T(x.sessionGuestId,120))||null),phase,intensity:C(Math.round(N(x.intensity)),0,10),observed_at:x.observedAt||new Date().toISOString(),local_offset_minutes:Number.isFinite(Number(x.localOffsetMinutes))?Math.round(Number(x.localOffsetMinutes)):null,note:T(x.note,300)||null})}if(checkRows.length){const cq=await db.from("symptom_checkins").insert(checkRows);if(cq.error)throw cq.error;importedCheckins=checkRows.length}
   const notes=Array.isArray(archive.notes)?archive.notes.slice(0,1000):[];const noteRows=[];for(const n of notes){const state=n.state&&typeof n.state==="object"?n.state:{};const patternId=T(state.patternId||n.patternId,100)||null;const version=Math.max(1,Math.round(N(state.patternVersion||n.patternVersion,1)));const config=canon(state.config||n.config||{});noteRows.push({participant_id:auth.participant_id,session_id:n.sessionGuestId?sessionMap.get(T(n.sessionGuestId,120))||null:null,note_text:T(n.text,5000),phase:["measured","after_feedback","standalone"].includes(String(n.phase))?String(n.phase):"standalone",observed_at:n.observedAt||new Date().toISOString(),local_offset_minutes:Number.isFinite(Number(n.localOffsetMinutes))?Math.round(Number(n.localOffsetMinutes)):null,session_elapsed_ms:Math.max(0,Math.round(N(n.sessionElapsedMs))),request_key:T(n.requestKey,60)||null,pattern_id:patternId,pattern_version:version,source_type:T(state.sourceType||n.sourceType,60)||null,source_id:T(state.sourceId||n.sourceId,120)||null,community_config_id:state.communityId||n.communityConfigId||null,config_hash:patternId?await cfgHash(patternId,version,config):null,config,preview_frame:Number.isFinite(Number(state.frame??n.previewFrame))?Number(state.frame??n.previewFrame):null})}if(noteRows.length){const nq=await db.from("participant_notes").insert(noteRows);if(nq.error)throw nq.error;importedNotes=noteRows.length}
   const summary={session_count:guestSessions.length,completed_session_count:guestSessions.filter(x=>x.completed).length,note_count:notes.length,symptom_count:Array.isArray(archive.symptoms)?archive.symptoms.length:0,symptom_checkin_count:checks.length,updated_at:new Date().toISOString(),last_seen_at:new Date().toISOString(),converted_at:new Date().toISOString(),participant_id:auth.participant_id,conversion_session_id:auth.id};const gq=await db.from("guest_trials").update(summary).eq("archive_id",archiveId);if(gq.error)throw gq.error;
   return J({ok:true,archiveId,importedSessions,importedNotes,importedCheckins,converted:true});
 }
 if(a.startsWith("admin-")){
   if(!(await requireAdmin(T(b.adminKey,300))))return J({error:"invalid_admin_key"},403);
   if(a==="admin-guest-overview"){
     const q=await db.from("guest_trials").select("archive_id,started_at,last_seen_at,converted_at,id_attempt_count,session_count,completed_session_count,note_count,symptom_count,symptom_checkin_count,favorite_count").order("started_at",{ascending:false}).limit(5000);if(q.error)throw q.error;const rows=q.data||[];const withSessions=rows.filter(x=>x.session_count>0);const converted=rows.filter(x=>x.converted_at);const attempts=rows.filter(x=>x.id_attempt_count>0);return J({ok:true,overview:{trials:rows.length,withSessions:withSessions.length,completedSessions:rows.reduce((a,x)=>a+(x.completed_session_count||0),0),idAttempts:attempts.length,converted:converted.length,conversionRate:rows.length?converted.length/rows.length:0,sessionConversionRate:withSessions.length?withSessions.filter(x=>x.converted_at).length/withSessions.length:0}})
   }
   if(a==="admin-guest-trials"){
     const q=await db.from("guest_trials").select("*").order("started_at",{ascending:false}).limit(2000);if(q.error)throw q.error;const rows=q.data||[];const pids=[...new Set(rows.map(x=>x.participant_id).filter(Boolean))];let pm=new Map();if(pids.length){const p=await db.from("participants").select("id,access_code,label").in("id",pids);if(p.error)throw p.error;pm=new Map((p.data||[]).map(x=>[x.id,x]))}const out=[];for(const r of rows){const ev=await db.from("guest_trial_events").select("event_type,wall_at,payload").eq("archive_id",r.archive_id).order("wall_at",{ascending:false}).limit(30);if(ev.error)throw ev.error;const before=(ev.data||[]).find(x=>!r.converted_at||Date.parse(x.wall_at)<=Date.parse(r.converted_at));out.push({...r,participant:r.participant_id?pm.get(r.participant_id)||null:null,lastAction:before||null})}return J({ok:true,items:out});
   }
   if(a==="admin-guest-trial"){
     const archiveId=T(b.archiveId,120);const t=await db.from("guest_trials").select("*").eq("archive_id",archiveId).single();if(t.error)throw t.error;const s=await db.from("guest_trial_sessions").select("*").eq("archive_id",archiveId).order("started_at");if(s.error)throw s.error;const e=await db.from("guest_trial_events").select("id,event_id,wall_at,event_type,payload").eq("archive_id",archiveId).order("wall_at").limit(5000);if(e.error)throw e.error;let participant=null;if(t.data.participant_id){const p=await db.from("participants").select("id,access_code,label").eq("id",t.data.participant_id).maybeSingle();if(p.error)throw p.error;participant=p.data||null}return J({ok:true,trial:t.data,sessions:s.data||[],events:e.data||[],participant});
   }
 }
 return J({error:"unknown_action"},400)}catch(e){console.error(e);return J({error:"server_error",detail:String(e?.message||e)},500)}});